%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:49 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $o).
tff(big_f_type, type, big_f: ($i > $o)).
tff(pel22, conjecture, {$box}(({$box}((! [X:$i]: (({$box}(({$box}(p) => {$box}(big_f(X)))) & {$box}(({$box}(big_f(X)) => {$box}(p))))))) => ({$box}(({$box}(p) => {$box}((! [X1:$i]: ({$box}(big_f(X1))))))) & {$box}(({$box}((! [X1:$i]: ({$box}(big_f(X1))))) => {$box}(p))))))).
