%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:10 CEST 2022 using command 'downgrade(tff)'.
tff(f_type, type, f: ($i > $o)).
tff(kalish204, conjecture, ({$box}(({$box}(~ ((? [X:$i]: ({$box}(f(X)))))) => {$box}((! [Y:$i]: ({$box}(~ ({$box}(f(Y))))))))) & {$box}(({$box}((! [Y:$i]: ({$box}(~ ({$box}(f(Y))))))) => {$box}(~ ((? [X:$i]: ({$box}(f(X)))))))))).
