%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:01 CEST 2022 using command 'downgrade(tff)'.
tff(big_q_type, type, big_q: (($i * $i * $i) > $o)).
tff(big_p_type, type, big_p: ($i > $o)).
tff(x2131, conjecture, {$box}(({$box}((! [X:$i]: ({$box}(big_p(X))))) => (? [Y:$i]: ({$box}(({$box}((! [X:$i]: ({$box}((! [Z:$i]: ({$box}(big_q(X,Y,Z)))))))) => {$box}(~ ({$box}((! [Z:$i]: (({$box}(big_p(Z)) & {$box}(~ ({$box}(big_q(Y,Y,Z))))))))))))))))).
