%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:50 CEST 2022 using command 'downgrade(tff)'.
tff(big_p_type, type, big_p: ($i > $o)).
tff(x2108, conjecture, {$box}((! [X:$i]: ((? [Y:$i]: ({$box}(({$box}(big_p(X)) => {$box}(big_p(Y)))))))))).
