%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:05 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $o).
tff(pel7, conjecture, ({$box}(p) | {$box}(~ ({$box}(~ ({$box}(~ ({$box}(p))))))))).
