%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:50 CEST 2022 using command 'downgrade(tff)'.
tff(a_type, type, a: $i).
tff(b_type, type, b: $i).
tff(big_q_type, type, big_q: (($i * $i) > $o)).
tff(big_r_type, type, big_r: (($i * $i) > $o)).
tff(x2107, conjecture, {$box}((({$box}(big_r(a,b)) & ({$box}((! [X:$i]: ({$box}((! [Y:$i]: ({$box}(({$box}(big_r(X,Y)) => ({$box}(big_r(Y,X)) & {$box}(big_q(X,Y))))))))))) & {$box}((! [U:$i]: ({$box}((! [V:$i]: ({$box}(({$box}(big_q(U,V)) => {$box}(big_q(U,U)))))))))))) => ({$box}(big_q(a,a)) & {$box}(big_q(b,b)))))).
