#!/bin/tcsh
#----Put this in the NX0 (without semantic specifications) directory

foreach problem (*/*.p)
    set name = `basename $problem .p`
    set domain = `dirname $problem`
    foreach semantics (../semantics/*.p)
        set destproblem = ../qmltp_NX0_SEMs/$domain/${name}_`basename $semantics`
        cp $semantics $destproblem
        cat $problem | grep -v "tff(semantics" >> $destproblem
    end
end
