%------------------------------------------------------------------------------
% File     : LOG001_1 : TPTP v9.0.0. Released v9.0.0.
% Domain   : Modal logics
% Defines  : Common elements for all modal logics
% Version  : Especial.
% English  : 

% Refs     : [BBW06] Blackburn  et al. (2006), Handbook of Modal Logic
% Source   : [TPTP]
% Names    : 

% Syntax   : TBA

% Comments : 
%------------------------------------------------------------------------------
tff('[.]_decl',type,'[.]' : $o > $o ).

tff('<.>_decl',type,'<.>' : $o > $o ).

tff('{.}_decl',type,'{.}' : $o > $o ).

%------------------------------------------------------------------------------
