%%% This output was generated by embedproblem, version 1.7.2 (library version 1.3).
%%% Generated on Fri May 06 13:26:54 EDT 2022
%%% using 'modal' embedding, version 1.5.3.
%%% Logic specification used:
%%% tff(s5_cumulative_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($cumulative),($modalities) == ($modal_system_S5U)])).

thf(mworld, type, mworld: $tType).
thf(mindex, type, mindex: $tType).
thf(mrel_type, type, mrel: (mindex > (mworld > (mworld > $o)))).
thf('#cr_type', type, '#cr': mindex).
thf('#it_type', type, '#it': mindex).
thf('#p_type', type, '#p': mindex).
thf('#t_type', type, '#t': mindex).
thf('#ip_type', type, '#ip': mindex).
thf('#bank_type', type, '#bank': mindex).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: (mindex > ((mworld > $o) > (mworld > $o)))).
thf(mbox_def, definition, (mbox = (^ [R:mindex,Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: (((((mrel @ R) @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: (mindex > ((mworld > $o) > (mworld > $o)))).
thf(mdia_def, definition, (mdia = (^ [R:mindex,Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: (((((mrel @ R) @ W) @ V) & (Phi @ V)))))))).
thf('mrel_#cr_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#cr') @ W) @ V)))).
thf('mrel_#it_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#it') @ W) @ V)))).
thf('mrel_#p_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#p') @ W) @ V)))).
thf('mrel_#t_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#t') @ W) @ V)))).
thf('mrel_#ip_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#ip') @ W) @ V)))).
thf('mrel_#bank_universal', axiom, (! [W:mworld,V:mworld]: ((((mrel @ '#bank') @ W) @ V)))).
thf(eiw_di_type, type, eiw_di: ($i > (mworld > $o))).
thf(eiw_di_nonempty, axiom, (! [W:mworld]: ((? [X:$i]: (((eiw_di @ X) @ W)))))).
thf(eiw_di_cumul, axiom, (! [Index:mindex,W:mworld,V:mworld,X:$i]: (((((eiw_di @ X) @ W) & (((mrel @ Index) @ W) @ V)) => ((eiw_di @ X) @ V))))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: ((((eiw_di @ X) @ W) => ((A @ X) @ W)))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: ((((eiw_di @ X) @ W) & ((A @ X) @ W)))))))).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:49:43 CEST 2022 using command 'downgrade(tff)'.
thf(fortytwo_decl, type, fortytwo: $i).
thf(p_decl, type, p: $i).
thf(t_decl, type, t: $i).
thf(number_decl, type, number: ($i > ($i > (mworld > $o)))).
thf(code_decl, type, code: ($i > (mworld > $o))).
thf(balance_decl, type, balance: ($i > ($i > (mworld > $o)))).
thf(belongs_decl, type, belongs: ($i > ($i > (mworld > $o)))).
thf(identifiable_decl, type, identifiable: ($i > (mworld > $o))).
thf(uttered_decl, type, uttered: ($i > ($i > (mworld > $o)))).
thf(value_decl, type, value: ($i > ($i > (mworld > $o)))).
thf(hasanswer_decl, type, hasanswer: ($i > (mworld > $o))).
thf(account_decl, type, account: ($i > (mworld > $o))).
thf(axiom_4, axiom, (mlocal @ ((mbox @ '#cr') @ (mforall_di @ (^ [A:$i]: ((mexists_di @ (^ [U:$i]: (((mbox @ '#cr') @ ((mimplies @ ((mand @ ((mbox @ '#ip') @ ((belongs @ A) @ p))) @ ((mand @ ((mbox @ '#cr') @ ((mand @ (account @ A)) @ ((mand @ ((number @ A) @ fortytwo)) @ (identifiable @ A))))) @ ((uttered @ p) @ U)))) @ ((mbox @ '#cr') @ ((belongs @ A) @ p))))))))))))).
thf(axiom_5, axiom, (mlocal @ ((mbox @ '#cr') @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mexists_di @ (^ [U:$i]: (((mand @ ((mbox @ '#cr') @ ((mimplies @ ((mbox @ '#ip') @ (mexists_di @ (^ [V:$i]: (((mbox @ '#p') @ ((value @ B) @ V))))))) @ (hasanswer @ p)))) @ ((mimplies @ ((mand @ ((mbox @ '#cr') @ ((mand @ (account @ A)) @ ((mand @ ((belongs @ A) @ p)) @ ((mand @ ((balance @ A) @ B)) @ (identifiable @ B)))))) @ ((uttered @ p) @ U))) @ ((mimplies @ ((mbox @ '#cr') @ (mexists_di @ (^ [V:$i]: (((mbox @ '#p') @ ((value @ B) @ V))))))) @ (hasanswer @ p)))))))))))))))).
thf(axiom_6, axiom, (mlocal @ ((mbox @ '#cr') @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [V:$i]: ((mexists_di @ (^ [U:$i]: (((mimplies @ ((mbox @ '#cr') @ ((mand @ ((mbox @ '#it') @ ((value @ B) @ V))) @ ((mand @ ((mbox @ '#cr') @ ((mand @ (account @ A)) @ ((mand @ ((belongs @ A) @ p)) @ ((mand @ ((balance @ A) @ B)) @ (identifiable @ B)))))) @ ((uttered @ t) @ U))))) @ ((mbox @ '#cr') @ ((value @ B) @ V)))))))))))))))))).
thf(axiom_7, axiom, (mlocal @ ((mbox @ '#bank') @ (code @ fortytwo)))).
thf(axiom_8, axiom, (mlocal @ ((mbox @ '#bank') @ (mforall_di @ (^ [C:$i]: (((mimplies @ (code @ C)) @ (mexists_di @ (^ [A:$i]: (((mbox @ '#bank') @ ((mand @ (account @ A)) @ ((mand @ ((number @ A) @ C)) @ (identifiable @ A)))))))))))))).
thf(axiom_9, axiom, (mlocal @ ((mbox @ '#bank') @ (mforall_di @ (^ [A:$i]: ((mexists_di @ (^ [B:$i]: (((mbox @ '#bank') @ ((mimplies @ (account @ A)) @ ((balance @ A) @ B)))))))))))).
thf(axiom_10, axiom, (mlocal @ ((mbox @ '#bank') @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((mand @ ((balance @ A) @ B)) @ (identifiable @ A))) @ (identifiable @ B))))))))))).
thf(axiom_11, axiom, (mlocal @ ((mbox @ '#bank') @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((balance @ A) @ B)) @ (mexists_di @ (^ [V:$i]: (((mbox @ '#t') @ ((value @ B) @ V))))))))))))))).
thf(axiom_12, axiom, (mlocal @ ((mbox @ '#ip') @ (mforall_di @ (^ [A:$i]: (((mimplies @ ((mand @ (account @ A)) @ ((number @ A) @ fortytwo))) @ ((belongs @ A) @ p)))))))).
thf(axiom_13, axiom, (mlocal @ ((mbox @ '#ip') @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mand @ (account @ A)) @ ((mand @ ((number @ A) @ fortytwo)) @ ((mand @ ((balance @ A) @ B)) @ ((mimplies @ (mexists_di @ (^ [C:$i]: (((mbox @ '#p') @ ((value @ B) @ C)))))) @ (hasanswer @ p)))))))))))))).
thf(axiom_1, axiom, (mlocal @ ((mimplies @ ((mbox @ '#cr') @ (hasanswer @ p))) @ ((mbox @ '#p') @ (hasanswer @ p))))).
thf(axiom_1_0, axiom, (mlocal @ ((mimplies @ ((mbox @ '#cr') @ (hasanswer @ p))) @ ((mbox @ '#t') @ (hasanswer @ p))))).
thf(axiom_1_1, axiom, (mlocal @ ((mimplies @ ((mbox @ '#bank') @ (hasanswer @ p))) @ ((mbox @ '#cr') @ (hasanswer @ p))))).
thf(axiom_1_2, axiom, (mlocal @ ((mimplies @ ((mbox @ '#t') @ (code @ fortytwo))) @ ((mbox @ '#it') @ (code @ fortytwo))))).
thf(axiom_1_3, axiom, (mlocal @ ((mimplies @ ((mbox @ '#cr') @ (code @ fortytwo))) @ ((mbox @ '#p') @ (code @ fortytwo))))).
thf(axiom_1_4, axiom, (mlocal @ ((mimplies @ ((mbox @ '#cr') @ (code @ fortytwo))) @ ((mbox @ '#t') @ (code @ fortytwo))))).
thf(axiom_1_5, axiom, (mlocal @ ((mimplies @ ((mbox @ '#bank') @ (code @ fortytwo))) @ ((mbox @ '#cr') @ (code @ fortytwo))))).
thf(axiom_1_6, axiom, (mlocal @ ((mimplies @ ((mbox @ '#t') @ (code @ fortytwo))) @ ((mbox @ '#it') @ (code @ fortytwo))))).
thf(axiom_1_7, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#cr') @ (identifiable @ X))) @ ((mbox @ '#p') @ (identifiable @ X)))))))).
thf(axiom_1_8, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#cr') @ (identifiable @ X))) @ ((mbox @ '#t') @ (identifiable @ X)))))))).
thf(axiom_1_9, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#bank') @ (identifiable @ X))) @ ((mbox @ '#cr') @ (identifiable @ X)))))))).
thf(axiom_1_10, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#t') @ (identifiable @ X))) @ ((mbox @ '#it') @ (identifiable @ X)))))))).
thf(axiom_1_11, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((number @ X) @ Y))) @ ((mbox @ '#p') @ ((number @ X) @ Y))))))))))).
thf(axiom_1_12, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((number @ X) @ Y))) @ ((mbox @ '#t') @ ((number @ X) @ Y))))))))))).
thf(axiom_1_13, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#bank') @ ((number @ X) @ Y))) @ ((mbox @ '#cr') @ ((number @ X) @ Y))))))))))).
thf(axiom_1_14, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#t') @ ((number @ X) @ Y))) @ ((mbox @ '#it') @ ((number @ X) @ Y))))))))))).
thf(axiom_1_15, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#cr') @ (account @ X))) @ ((mbox @ '#p') @ (account @ X)))))))).
thf(axiom_1_16, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#cr') @ (account @ X))) @ ((mbox @ '#t') @ (account @ X)))))))).
thf(axiom_1_17, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#bank') @ (account @ X))) @ ((mbox @ '#cr') @ (account @ X)))))))).
thf(axiom_1_18, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mbox @ '#t') @ (account @ X))) @ ((mbox @ '#it') @ (account @ X)))))))).
thf(axiom_1_19, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((balance @ X) @ Y))) @ ((mbox @ '#p') @ ((balance @ X) @ Y))))))))))).
thf(axiom_1_20, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((balance @ X) @ Y))) @ ((mbox @ '#t') @ ((balance @ X) @ Y))))))))))).
thf(axiom_1_21, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#bank') @ ((balance @ X) @ Y))) @ ((mbox @ '#cr') @ ((balance @ X) @ Y))))))))))).
thf(axiom_1_22, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#t') @ ((balance @ X) @ Y))) @ ((mbox @ '#it') @ ((balance @ X) @ Y))))))))))).
thf(axiom_1_23, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((value @ X) @ Y))) @ ((mbox @ '#p') @ ((value @ X) @ Y))))))))))).
thf(axiom_1_24, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#cr') @ ((value @ X) @ Y))) @ ((mbox @ '#t') @ ((value @ X) @ Y))))))))))).
thf(axiom_1_25, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#bank') @ ((value @ X) @ Y))) @ ((mbox @ '#cr') @ ((value @ X) @ Y))))))))))).
thf(axiom_1_26, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((mbox @ '#t') @ ((value @ X) @ Y))) @ ((mbox @ '#it') @ ((value @ X) @ Y))))))))))).
thf(con, conjecture, (mlocal @ (mexists_di @ (^ [U:$i]: (((mbox @ '#p') @ ((mimplies @ ((uttered @ p) @ U)) @ (mexists_di @ (^ [U1:$i]: (((mbox @ '#p') @ ((mimplies @ ((uttered @ p) @ U1)) @ ((mbox @ '#cr') @ (mexists_di @ (^ [U2:$i]: (((mimplies @ ((mbox @ '#t') @ ((uttered @ t) @ U2))) @ ((mbox @ '#cr') @ (hasanswer @ p))))))))))))))))))).
