%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : TBA
% Source   : [TPTP]
% Names    :

% Status   : Theorem
% Rating   : ? b8.1.0
% Syntax   : Number of formulae    :   29 (  14 unt;  14 typ;  14 def)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S5U].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_universal,axiom,
    ! [W: mworld,V: mworld] : ( mrel @ W @ V ) ).

%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:31 CEST 2022 using command 'downgrade(tff)'.
thf(v10_decl,type,
    v10: mworld > $o ).

thf(v12_decl,type,
    v12: mworld > $o ).

thf(v11_decl,type,
    v11: mworld > $o ).

thf(v14_decl,type,
    v14: mworld > $o ).

thf(v13_decl,type,
    v13: mworld > $o ).

thf(v16_decl,type,
    v16: mworld > $o ).

thf(v15_decl,type,
    v15: mworld > $o ).

thf(v18_decl,type,
    v18: mworld > $o ).

thf(v17_decl,type,
    v17: mworld > $o ).

thf(v19_decl,type,
    v19: mworld > $o ).

thf(v20_decl,type,
    v20: mworld > $o ).

thf(v1_decl,type,
    v1: mworld > $o ).

thf(v2_decl,type,
    v2: mworld > $o ).

thf(v3_decl,type,
    v3: mworld > $o ).

thf(v4_decl,type,
    v4: mworld > $o ).

thf(v5_decl,type,
    v5: mworld > $o ).

thf(v6_decl,type,
    v6: mworld > $o ).

thf(v7_decl,type,
    v7: mworld > $o ).

thf(v8_decl,type,
    v8: mworld > $o ).

thf(v9_decl,type,
    v9: mworld > $o ).

thf(mod1,axiom,
    mlocal @ ( mbox @ ( mor @ v20 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v16 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v5 @ ( mbox @ ( mbox @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod2,axiom,
    mlocal @ ( mbox @ ( mor @ v20 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v15 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v8 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod3,axiom,
    mlocal @ ( mbox @ ( mor @ v20 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v15 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v6 @ ( mbox @ ( mbox @ ( mbox @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod4,axiom,
    mlocal @ ( mbox @ ( mor @ v20 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v11 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v7 @ ( mbox @ ( mbox @ v5 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod5,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v20 ) @ ( mbox @ ( mor @ ( mnot @ v19 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v15 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod6,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v20 ) @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v18 ) @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v15 @ ( mbox @ ( mbox @ ( mnot @ v13 ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod7,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v20 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v14 @ ( mbox @ ( mor @ v13 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod8,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v20 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v14 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v5 @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod9,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ v19 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v10 ) @ ( mbox @ ( mbox @ ( mor @ v8 @ ( mbox @ ( mbox @ v6 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod10,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v18 ) @ ( mbox @ ( mor @ ( mnot @ v17 ) @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v15 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod11,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v17 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v9 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v5 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod12,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v17 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v9 ) @ ( mbox @ ( mor @ ( mnot @ v8 ) @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod13,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v16 ) @ ( mbox @ ( mbox @ ( mor @ v14 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v10 @ ( mbox @ ( mnot @ v9 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod14,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v16 ) @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v2 ) @ ( mbox @ v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod15,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v15 ) @ ( mbox @ ( mor @ v14 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v4 @ ( mbox @ ( mbox @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod16,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v11 @ ( mbox @ ( mor @ v10 @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod17,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v13 @ ( mbox @ ( mbox @ ( mor @ v11 @ ( mbox @ ( mor @ v10 @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod18,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v12 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v6 ) @ ( mbox @ ( mor @ ( mnot @ v5 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod19,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v10 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v6 @ ( mbox @ ( mor @ v5 @ ( mbox @ ( mbox @ ( mbox @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod20,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v7 @ ( mbox @ ( mor @ v6 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v2 @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(alt1,axiom,
    ( mlocal
    @ ( mand
      @ ( mbox
        @ ( mand
          @ ( mbox
            @ ( mand
              @ ( mbox
                @ ( mand
                  @ ( mbox
                    @ ( mand
                      @ ( mbox
                        @ ( mand
                          @ ( mbox
                            @ ( mand
                              @ ( mbox
                                @ ( mand
                                  @ ( mbox
                                    @ ( mand
                                      @ ( mbox
                                        @ ( mand
                                          @ ( mbox
                                            @ ( mand
                                              @ ( mbox
                                                @ ( mand
                                                  @ ( mbox
                                                    @ ( mand
                                                      @ ( mbox
                                                        @ ( mand
                                                          @ ( mbox
                                                            @ ( mand
                                                              @ ( mbox
                                                                @ ( mand
                                                                  @ ( mbox
                                                                    @ ( mand
                                                                      @ ( mbox
                                                                        @ ( mand
                                                                          @ ( mbox
                                                                            @ ( mand
                                                                              @ ( mbox
                                                                                @ ( mdia
                                                                                  @ ^ [W: mworld] : $true ) )
                                                                              @ ( mdia
                                                                                @ ^ [W: mworld] : $true ) ) )
                                                                          @ ( mdia
                                                                            @ ^ [W: mworld] : $true ) ) )
                                                                      @ ( mdia
                                                                        @ ^ [W: mworld] : $true ) ) )
                                                                  @ ( mand @ ( mdia @ v5 ) @ ( mdia @ ( mnot @ v5 ) ) ) ) )
                                                              @ ( mand @ ( mdia @ v6 ) @ ( mdia @ ( mnot @ v6 ) ) ) ) )
                                                          @ ( mand @ ( mdia @ v7 ) @ ( mdia @ ( mnot @ v7 ) ) ) ) )
                                                      @ ( mand @ ( mdia @ v8 ) @ ( mdia @ ( mnot @ v8 ) ) ) ) )
                                                  @ ( mdia
                                                    @ ^ [W: mworld] : $true ) ) )
                                              @ ( mdia
                                                @ ^ [W: mworld] : $true ) ) )
                                          @ ( mdia
                                            @ ^ [W: mworld] : $true ) ) )
                                      @ ( mdia
                                        @ ^ [W: mworld] : $true ) ) )
                                  @ ( mand @ ( mdia @ v13 ) @ ( mdia @ ( mnot @ v13 ) ) ) ) )
                              @ ( mand @ ( mdia @ v14 ) @ ( mdia @ ( mnot @ v14 ) ) ) ) )
                          @ ( mand @ ( mdia @ v15 ) @ ( mdia @ ( mnot @ v15 ) ) ) ) )
                      @ ( mand @ ( mdia @ v16 ) @ ( mdia @ ( mnot @ v16 ) ) ) ) )
                  @ ( mdia
                    @ ^ [W: mworld] : $true ) ) )
              @ ( mdia
                @ ^ [W: mworld] : $true ) ) )
          @ ( mdia
            @ ^ [W: mworld] : $true ) ) )
      @ ( mdia
        @ ^ [W: mworld] : $true ) ) ) ).

thf(result1,conjecture,
    ( mlocal
    @ ^ [W: mworld] : $false ) ).

%------------------------------------------------------------------------------
