%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : SYM316+1 [QMLTP]

% Status   : Unknown 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   70 (   9 unt;  19 typ;   8 def)
%            Number of atoms       :  504 (   8 equ;   0 cnn)
%            Maximal formula atoms :   14 (   9 avg)
%            Number of connectives :  468 (   1   ~;   1   |;   2   &; 461   @)
%                                         (   1 <=>;   2  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    8 (   6 avg)
%            Number of types       :    2 (   1 usr)
%            Number of type conns  :   53 (  53   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   21 (  18 usr;   3 con; 0-3 aty)
%            Number of variables   :   25 (  21   ^   2   !;   2   ?;  25   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_D].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_serial,axiom,
    ! [W: mworld] :
    ? [V: mworld] : ( mrel @ W @ V ) ).

thf(v1_decl,type,
    v1: mworld > $o ).

thf(v2_decl,type,
    v2: mworld > $o ).

thf(v3_decl,type,
    v3: mworld > $o ).

thf(v4_decl,type,
    v4: mworld > $o ).

thf(v5_decl,type,
    v5: mworld > $o ).

thf(v6_decl,type,
    v6: mworld > $o ).

thf(v7_decl,type,
    v7: mworld > $o ).

thf(v8_decl,type,
    v8: mworld > $o ).

thf(persat1,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v3 ) @ ( mbox @ ( mnot @ v5 ) ) ) ) ) ).

thf(persat2,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat3,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v5 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat4,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ v4 @ ( mor @ v7 @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat5,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ v5 @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat6,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v4 ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat7,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ ( mnot @ v3 ) ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat8,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mnot @ v6 ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat9,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mbox @ v2 ) @ ( mor @ ( mbox @ v6 ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat10,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ v8 @ ( mor @ ( mnot @ v4 ) @ ( mbox @ v3 ) ) ) ) ).

thf(persat11,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mnot @ v6 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ).

thf(persat12,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mbox @ v3 ) @ ( mor @ ( mbox @ v6 ) @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ).

thf(persat13,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mbox @ v3 ) @ ( mor @ ( mbox @ ( mnot @ v6 ) ) @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat14,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ v5 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat15,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ ( mnot @ v4 ) ) @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat16,axiom,
    mlocal @ ( mor @ v5 @ ( mor @ ( mnot @ v8 ) @ ( mor @ ( mbox @ v7 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat17,axiom,
    mlocal @ ( mor @ v6 @ ( mor @ v7 @ ( mor @ ( mnot @ v8 ) @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat18,axiom,
    mlocal @ ( mor @ v6 @ ( mor @ v7 @ ( mor @ ( mbox @ v7 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat19,axiom,
    mlocal @ ( mor @ v6 @ ( mor @ v8 @ ( mor @ ( mnot @ v7 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat20,axiom,
    mlocal @ ( mor @ v6 @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ ( mnot @ v5 ) ) @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ).

thf(persat21,axiom,
    mlocal @ ( mor @ v6 @ ( mor @ ( mnot @ v7 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ v6 ) ) ) ) ).

thf(persat22,axiom,
    mlocal @ ( mor @ v7 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v2 ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat23,axiom,
    mlocal @ ( mor @ v7 @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat24,axiom,
    mlocal @ ( mor @ v7 @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ ( mnot @ v7 ) ) @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat25,axiom,
    mlocal @ ( mor @ v7 @ ( mor @ ( mbox @ v1 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ).

thf(persat26,axiom,
    mlocal @ ( mor @ v8 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ).

thf(persat27,axiom,
    mlocal @ ( mor @ v8 @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ v5 ) @ ( mbox @ v7 ) ) ) ) ).

thf(persat28,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mnot @ v5 ) @ ( mbox @ v3 ) ) ) ) ).

thf(persat29,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v1 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(persat30,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v3 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ v7 ) ) ) ) ).

thf(persat31,axiom,
    mlocal @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ v7 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat32,axiom,
    mlocal @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mnot @ v7 ) @ ( mor @ ( mbox @ v6 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat33,axiom,
    mlocal @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v2 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ v6 ) ) ) ) ).

thf(persat34,axiom,
    mlocal @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v6 ) @ ( mor @ ( mbox @ v7 ) @ ( mbox @ v8 ) ) ) ) ).

thf(persat35,axiom,
    mlocal @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mnot @ v6 ) @ ( mor @ ( mbox @ ( mnot @ v3 ) ) @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ).

thf(persat36,axiom,
    mlocal @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mnot @ v7 ) @ ( mor @ ( mnot @ v8 ) @ ( mbox @ v2 ) ) ) ) ).

thf(persat37,axiom,
    mlocal @ ( mor @ ( mnot @ v5 ) @ ( mor @ ( mbox @ v2 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ ( mnot @ v5 ) ) ) ) ) ).

thf(persat38,axiom,
    mlocal @ ( mor @ ( mnot @ v6 ) @ ( mor @ ( mnot @ v7 ) @ ( mor @ ( mnot @ v8 ) @ ( mbox @ v2 ) ) ) ) ).

thf(persat39,axiom,
    mlocal @ ( mor @ ( mnot @ v6 ) @ ( mor @ ( mnot @ v7 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ v5 ) ) ) ) ).

thf(persat40,axiom,
    mlocal @ ( mor @ ( mnot @ v6 ) @ ( mor @ ( mnot @ v8 ) @ ( mor @ ( mbox @ v7 ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(deontic1,axiom,
    ( mlocal
    @ ( mdia
      @ ^ [W: mworld] : $true ) ) ).

thf(result1,conjecture,
    ( mlocal
    @ ^ [W: mworld] : $false ) ).

%------------------------------------------------------------------------------
