%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : TBA
% Source   : [TPTP]
% Names    :

% Status   : Theorem
% Rating   : ? b8.1.0
% Syntax   : Number of formulae    :   29 (  14 unt;  14 typ;  14 def)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S5].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(mrel_euclidean,axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ W @ U )
        & ( mrel @ W @ V ) )
     => ( mrel @ U @ V ) ) ).

thf(v1_decl,type,
    v1: mworld > $o ).

thf(v2_decl,type,
    v2: mworld > $o ).

thf(v3_decl,type,
    v3: mworld > $o ).

thf(v4_decl,type,
    v4: mworld > $o ).

thf(persat1,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ v2 @ ( mor @ ( mnot @ v3 ) @ ( mbox @ v3 ) ) ) ) ).

thf(persat2,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v2 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat3,axiom,
    mlocal @ ( mor @ v1 @ ( mor @ ( mbox @ v2 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ).

thf(persat4,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ v3 @ ( mor @ ( mbox @ ( mnot @ v3 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat5,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v3 ) @ ( mbox @ v4 ) ) ) ) ).

thf(persat6,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat7,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat8,axiom,
    mlocal @ ( mor @ v2 @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat9,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ v4 @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat10,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ).

thf(persat11,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat12,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat13,axiom,
    mlocal @ ( mor @ v3 @ ( mor @ ( mbox @ v1 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(persat14,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat15,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat16,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v4 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat17,axiom,
    mlocal @ ( mor @ v4 @ ( mor @ ( mbox @ v3 ) @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat18,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v3 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat19,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ).

thf(persat20,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat21,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mbox @ v2 ) @ ( mbox @ v3 ) ) ) ) ).

thf(persat22,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v1 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ).

thf(persat23,axiom,
    mlocal @ ( mor @ ( mnot @ v1 ) @ ( mor @ ( mbox @ v4 ) @ ( mor @ ( mbox @ ( mnot @ v3 ) ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat24,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ).

thf(persat25,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(persat26,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ).

thf(persat27,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mbox @ v1 ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(persat28,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v3 ) @ ( mor @ ( mbox @ ( mnot @ v2 ) ) @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ).

thf(persat29,axiom,
    mlocal @ ( mor @ ( mnot @ v2 ) @ ( mor @ ( mbox @ v4 ) @ ( mor @ ( mbox @ ( mnot @ v1 ) ) @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ).

thf(persat30,axiom,
    mlocal @ ( mor @ ( mnot @ v3 ) @ ( mor @ ( mnot @ v4 ) @ ( mor @ ( mbox @ v3 ) @ ( mbox @ v4 ) ) ) ) ).

thf(deontic1,axiom,
    ( mlocal
    @ ( mdia
      @ ^ [W: mworld] : $true ) ) ).

thf(result1,conjecture,
    ( mlocal
    @ ^ [W: mworld] : $false ) ).

%------------------------------------------------------------------------------
