tff(s4_cumulative_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $cumulative,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:37:53 CEST 2022 using command 'downgrade(tff)'.
tff(member_decl, type, member: (($i * $i) > $o)).
tff(subset_decl, type, subset: (($i * $i) > $o)).
tff(subset_defn, axiom-local, (! [B:$i,C:$i]: ((subset(B,C) <=> (! [D:$i]: ((member(D,B) => member(D,C)))))))).
tff(reflexivity_of_subset, axiom-local, (! [B:$i]: (subset(B,B)))).
tff(prove_transitivity_of_subset, conjecture, (! [B:$i,C:$i,D:$i]: (((subset(B,C) & subset(C,D)) => subset(B,D))))).
