tff(s5_cumulative_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $cumulative,
     $modalities == $modal_system_S5
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:17 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_decl, type, qmltpeq: (($i * $i) > $o)).
tff(in_decl, type, in: (($i * $i) > $o)).
tff(disjoint_decl, type, disjoint: (($i * $i) > $o)).
tff(empty_decl, type, empty: ($i > $o)).
tff(set_intersection2_decl, type, set_intersection2: (($i * $i) > $i)).
tff(unordered_pair_decl, type, unordered_pair: (($i * $i) > $i)).
tff(reflexivity, axiom-local, (! [X:$i]: (qmltpeq(X,X)))).
tff(symmetry, axiom-local, (! [X:$i,Y:$i]: ((qmltpeq(X,Y) => qmltpeq(Y,X))))).
tff(transitivity, axiom-local, (! [X:$i,Y:$i,Z:$i]: (((qmltpeq(X,Y) & qmltpeq(Y,Z)) => qmltpeq(X,Z))))).
tff(set_intersection2_substitution_1, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_intersection2(A,C),set_intersection2(B,C)))))).
tff(set_intersection2_substitution_2, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_intersection2(C,A),set_intersection2(C,B)))))).
tff(unordered_pair_substitution_1, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(unordered_pair(A,C),unordered_pair(B,C)))))).
tff(unordered_pair_substitution_2, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(unordered_pair(C,A),unordered_pair(C,B)))))).
tff(disjoint_substitution_1, axiom-local, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & disjoint(A,C)) => disjoint(B,C))))).
tff(disjoint_substitution_2, axiom-local, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & disjoint(C,A)) => disjoint(C,B))))).
tff(empty_substitution_1, axiom-local, (! [A:$i,B:$i]: (((qmltpeq(A,B) & empty(A)) => empty(B))))).
tff(in_substitution_1, axiom-local, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(A,C)) => in(B,C))))).
tff(in_substitution_2, axiom-local, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(C,A)) => in(C,B))))).
tff(antisymmetry_r2_hidden, axiom-local, (! [A:$i,B:$i]: ((in(A,B) => ~ (in(B,A)))))).
tff(commutativity_k2_tarski, axiom-local, (! [A:$i,B:$i]: (qmltpeq(unordered_pair(A,B),unordered_pair(B,A))))).
tff(commutativity_k3_xboole_0, axiom-local, (! [A:$i,B:$i]: (qmltpeq(set_intersection2(A,B),set_intersection2(B,A))))).
tff(d2_tarski, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(C,unordered_pair(A,B)) <=> (! [D:$i]: ((in(D,C) <=> (qmltpeq(D,A) | qmltpeq(D,B))))))))).
tff(d3_xboole_0, axiom-local, (! [A:$i,B:$i,C:$i]: ((qmltpeq(C,set_intersection2(A,B)) <=> (! [D:$i]: ((in(D,C) <=> (in(D,A) & in(D,B))))))))).
tff(idempotence_k3_xboole_0, axiom-local, (! [A:$i,B:$i]: (qmltpeq(set_intersection2(A,A),A)))).
tff(rc1_xboole_0, axiom-local, (? [A:$i]: (empty(A)))).
tff(rc2_xboole_0, axiom-local, (? [A:$i]: (~ (empty(A))))).
tff(symmetry_r1_xboole_0, axiom-local, (! [A:$i,B:$i]: ((disjoint(A,B) => disjoint(B,A))))).
tff(t4_xboole_0, axiom-local, (! [A:$i,B:$i]: ((~ ((~ (disjoint(A,B)) & (! [C:$i]: (~ (in(C,set_intersection2(A,B))))))) & ~ (((? [C:$i]: (in(C,set_intersection2(A,B)))) & disjoint(A,B))))))).
tff(t57_zfmisc_1, conjecture, (! [A:$i,B:$i,C:$i]: (~ ((~ (in(A,B)) & (~ (in(C,B)) & ~ (disjoint(unordered_pair(A,C),B)))))))).
