tff(s4_constant_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $constant,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:16 CEST 2022 using command 'downgrade(tff)'.
tff(in_decl, type, in: (($i * $i) > $o)).
tff(disjoint_decl, type, disjoint: (($i * $i) > $o)).
tff(empty_decl, type, empty: ($i > $o)).
tff(singleton_decl, type, singleton: ($i > $i)).
tff(symmetry_r1_xboole_0, axiom-local, (! [A:$i,B:$i]: ((disjoint(A,B) => disjoint(B,A))))).
tff(antisymmetry_r2_hidden, axiom-local, (! [A:$i,B:$i]: ((in(A,B) => ~ (in(B,A)))))).
tff(rc1_xboole_0, axiom-local, (? [A:$i]: (empty(A)))).
tff(rc2_xboole_0, axiom-local, (? [A:$i]: (~ (empty(A))))).
tff(t56_zfmisc_1, conjecture, (! [A:$i,B:$i]: ((~ (in(A,B)) => disjoint(singleton(A),B))))).
tff(l28_zfmisc_1, axiom-local, (! [A:$i,B:$i]: ((~ (in(A,B)) => disjoint(singleton(A),B))))).
