%%% This output was generated by embedproblem, version 1.7.1 (library version 1.3).
%%% Generated on Thu Apr 28 16:01:11 EDT 2022
%%% using 'modal' embedding, version 1.5.2.
%%% Logic specification used:
%%% tff(s5_constant_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($constant),($modalities) == ($modal_system_S5)])).

thf(mworld, type, mworld: $tType).
thf(mindex, type, mindex: $tType).
thf(mrel_type, type, mrel: (mindex > (mworld > (mworld > $o)))).
thf('#coffee_type', type, '#coffee': mindex).
thf('#ticket_type', type, '#ticket': mindex).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: (mindex > ((mworld > $o) > (mworld > $o)))).
thf(mbox_def, definition, (mbox = (^ [R:mindex,Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: (((((mrel @ R) @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: (mindex > ((mworld > $o) > (mworld > $o)))).
thf(mdia_def, definition, (mdia = (^ [R:mindex,Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: (((((mrel @ R) @ W) @ V) & (Phi @ V)))))))).
thf('mrel_#coffee_reflexive', axiom, (! [W:mworld]: ((((mrel @ '#coffee') @ W) @ W)))).
thf('mrel_#coffee_euclidean', axiom, (! [W:mworld,V:mworld,U:mworld]: ((((((mrel @ '#coffee') @ W) @ U) & (((mrel @ '#coffee') @ W) @ V)) => (((mrel @ '#coffee') @ U) @ V))))).
thf('mrel_#ticket_reflexive', axiom, (! [W:mworld]: ((((mrel @ '#ticket') @ W) @ W)))).
thf('mrel_#ticket_euclidean', axiom, (! [W:mworld,V:mworld,U:mworld]: ((((((mrel @ '#ticket') @ W) @ U) & (((mrel @ '#ticket') @ W) @ V)) => (((mrel @ '#ticket') @ U) @ V))))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: (((A @ X) @ W))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: (((A @ X) @ W))))))).
thf(passenger_decl, type, passenger: $i).
thf(takejourney_decl, type, takejourney: ($i > (mworld > $o))).
thf(usemachine_decl, type, usemachine: ($i > (mworld > $o))).
thf(visitdonuts_decl, type, visitdonuts: ($i > (mworld > $o))).
thf(usewindow_decl, type, usewindow: ($i > (mworld > $o))).
thf(getticket_decl, type, getticket: ($i > (mworld > $o))).
thf(visitstarbucks_decl, type, visitstarbucks: ($i > (mworld > $o))).
thf(getcoffee_decl, type, getcoffee: ($i > (mworld > $o))).
thf(visitstarbuck_decl, type, visitstarbuck: ($i > (mworld > $o))).
thf(axiom_1, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#ticket') @ ((mor @ (usemachine @ X)) @ (usewindow @ X)))))))).
thf(axiom_2, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#ticket') @ ((mimplies @ (usemachine @ X)) @ (getticket @ X)))))))).
thf(axiom_3, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#ticket') @ ((mimplies @ (usewindow @ X)) @ (getticket @ X)))))))).
thf(axiom_4, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#coffee') @ ((mor @ (visitdonuts @ X)) @ (visitstarbucks @ X)))))))).
thf(axiom_5, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#coffee') @ ((mimplies @ (visitdonuts @ X)) @ (getcoffee @ X)))))))).
thf(axiom_6, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mbox @ '#coffee') @ ((mimplies @ (visitstarbuck @ X)) @ (getcoffee @ X)))))))).
thf(axiom_7, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((mand @ ((mbox @ '#ticket') @ (getticket @ X))) @ ((mbox @ '#coffee') @ (getcoffee @ X)))) @ (takejourney @ X))))))).
thf(con, conjecture, (mlocal @ (takejourney @ passenger))).
