%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : [Bal98] Baldoni (1998), Normal Multimodal Logics: Automatic De
%          : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : MML005+1 [QMLTP]

% Status   : Unknown 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   47 (  12 unt;  20 typ;   8 def)
%            Number of atoms       :  114 (   8 equ;   0 cnn)
%            Maximal formula atoms :    9 (   4 avg)
%            Number of connectives :  202 (   1   ~;   1   |;   6   &; 187   @)
%                                         (   1 <=>;   6  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    9 (   5 avg)
%            Number of types       :    4 (   2 usr)
%            Number of type conns  :   52 (  52   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   19 (  18 usr;   7 con; 0-3 aty)
%            Number of variables   :   39 (  21   ^  17   !;   1   ?;  39   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S4].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mindex,type,
    mindex: $tType ).

thf(mrel_type,type,
    mrel: mindex > mworld > mworld > $o ).

thf('#sing_type',type,
    '#sing': mindex ).

thf('#always_type',type,
    '#always': mindex ).

thf('#fox_type',type,
    '#fox': mindex ).

thf('#praise_type',type,
    '#praise': mindex ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: mindex > ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ R @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: mindex > ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ R @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf('mrel_#sing_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#sing' @ W @ W ) ).

thf('mrel_#sing_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#sing' @ W @ V )
        & ( mrel @ '#sing' @ V @ U ) )
     => ( mrel @ '#sing' @ W @ U ) ) ).

thf('mrel_#always_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#always' @ W @ W ) ).

thf('mrel_#always_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#always' @ W @ V )
        & ( mrel @ '#always' @ V @ U ) )
     => ( mrel @ '#always' @ W @ U ) ) ).

thf('mrel_#fox_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#fox' @ W @ W ) ).

thf('mrel_#fox_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#fox' @ W @ V )
        & ( mrel @ '#fox' @ V @ U ) )
     => ( mrel @ '#fox' @ W @ U ) ) ).

thf('mrel_#praise_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#praise' @ W @ W ) ).

thf('mrel_#praise_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#praise' @ W @ V )
        & ( mrel @ '#praise' @ V @ U ) )
     => ( mrel @ '#praise' @ W @ U ) ) ).

thf(raven_decl,type,
    raven: $i ).

thf(cheese_decl,type,
    cheese: $i ).

thf(dropped_decl,type,
    dropped: $i > mworld > $o ).

thf(charmed_decl,type,
    charmed: $i > mworld > $o ).

thf(i_always_praise_1_1,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( dropped @ cheese ) ) @ ( mbox @ '#praise' @ ( mbox @ '#always' @ ( dropped @ cheese ) ) ) ) ).

thf(i_always_praise_2_2,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( mnot @ ( dropped @ cheese ) ) ) @ ( mbox @ '#praise' @ ( mbox @ '#always' @ ( mnot @ ( dropped @ cheese ) ) ) ) ) ).

thf(i_always_praise_1_3,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( charmed @ raven ) ) @ ( mbox @ '#praise' @ ( mbox @ '#always' @ ( charmed @ raven ) ) ) ) ).

thf(i_always_praise_2_4,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( mnot @ ( charmed @ cheese ) ) ) @ ( mbox @ '#praise' @ ( mbox @ '#always' @ ( mnot @ ( charmed @ raven ) ) ) ) ) ).

thf(i_always_praise_1_5,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( dropped @ cheese ) ) @ ( mbox @ '#sing' @ ( mbox @ '#always' @ ( dropped @ cheese ) ) ) ) ).

thf(i_always_praise_2_6,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( mnot @ ( dropped @ cheese ) ) ) @ ( mbox @ '#sing' @ ( mbox @ '#always' @ ( mnot @ ( dropped @ cheese ) ) ) ) ) ).

thf(i_always_praise_1_7,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( charmed @ raven ) ) @ ( mbox @ '#sing' @ ( mbox @ '#always' @ ( charmed @ raven ) ) ) ) ).

thf(i_always_praise_2_8,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#always' @ ( mnot @ ( charmed @ cheese ) ) ) @ ( mbox @ '#sing' @ ( mbox @ '#always' @ ( mnot @ ( charmed @ raven ) ) ) ) ) ).

thf(axiom_1,axiom,
    mlocal @ ( mbox @ '#fox' @ ( mbox @ '#praise' @ ( charmed @ raven ) ) ) ).

thf(axiom_2,axiom,
    mlocal @ ( mbox @ '#fox' @ ( mbox @ '#always' @ ( mimplies @ ( charmed @ raven ) @ ( mbox @ '#sing' @ ( dropped @ cheese ) ) ) ) ) ).

thf(conj,conjecture,
    mlocal @ ( mbox @ '#fox' @ ( mbox @ '#praise' @ ( mbox @ '#sing' @ ( dropped @ cheese ) ) ) ) ).

%------------------------------------------------------------------------------
