%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : [vDK06] van Ditmarsch & Kooi (2006), The Secret of My Success
%          : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : MML007+1 [QMLTP]

% Status   : Unknown 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   48 (  11 unt;  25 typ;   8 def)
%            Number of atoms       :  117 (   8 equ;   0 cnn)
%            Maximal formula atoms :   11 (   5 avg)
%            Number of connectives :  184 (   1   ~;   1   |;   5   &; 171   @)
%                                         (   1 <=>;   5  =>;   0  <=;   0 <~>)
%            Maximal formula depth :    9 (   5 avg)
%            Number of types       :    3 (   2 usr)
%            Number of type conns  :   58 (  58   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   24 (  23 usr;   4 con; 0-3 aty)
%            Number of variables   :   35 (  21   ^  13   !;   1   ?;  35   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S5].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mindex,type,
    mindex: $tType ).

thf(mrel_type,type,
    mrel: mindex > mworld > mworld > $o ).

thf('#c_type',type,
    '#c': mindex ).

thf('#b_type',type,
    '#b': mindex ).

thf('#a_type',type,
    '#a': mindex ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: mindex > ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ R @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: mindex > ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ R @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf('mrel_#c_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#c' @ W @ W ) ).

thf('mrel_#c_euclidean',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#c' @ W @ U )
        & ( mrel @ '#c' @ W @ V ) )
     => ( mrel @ '#c' @ U @ V ) ) ).

thf('mrel_#b_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#b' @ W @ W ) ).

thf('mrel_#b_euclidean',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#b' @ W @ U )
        & ( mrel @ '#b' @ W @ V ) )
     => ( mrel @ '#b' @ U @ V ) ) ).

thf('mrel_#a_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#a' @ W @ W ) ).

thf('mrel_#a_euclidean',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#a' @ W @ U )
        & ( mrel @ '#a' @ W @ V ) )
     => ( mrel @ '#a' @ U @ V ) ) ).

thf(c0_decl,type,
    c0: mworld > $o ).

thf(c1_decl,type,
    c1: mworld > $o ).

thf(b0_decl,type,
    b0: mworld > $o ).

thf(c2_decl,type,
    c2: mworld > $o ).

thf(b1_decl,type,
    b1: mworld > $o ).

thf(a0_decl,type,
    a0: mworld > $o ).

thf(b2_decl,type,
    b2: mworld > $o ).

thf(a1_decl,type,
    a1: mworld > $o ).

thf(a2_decl,type,
    a2: mworld > $o ).

thf(cb_decl,type,
    cb: mworld > $o ).

thf(axiom_knows_a_b_c,axiom,
    mlocal @ ( mbox @ '#a' @ ( mbox @ '#b' @ ( mor @ ( mbox @ '#c' @ c0 ) @ ( mor @ ( mbox @ '#c' @ c1 ) @ ( mbox @ '#c' @ c2 ) ) ) ) ) ).

thf(axiom_knows_b_a_c,axiom,
    mlocal @ ( mbox @ '#b' @ ( mbox @ '#a' @ ( mor @ ( mbox @ '#c' @ c0 ) @ ( mor @ ( mbox @ '#c' @ c1 ) @ ( mbox @ '#c' @ c2 ) ) ) ) ) ).

thf(axiom_knows_a_b_c_0,axiom,
    mlocal @ ( mbox @ '#a' @ ( mbox @ '#b' @ ( mor @ ( mbox @ '#c' @ c0 ) @ ( mor @ ( mbox @ '#c' @ c1 ) @ ( mbox @ '#c' @ c2 ) ) ) ) ) ).

thf(axiom_knows_a_c_b,axiom,
    mlocal @ ( mbox @ '#a' @ ( mbox @ '#c' @ ( mor @ ( mbox @ '#b' @ b0 ) @ ( mor @ ( mbox @ '#b' @ b1 ) @ ( mbox @ '#b' @ b2 ) ) ) ) ) ).

thf(axiom_knows_c_a_b,axiom,
    mlocal @ ( mbox @ '#c' @ ( mbox @ '#a' @ ( mor @ ( mbox @ '#b' @ cb ) @ ( mor @ ( mbox @ '#b' @ b1 ) @ ( mbox @ '#b' @ b2 ) ) ) ) ) ).

thf(axiom_knows_c_b_a,axiom,
    mlocal @ ( mbox @ '#c' @ ( mbox @ '#b' @ ( mor @ ( mbox @ '#a' @ a0 ) @ ( mor @ ( mbox @ '#a' @ a1 ) @ ( mbox @ '#a' @ a2 ) ) ) ) ) ).

thf(axiom_knows_b_c_a,axiom,
    mlocal @ ( mbox @ '#b' @ ( mbox @ '#c' @ ( mor @ ( mbox @ '#a' @ a0 ) @ ( mor @ ( mbox @ '#a' @ a1 ) @ ( mbox @ '#a' @ a2 ) ) ) ) ) ).

thf(axiom_a0,axiom,
    mlocal @ a0 ).

thf(con,conjecture,
    mlocal @ ( mbox @ '#b' @ ( mnot @ ( mdia @ '#a' @ ( mdia @ '#b' @ ( mbox @ '#c' @ ( mnot @ a0 ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
