%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : MML015+1 [QMLTP]

% Status   : Theorem
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   44 (  13 unt;  20 typ;   8 def)
%            Number of atoms       :   91 (   8 equ;   0 cnn)
%            Maximal formula atoms :   16 (   3 avg)
%            Number of connectives :  175 (   1   ~;   1   |;   7   &; 158   @)
%                                         (   1 <=>;   7  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   10 (   5 avg)
%            Number of types       :    4 (   2 usr)
%            Number of type conns  :   52 (  52   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   19 (  18 usr;   7 con; 0-3 aty)
%            Number of variables   :   43 (  21   ^  21   !;   1   ?;  43   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S4].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mindex,type,
    mindex: $tType ).

thf(mrel_type,type,
    mrel: mindex > mworld > mworld > $o ).

thf('#i_alice_type',type,
    '#i_alice': mindex ).

thf('#i_bob_type',type,
    '#i_bob': mindex ).

thf('#b_alice_type',type,
    '#b_alice': mindex ).

thf('#alice_type',type,
    '#alice': mindex ).

thf('#b_bob_type',type,
    '#b_bob': mindex ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: mindex > ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ R @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: mindex > ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [R: mindex,Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ R @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf('mrel_#i_alice_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#i_alice' @ W @ W ) ).

thf('mrel_#i_alice_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#i_alice' @ W @ V )
        & ( mrel @ '#i_alice' @ V @ U ) )
     => ( mrel @ '#i_alice' @ W @ U ) ) ).

thf('mrel_#i_bob_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#i_bob' @ W @ W ) ).

thf('mrel_#i_bob_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#i_bob' @ W @ V )
        & ( mrel @ '#i_bob' @ V @ U ) )
     => ( mrel @ '#i_bob' @ W @ U ) ) ).

thf('mrel_#b_alice_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#b_alice' @ W @ W ) ).

thf('mrel_#b_alice_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#b_alice' @ W @ V )
        & ( mrel @ '#b_alice' @ V @ U ) )
     => ( mrel @ '#b_alice' @ W @ U ) ) ).

thf('mrel_#alice_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#alice' @ W @ W ) ).

thf('mrel_#alice_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#alice' @ W @ V )
        & ( mrel @ '#alice' @ V @ U ) )
     => ( mrel @ '#alice' @ W @ U ) ) ).

thf('mrel_#b_bob_reflexive',axiom,
    ! [W: mworld] : ( mrel @ '#b_bob' @ W @ W ) ).

thf('mrel_#b_bob_transitive',axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ '#b_bob' @ W @ V )
        & ( mrel @ '#b_bob' @ V @ U ) )
     => ( mrel @ '#b_bob' @ W @ U ) ) ).

thf(portland_decl,type,
    portland: $i ).

thf(bigcity_decl,type,
    bigcity: $i > mworld > $o ).

thf(beautycity_decl,type,
    beautycity: $i > mworld > $o ).

thf(axiom_1_a,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#b_alice' @ ( bigcity @ portland ) ) @ ( mnot @ ( mbox @ '#i_alice' @ ( bigcity @ portland ) ) ) ) ).

thf(axiom_1_b,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#b_bob' @ ( bigcity @ portland ) ) @ ( mnot @ ( mbox @ '#i_bob' @ ( bigcity @ portland ) ) ) ) ).

thf(axiom_1_c,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#b_alice' @ ( beautycity @ portland ) ) @ ( mnot @ ( mbox @ '#i_alice' @ ( beautycity @ portland ) ) ) ) ).

thf(axiom_1_d,axiom,
    mlocal @ ( mimplies @ ( mbox @ '#b_bob' @ ( beautycity @ portland ) ) @ ( mnot @ ( mbox @ '#i_bob' @ ( beautycity @ portland ) ) ) ) ).

thf(axiom_2,axiom,
    mlocal @ ( mbox @ '#b_alice' @ ( mor @ ( mbox @ '#b_bob' @ ( mbox @ '#b_alice' @ ( bigcity @ portland ) ) ) @ ( mbox @ '#b_bob' @ ( mbox @ '#b_alice' @ ( beautycity @ portland ) ) ) ) ) ).

thf(con,conjecture,
    mlocal @ ( mbox @ '#b_alice' @ ( mand @ ( mbox @ '#b_bob' @ ( mimplies @ ( mbox @ '#alice' @ ( bigcity @ portland ) ) @ ( mnot @ ( mbox @ '#i_alice' @ ( bigcity @ portland ) ) ) ) ) @ ( mimplies @ ( mbox @ '#alice' @ ( beautycity @ portland ) ) @ ( mnot @ ( mbox @ '#i_alice' @ ( beautycity @ portland ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
