%%% This output was generated by embedproblem, version 1.7.2 (library version 1.3).
%%% Generated on Fri May 06 13:29:15 EDT 2022
%%% using 'modal' embedding, version 1.5.3.
%%% Logic specification used:
%%% tff(s5_decreasing_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($decreasing),($modalities) == ($modal_system_S5U)])).

thf(mworld, type, mworld: $tType).
thf(mrel_type, type, mrel: (mworld > (mworld > $o))).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: ((mworld > $o) > (mworld > $o))).
thf(mbox_def, definition, (mbox = (^ [Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: ((((mrel @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: ((mworld > $o) > (mworld > $o))).
thf(mdia_def, definition, (mdia = (^ [Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: ((((mrel @ W) @ V) & (Phi @ V)))))))).
thf(mrel_universal, axiom, (! [W:mworld,V:mworld]: (((mrel @ W) @ V)))).
thf(eiw_di_type, type, eiw_di: ($i > (mworld > $o))).
thf(eiw_di_nonempty, axiom, (! [W:mworld]: ((? [X:$i]: (((eiw_di @ X) @ W)))))).
thf(eiw_di_decr, axiom, (! [W:mworld,V:mworld,X:$i]: (((((eiw_di @ X) @ W) & ((mrel @ V) @ W)) => ((eiw_di @ X) @ V))))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: ((((eiw_di @ X) @ W) => ((A @ X) @ W)))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: ((((eiw_di @ X) @ W) & ((A @ X) @ W)))))))).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:37:58 CEST 2022 using command 'downgrade(tff)'.
thf(universal_class_decl, type, universal_class: $i).
thf(identity_relation_decl, type, identity_relation: $i).
thf(successor_relation_decl, type, successor_relation: $i).
thf(element_relation_decl, type, element_relation: $i).
thf(null_class_decl, type, null_class: $i).
thf(qmltpeq_decl, type, qmltpeq: ($i > ($i > (mworld > $o)))).
thf(inductive_decl, type, inductive: ($i > (mworld > $o))).
thf(disjoint_decl, type, disjoint: ($i > ($i > (mworld > $o)))).
thf(function_decl, type, function: ($i > (mworld > $o))).
thf(member_decl, type, member: ($i > ($i > (mworld > $o)))).
thf(subclass_decl, type, subclass: ($i > ($i > (mworld > $o)))).
thf(singleton_decl, type, singleton: ($i > $i)).
thf(image_decl, type, image: ($i > ($i > $i))).
thf(inverse_decl, type, inverse: ($i > $i)).
thf(rotate_decl, type, rotate: ($i > $i)).
thf(unordered_pair_decl, type, unordered_pair: ($i > ($i > $i))).
thf(successor_decl, type, successor: ($i > $i)).
thf(apply_decl, type, apply: ($i > ($i > $i))).
thf(power_class_decl, type, power_class: ($i > $i)).
thf(range_of_decl, type, range_of: ($i > $i)).
thf(union_decl, type, union: ($i > ($i > $i))).
thf(restrict_decl, type, restrict: ($i > ($i > ($i > $i)))).
thf(second_decl, type, second: ($i > $i)).
thf(ordered_pair_decl, type, ordered_pair: ($i > ($i > $i))).
thf(domain_of_decl, type, domain_of: ($i > $i)).
thf(sum_class_decl, type, sum_class: ($i > $i)).
thf(compose_decl, type, compose: ($i > ($i > $i))).
thf(intersection_decl, type, intersection: ($i > ($i > $i))).
thf(cross_product_decl, type, cross_product: ($i > ($i > $i))).
thf(complement_decl, type, complement: ($i > $i)).
thf(flip_decl, type, flip: ($i > $i)).
thf(first_decl, type, first: ($i > $i)).
thf(reflexivity, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((qmltpeq @ X) @ X)))))).
thf(symmetry, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((qmltpeq @ X) @ Y)) @ ((qmltpeq @ Y) @ X)))))))))).
thf(transitivity, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mforall_di @ (^ [Z:$i]: (((mimplies @ ((mand @ ((qmltpeq @ X) @ Y)) @ ((qmltpeq @ Y) @ Z))) @ ((qmltpeq @ X) @ Z))))))))))))).
thf(apply_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((apply @ A) @ C)) @ ((apply @ B) @ C)))))))))))))).
thf(apply_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((apply @ C) @ A)) @ ((apply @ C) @ B)))))))))))))).
thf(complement_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (complement @ A)) @ (complement @ B))))))))))).
thf(compose_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((compose @ A) @ C)) @ ((compose @ B) @ C)))))))))))))).
thf(compose_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((compose @ C) @ A)) @ ((compose @ C) @ B)))))))))))))).
thf(cross_product_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((cross_product @ A) @ C)) @ ((cross_product @ B) @ C)))))))))))))).
thf(cross_product_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((cross_product @ C) @ A)) @ ((cross_product @ C) @ B)))))))))))))).
thf(domain_of_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (domain_of @ A)) @ (domain_of @ B))))))))))).
thf(first_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (first @ A)) @ (first @ B))))))))))).
thf(flip_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (flip @ A)) @ (flip @ B))))))))))).
thf(image_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((image @ A) @ C)) @ ((image @ B) @ C)))))))))))))).
thf(image_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((image @ C) @ A)) @ ((image @ C) @ B)))))))))))))).
thf(intersection_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((intersection @ A) @ C)) @ ((intersection @ B) @ C)))))))))))))).
thf(intersection_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((intersection @ C) @ A)) @ ((intersection @ C) @ B)))))))))))))).
thf(inverse_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (inverse @ A)) @ (inverse @ B))))))))))).
thf(ordered_pair_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((ordered_pair @ A) @ C)) @ ((ordered_pair @ B) @ C)))))))))))))).
thf(ordered_pair_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((ordered_pair @ C) @ A)) @ ((ordered_pair @ C) @ B)))))))))))))).
thf(power_class_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (power_class @ A)) @ (power_class @ B))))))))))).
thf(range_of_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (range_of @ A)) @ (range_of @ B))))))))))).
thf(restrict_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: ((mforall_di @ (^ [D:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (((restrict @ A) @ C) @ D)) @ (((restrict @ B) @ C) @ D))))))))))))))))).
thf(restrict_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: ((mforall_di @ (^ [D:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (((restrict @ C) @ A) @ D)) @ (((restrict @ C) @ B) @ D))))))))))))))))).
thf(restrict_substitution_3, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: ((mforall_di @ (^ [D:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (((restrict @ C) @ D) @ A)) @ (((restrict @ C) @ D) @ B))))))))))))))))).
thf(rotate_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (rotate @ A)) @ (rotate @ B))))))))))).
thf(second_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (second @ A)) @ (second @ B))))))))))).
thf(singleton_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (singleton @ A)) @ (singleton @ B))))))))))).
thf(successor_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (successor @ A)) @ (successor @ B))))))))))).
thf(sum_class_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (sum_class @ A)) @ (sum_class @ B))))))))))).
thf(union_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((union @ A) @ C)) @ ((union @ B) @ C)))))))))))))).
thf(union_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((union @ C) @ A)) @ ((union @ C) @ B)))))))))))))).
thf(unordered_pair_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((unordered_pair @ A) @ C)) @ ((unordered_pair @ B) @ C)))))))))))))).
thf(unordered_pair_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((unordered_pair @ C) @ A)) @ ((unordered_pair @ C) @ B)))))))))))))).
thf(disjoint_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((disjoint @ A) @ C))) @ ((disjoint @ B) @ C))))))))))))).
thf(disjoint_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((disjoint @ C) @ A))) @ ((disjoint @ C) @ B))))))))))))).
thf(function_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ (function @ A))) @ (function @ B)))))))))).
thf(inductive_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ (inductive @ A))) @ (inductive @ B)))))))))).
thf(member_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((member @ A) @ C))) @ ((member @ B) @ C))))))))))))).
thf(member_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((member @ C) @ A))) @ ((member @ C) @ B))))))))))))).
thf(subclass_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((subclass @ A) @ C))) @ ((subclass @ B) @ C))))))))))))).
thf(subclass_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((subclass @ C) @ A))) @ ((subclass @ C) @ B))))))))))))).
thf(subclass_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((subclass @ X) @ Y)) @ (mforall_di @ (^ [U:$i]: (((mimplies @ ((member @ U) @ X)) @ ((member @ U) @ Y)))))))))))))).
thf(class_elements_are_sets, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((subclass @ X) @ universal_class)))))).
thf(extensionality, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((qmltpeq @ X) @ Y)) @ ((mand @ ((subclass @ X) @ Y)) @ ((subclass @ Y) @ X))))))))))).
thf(unordered_pair_defn, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((member @ U) @ ((unordered_pair @ X) @ Y))) @ ((mand @ ((member @ U) @ universal_class)) @ ((mor @ ((qmltpeq @ U) @ X)) @ ((qmltpeq @ U) @ Y))))))))))))))).
thf(unordered_pair_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((member @ ((unordered_pair @ X) @ Y)) @ universal_class))))))))).
thf(singleton_set_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((qmltpeq @ (singleton @ X)) @ ((unordered_pair @ X) @ X))))))).
thf(ordered_pair_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((qmltpeq @ ((ordered_pair @ X) @ Y)) @ ((unordered_pair @ (singleton @ X)) @ ((unordered_pair @ X) @ (singleton @ Y)))))))))))).
thf(cross_product_defn, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [V:$i]: ((mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((member @ ((ordered_pair @ U) @ V)) @ ((cross_product @ X) @ Y))) @ ((mand @ ((member @ U) @ X)) @ ((member @ V) @ Y))))))))))))))))).
thf(cross_product_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mforall_di @ (^ [Z:$i]: (((mimplies @ ((member @ Z) @ ((cross_product @ X) @ Y))) @ ((qmltpeq @ Z) @ ((ordered_pair @ (first @ Z)) @ (second @ Z))))))))))))))).
thf(element_relation_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((member @ ((ordered_pair @ X) @ Y)) @ element_relation)) @ ((mand @ ((member @ Y) @ universal_class)) @ ((member @ X) @ Y))))))))))).
thf(element_relation_0, axiom, (mlocal @ ((subclass @ element_relation) @ ((cross_product @ universal_class) @ universal_class)))).
thf(intersection_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mforall_di @ (^ [Z:$i]: (((mequiv @ ((member @ Z) @ ((intersection @ X) @ Y))) @ ((mand @ ((member @ Z) @ X)) @ ((member @ Z) @ Y)))))))))))))).
thf(complement_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Z:$i]: (((mequiv @ ((member @ Z) @ (complement @ X))) @ ((mand @ ((member @ Z) @ universal_class)) @ (mnot @ ((member @ Z) @ X)))))))))))).
thf(restrict_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [XR:$i]: ((mforall_di @ (^ [Y:$i]: (((qmltpeq @ (((restrict @ XR) @ X) @ Y)) @ ((intersection @ XR) @ ((cross_product @ X) @ Y)))))))))))))).
thf(null_class_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mnot @ ((member @ X) @ null_class))))))).
thf(domain_of_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Z:$i]: (((mequiv @ ((member @ Z) @ (domain_of @ X))) @ ((mand @ ((member @ Z) @ universal_class)) @ (mnot @ ((qmltpeq @ (((restrict @ X) @ (singleton @ Z)) @ universal_class)) @ null_class)))))))))))).
thf(rotate_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [V:$i]: ((mforall_di @ (^ [W:$i]: (((mequiv @ ((member @ ((ordered_pair @ ((ordered_pair @ U) @ V)) @ W)) @ (rotate @ X))) @ ((mand @ ((member @ ((ordered_pair @ ((ordered_pair @ U) @ V)) @ W)) @ ((cross_product @ ((cross_product @ universal_class) @ universal_class)) @ universal_class))) @ ((member @ ((ordered_pair @ ((ordered_pair @ V) @ W)) @ U)) @ X))))))))))))))))).
thf(rotate_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((subclass @ (rotate @ X)) @ ((cross_product @ ((cross_product @ universal_class) @ universal_class)) @ universal_class))))))).
thf(flip_defn, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [V:$i]: ((mforall_di @ (^ [W:$i]: ((mforall_di @ (^ [X:$i]: (((mequiv @ ((member @ ((ordered_pair @ ((ordered_pair @ U) @ V)) @ W)) @ (flip @ X))) @ ((mand @ ((member @ ((ordered_pair @ ((ordered_pair @ U) @ V)) @ W)) @ ((cross_product @ ((cross_product @ universal_class) @ universal_class)) @ universal_class))) @ ((member @ ((ordered_pair @ ((ordered_pair @ V) @ U)) @ W)) @ X))))))))))))))))).
thf(flip_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((subclass @ (flip @ X)) @ ((cross_product @ ((cross_product @ universal_class) @ universal_class)) @ universal_class))))))).
thf(union_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mforall_di @ (^ [Z:$i]: (((mequiv @ ((member @ Z) @ ((union @ X) @ Y))) @ ((mor @ ((member @ Z) @ X)) @ ((member @ Z) @ Y)))))))))))))).
thf(successor_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((qmltpeq @ (successor @ X)) @ ((union @ X) @ (singleton @ X)))))))).
thf(successor_relation_defn1, axiom, (mlocal @ ((subclass @ successor_relation) @ ((cross_product @ universal_class) @ universal_class)))).
thf(successor_relation_defn2, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((member @ ((ordered_pair @ X) @ Y)) @ successor_relation)) @ ((mand @ ((member @ X) @ universal_class)) @ ((mand @ ((member @ Y) @ universal_class)) @ ((qmltpeq @ (successor @ X)) @ Y)))))))))))).
thf(inverse_defn, axiom, (mlocal @ (mforall_di @ (^ [Y:$i]: (((qmltpeq @ (inverse @ Y)) @ (domain_of @ (flip @ ((cross_product @ Y) @ universal_class))))))))).
thf(range_of_defn, axiom, (mlocal @ (mforall_di @ (^ [Z:$i]: (((qmltpeq @ (range_of @ Z)) @ (domain_of @ (inverse @ Z)))))))).
thf(image_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [XR:$i]: (((qmltpeq @ ((image @ XR) @ X)) @ (range_of @ (((restrict @ XR) @ X) @ universal_class))))))))))).
thf(inductive_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mequiv @ (inductive @ X)) @ ((mand @ ((member @ null_class) @ X)) @ ((subclass @ ((image @ successor_relation) @ X)) @ X)))))))).
thf(infinity, axiom, (mlocal @ (mexists_di @ (^ [X:$i]: (((mand @ ((member @ X) @ universal_class)) @ ((mand @ (inductive @ X)) @ (mforall_di @ (^ [Y:$i]: (((mimplies @ (inductive @ Y)) @ ((subclass @ X) @ Y)))))))))))).
thf(sum_class_defn, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [X:$i]: (((mequiv @ ((member @ U) @ (sum_class @ X))) @ (mexists_di @ (^ [Y:$i]: (((mand @ ((member @ U) @ Y)) @ ((member @ Y) @ X)))))))))))))).
thf(sum_class_0, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ ((member @ X) @ universal_class)) @ ((member @ (sum_class @ X)) @ universal_class))))))).
thf(power_class_defn, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [X:$i]: (((mequiv @ ((member @ U) @ (power_class @ X))) @ ((mand @ ((member @ U) @ universal_class)) @ ((subclass @ U) @ X))))))))))).
thf(power_class_0, axiom, (mlocal @ (mforall_di @ (^ [U:$i]: (((mimplies @ ((member @ U) @ universal_class)) @ ((member @ (power_class @ U)) @ universal_class))))))).
thf(compose_defn1, axiom, (mlocal @ (mforall_di @ (^ [XR:$i]: ((mforall_di @ (^ [YR:$i]: (((subclass @ ((compose @ YR) @ XR)) @ ((cross_product @ universal_class) @ universal_class)))))))))).
thf(compose_defn2, axiom, (mlocal @ (mforall_di @ (^ [XR:$i]: ((mforall_di @ (^ [YR:$i]: ((mforall_di @ (^ [U:$i]: ((mforall_di @ (^ [V:$i]: (((mequiv @ ((member @ ((ordered_pair @ U) @ V)) @ ((compose @ YR) @ XR))) @ ((mand @ ((member @ U) @ universal_class)) @ ((member @ V) @ ((image @ YR) @ ((image @ YR) @ (singleton @ U)))))))))))))))))))).
thf(function_defn, axiom, (mlocal @ (mforall_di @ (^ [XF:$i]: (((mequiv @ (function @ XF)) @ ((mand @ ((subclass @ XF) @ ((cross_product @ universal_class) @ universal_class))) @ ((subclass @ ((compose @ XF) @ (inverse @ XF))) @ identity_relation)))))))).
thf(replacement, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [XF:$i]: (((mimplies @ ((mand @ ((member @ X) @ universal_class)) @ (function @ XF))) @ ((member @ ((image @ XF) @ X)) @ universal_class)))))))))).
thf(disjoint_defn, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mequiv @ ((disjoint @ X) @ Y)) @ (mforall_di @ (^ [U:$i]: ((mnot @ ((mand @ ((member @ U) @ X)) @ ((member @ U) @ Y))))))))))))))).
thf(regularity, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((mimplies @ (mnot @ ((qmltpeq @ X) @ null_class))) @ (mexists_di @ (^ [U:$i]: (((mand @ ((member @ U) @ universal_class)) @ ((mand @ ((member @ U) @ X)) @ ((disjoint @ U) @ X)))))))))))).
thf(apply_defn, axiom, (mlocal @ (mforall_di @ (^ [XF:$i]: ((mforall_di @ (^ [Y:$i]: (((qmltpeq @ ((apply @ XF) @ Y)) @ (sum_class @ ((image @ XF) @ (singleton @ Y)))))))))))).
thf(choice, axiom, (mlocal @ (mexists_di @ (^ [XF:$i]: (((mand @ (function @ XF)) @ (mforall_di @ (^ [Y:$i]: (((mimplies @ ((member @ Y) @ universal_class)) @ ((mor @ ((qmltpeq @ Y) @ null_class)) @ ((member @ ((apply @ XF) @ Y)) @ Y)))))))))))).
thf(special_classes_lemma, conjecture, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mnot @ ((member @ Y) @ ((intersection @ (complement @ X)) @ X))))))))))).
