%%% This output was generated by embedproblem, version 1.7.1 (library version 1.3).
%%% Generated on Thu Apr 28 14:21:25 EDT 2022
%%% using 'modal' embedding, version 1.5.2.
%%% Logic specification used:
%%% tff(t_constant_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($constant),($modalities) == ($modal_system_T)])).

thf(mworld, type, mworld: $tType).
thf(mrel_type, type, mrel: (mworld > (mworld > $o))).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: ((mworld > $o) > (mworld > $o))).
thf(mbox_def, definition, (mbox = (^ [Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: ((((mrel @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: ((mworld > $o) > (mworld > $o))).
thf(mdia_def, definition, (mdia = (^ [Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: ((((mrel @ W) @ V) & (Phi @ V)))))))).
thf(mrel_reflexive, axiom, (! [W:mworld]: (((mrel @ W) @ W)))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: (((A @ X) @ W))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: (((A @ X) @ W))))))).
thf(empty_set_decl, type, empty_set: $i).
thf(qmltpeq_decl, type, qmltpeq: ($i > ($i > (mworld > $o)))).
thf(in_decl, type, in: ($i > ($i > (mworld > $o)))).
thf(empty_decl, type, empty: ($i > (mworld > $o))).
thf(singleton_decl, type, singleton: ($i > $i)).
thf(reflexivity, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [X:$i]: ((mbox @ ((qmltpeq @ X) @ X)))))))).
thf(symmetry, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [X:$i]: ((mbox @ (mforall_di @ (^ [Y:$i]: ((mbox @ ((mimplies @ (mbox @ ((qmltpeq @ X) @ Y))) @ (mbox @ ((qmltpeq @ Y) @ X)))))))))))))).
thf(transitivity, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [X:$i]: ((mbox @ (mforall_di @ (^ [Y:$i]: ((mbox @ (mforall_di @ (^ [Z:$i]: ((mbox @ ((mimplies @ ((mand @ (mbox @ ((qmltpeq @ X) @ Y))) @ (mbox @ ((qmltpeq @ Y) @ Z)))) @ (mbox @ ((qmltpeq @ X) @ Z)))))))))))))))))).
thf(singleton_substitution_1, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ ((mimplies @ (mbox @ ((qmltpeq @ A) @ B))) @ (mbox @ ((qmltpeq @ (singleton @ A)) @ (singleton @ B))))))))))))))).
thf(empty_substitution_1, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ ((mimplies @ ((mand @ (mbox @ ((qmltpeq @ A) @ B))) @ (mbox @ (empty @ A)))) @ (mbox @ (empty @ B)))))))))))))).
thf(in_substitution_1, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ (mforall_di @ (^ [C:$i]: ((mbox @ ((mimplies @ ((mand @ (mbox @ ((qmltpeq @ A) @ B))) @ (mbox @ ((in @ A) @ C)))) @ (mbox @ ((in @ B) @ C)))))))))))))))))).
thf(in_substitution_2, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ (mforall_di @ (^ [C:$i]: ((mbox @ ((mimplies @ ((mand @ (mbox @ ((qmltpeq @ A) @ B))) @ (mbox @ ((in @ C) @ A)))) @ (mbox @ ((in @ C) @ B)))))))))))))))))).
thf(antisymmetry_r2_hidden, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ ((mimplies @ (mbox @ ((in @ A) @ B))) @ (mbox @ (mnot @ (mbox @ ((in @ B) @ A)))))))))))))))).
thf(fc1_xboole_0, axiom, (mlocal @ (mbox @ (empty @ empty_set)))).
thf(rc1_xboole_0, axiom, (mlocal @ (mexists_di @ (^ [A:$i]: ((mbox @ (empty @ A))))))).
thf(rc2_xboole_0, axiom, (mlocal @ (mexists_di @ (^ [A:$i]: ((mbox @ (mnot @ (mbox @ (empty @ A))))))))).
thf(t41_zfmisc_1, conjecture, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ (mnot @ ((mand @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ A) @ (singleton @ B)))))) @ ((mand @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ A) @ empty_set))))) @ (mbox @ (mforall_di @ (^ [C:$i]: ((mbox @ (mnot @ ((mand @ (mbox @ ((in @ C) @ A))) @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ C) @ B))))))))))))))))))))))))).
thf(l45_zfmisc_1, axiom, (mlocal @ (mbox @ (mforall_di @ (^ [A:$i]: ((mbox @ (mforall_di @ (^ [B:$i]: ((mbox @ (mnot @ ((mand @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ A) @ (singleton @ B)))))) @ ((mand @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ A) @ empty_set))))) @ (mbox @ (mforall_di @ (^ [C:$i]: ((mbox @ (mnot @ ((mand @ (mbox @ ((in @ C) @ A))) @ (mbox @ (mnot @ (mbox @ ((qmltpeq @ C) @ B))))))))))))))))))))))))).
