tff(s4_decreasing_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $decreasing,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:04 CEST 2022 using command 'downgrade(tff)'.
tff(element_decl, type, element: (($i * $i) > $o)).
tff(pel39, conjecture, {$box}(~ ((? [X:$i]: ({$box}((! [Y:$i]: (({$box}(({$box}(element(Y,X)) => {$box}(~ ({$box}(element(Y,Y)))))) & {$box}(({$box}(~ ({$box}(element(Y,Y)))) => {$box}(element(Y,X))))))))))))).
