tff(s5_decreasing_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $decreasing,
     $modalities == $modal_system_S5
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:26 CEST 2022 using command 'downgrade(tff)'.
tff(empty_set_decl, type, empty_set: $i).
tff(qmltpeq_decl, type, qmltpeq: (($i * $i) > $o)).
tff(empty_decl, type, empty: ($i > $o)).
tff(singleton_decl, type, singleton: ($i > $i)).
tff(set_union2_decl, type, set_union2: (($i * $i) > $i)).
tff(reflexivity, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ (qmltpeq(X,X)))))).
tff(symmetry, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ ((! [Y:$i]: ({$box} @ (({$box} @ (qmltpeq(X,Y)) => {$box} @ (qmltpeq(Y,X))))))))))).
tff(transitivity, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ ((! [Y:$i]: ({$box} @ ((! [Z:$i]: ({$box} @ ((({$box} @ (qmltpeq(X,Y)) & {$box} @ (qmltpeq(Y,Z))) => {$box} @ (qmltpeq(X,Z)))))))))))))).
tff(set_union2_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(set_union2(A,C),set_union2(B,C))))))))))))))).
tff(set_union2_substitution_2, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(set_union2(C,A),set_union2(C,B))))))))))))))).
tff(singleton_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(singleton(A),singleton(B)))))))))))).
tff(empty_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((({$box} @ (qmltpeq(A,B)) & {$box} @ (empty(A))) => {$box} @ (empty(B))))))))))).
tff(commutativity_k2_xboole_0, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (qmltpeq(set_union2(A,B),set_union2(B,A)))))))))).
tff(fc1_xboole_0, axiom-local, {$box} @ (empty(empty_set))).
tff(fc2_xboole_0, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (({$box} @ (~ ({$box} @ (empty(A)))) => {$box} @ (~ ({$box} @ (empty(set_union2(A,B)))))))))))))).
tff(fc3_xboole_0, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (({$box} @ (~ ({$box} @ (empty(A)))) => {$box} @ (~ ({$box} @ (empty(set_union2(B,A)))))))))))))).
tff(idempotence_k2_xboole_0, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (qmltpeq(set_union2(A,A),A))))))))).
tff(rc1_xboole_0, axiom-local, (? [A:$i]: ({$box} @ (empty(A))))).
tff(rc2_xboole_0, axiom-local, (? [A:$i]: ({$box} @ (~ ({$box} @ (empty(A))))))).
tff(t43_zfmisc_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (~ (({$box} @ (qmltpeq(singleton(A),set_union2(B,C))) & ({$box} @ (~ (({$box} @ (qmltpeq(B,singleton(A))) & {$box} @ (qmltpeq(C,singleton(A)))))) & ({$box} @ (~ (({$box} @ (qmltpeq(B,empty_set)) & {$box} @ (qmltpeq(C,singleton(A)))))) & {$box} @ (~ (({$box} @ (qmltpeq(B,singleton(A))) & {$box} @ (qmltpeq(C,empty_set)))))))))))))))))))).
tff(t44_zfmisc_1, conjecture, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (~ (({$box} @ (qmltpeq(singleton(A),set_union2(B,C))) & ({$box} @ (~ ({$box} @ (qmltpeq(B,C)))) & ({$box} @ (~ ({$box} @ (qmltpeq(B,empty_set)))) & {$box} @ (~ ({$box} @ (qmltpeq(C,empty_set))))))))))))))))))).
