tff(s5_varying_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $varying,
     $modalities == $modal_system_S5
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:37 CEST 2022 using command 'downgrade(tff)'.
tff(empty_set_decl, type, empty_set: $i).
tff(qmltpeq_decl, type, qmltpeq: (($i * $i) > $o)).
tff(subset_decl, type, subset: (($i * $i) > $o)).
tff(empty_decl, type, empty: ($i > $o)).
tff(singleton_decl, type, singleton: ($i > $i)).
tff(set_difference_decl, type, set_difference: (($i * $i) > $i)).
tff(reflexivity, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ (qmltpeq(X,X)))))).
tff(symmetry, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ ((! [Y:$i]: ({$box} @ (({$box} @ (qmltpeq(X,Y)) => {$box} @ (qmltpeq(Y,X))))))))))).
tff(transitivity, axiom-local, {$box} @ ((! [X:$i]: ({$box} @ ((! [Y:$i]: ({$box} @ ((! [Z:$i]: ({$box} @ ((({$box} @ (qmltpeq(X,Y)) & {$box} @ (qmltpeq(Y,Z))) => {$box} @ (qmltpeq(X,Z)))))))))))))).
tff(set_difference_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(set_difference(A,C),set_difference(B,C))))))))))))))).
tff(set_difference_substitution_2, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(set_difference(C,A),set_difference(C,B))))))))))))))).
tff(singleton_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (({$box} @ (qmltpeq(A,B)) => {$box} @ (qmltpeq(singleton(A),singleton(B)))))))))))).
tff(empty_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((({$box} @ (qmltpeq(A,B)) & {$box} @ (empty(A))) => {$box} @ (empty(B))))))))))).
tff(subset_substitution_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ ((({$box} @ (qmltpeq(A,B)) & {$box} @ (subset(A,C))) => {$box} @ (subset(B,C)))))))))))))).
tff(subset_substitution_2, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ ((! [C:$i]: ({$box} @ ((({$box} @ (qmltpeq(A,B)) & {$box} @ (subset(C,A))) => {$box} @ (subset(C,B)))))))))))))).
tff(fc1_xboole_0, axiom-local, {$box} @ (empty(empty_set))).
tff(l4_zfmisc_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: (({$box} @ (({$box} @ (subset(A,singleton(B))) => ({$box} @ (qmltpeq(A,empty_set)) | {$box} @ (qmltpeq(A,singleton(B)))))) & {$box} @ ((({$box} @ (qmltpeq(A,empty_set)) | {$box} @ (qmltpeq(A,singleton(B)))) => {$box} @ (subset(A,singleton(B))))))))))))).
tff(rc1_xboole_0, axiom-local, (? [A:$i]: ({$box} @ (empty(A))))).
tff(rc2_xboole_0, axiom-local, (? [A:$i]: ({$box} @ (~ ({$box} @ (empty(A))))))).
tff(reflexivity_r1_tarski, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (subset(A,A))))))))).
tff(t37_xboole_1, axiom-local, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: (({$box} @ (({$box} @ (qmltpeq(set_difference(A,B),empty_set)) => {$box} @ (subset(A,B)))) & {$box} @ (({$box} @ (subset(A,B)) => {$box} @ (qmltpeq(set_difference(A,B),empty_set)))))))))))).
tff(t66_zfmisc_1, conjecture, {$box} @ ((! [A:$i]: ({$box} @ ((! [B:$i]: ({$box} @ (~ (({$box} @ (qmltpeq(set_difference(A,singleton(B)),empty_set)) & ({$box} @ (~ ({$box} @ (qmltpeq(A,empty_set)))) & {$box} @ (~ ({$box} @ (qmltpeq(A,singleton(B)))))))))))))))).
