%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:45 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, $modal == ([$constants == $rigid,$quantification == $constant,$modalities == $modal_system_S5])).
tff(p_decl, type, p: $o).
tff(con, conjecture, ({$box}({$dia}(p)) => {$box}({$dia}({$box}({$dia}(p)))))).
