%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:01 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, $modal == ([$constants == $rigid,$quantification == $constant,$modalities == $modal_system_S5])).
tff(p_decl, type, p: $o).
tff(con, conjecture, ({$box} @ (({$box} @ ((p => {$box} @ (p))) => {$box} @ (p))) => ({$dia} @ ({$box} @ (p)) => {$box} @ (p)))).
