tff(s4_varying_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $varying,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:09 CEST 2022 using command 'downgrade(tff)'.
tff(a_decl, type, a: ($i > $o)).
tff(con, conjecture, ({$box} @ ((? [X:$i]: ({$dia} @ (a(X))))) => {$box} @ ({$dia} @ ((? [X:$i]: (a(X))))))).
