tff(t_cumulative_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $cumulative,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:49 CEST 2022 using command 'downgrade(tff)'.
tff(r_decl, type, r: (($i * $i) > $o)).
tff(con, conjecture, ((? [X:$i]: ((! [Y:$i]: ({$box} @ (r(X,Y)))))) => (! [Y:$i]: ((? [X:$i]: (r(X,Y))))))).
