tff(k_decreasing_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $decreasing,
     $modalities == $modal_system_K
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:57 CEST 2022 using command 'downgrade(tff)'.
tff(a_decl, type, a: $o).
tff(b_decl, type, b: $o).
tff(f_decl, type, f: ($i > $o)).
tff(con, conjecture, (({$dia} @ ((! [X:$i]: ((f(X) => {$box} @ ((a => ~ (f(X)))))))) & {$box} @ ((? [X:$i]: ((f(X) & {$box} @ ((b => f(X)))))))) => ~ ({$dia} @ ((a & b))))).
