tff(s4_constant_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $constant,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:45 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(a_decl, type, a: $i).
tff(f_decl, type, f: ($i > $o)).
tff(con, conjecture, ((! [X:$i]: (({$dia} @ (f(X)) | {$dia} @ (~ (f(X)))))) => {$box} @ (({$box} @ (f(a)) <=> (p | ~ (p)))))).
