tff(d_decreasing_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $decreasing,
     $modalities == $modal_system_D
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:11 CEST 2022 using command 'downgrade(tff)'.
tff(r_decl, type, r: (($i * $i) > $o)).
tff(con, conjecture, ({$box} @ ((! [X:$i]: ((? [Y:$i]: ({$dia} @ (r(X,Y))))))) => (! [X:$i]: ({$box} @ ({$dia} @ ((? [Y:$i]: (r(X,Y))))))))).
