tff(d_constant_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $constant,
     $modalities == $modal_system_D
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:47 CEST 2022 using command 'downgrade(tff)'.
tff(f_decl, type, f: ($i > $o)).
tff(g_decl, type, g: ($i > $o)).
tff(h_decl, type, h: ($i > $o)).
tff(con, conjecture, (((! [X:$i]: ((f(X) => {$box}(g(X))))) & (! [X:$i]: ((g(X) => {$box}(h(X)))))) => (! [X:$i]: ((f(X) => {$box}(h(X))))))).
