tff(t_varying_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $varying,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:06 CEST 2022 using command 'downgrade(tff)'.
tff(a_decl, type, a: $o).
tff(e_decl, type, e: ($i > $o)).
tff(f_decl, type, f: ($i > $o)).
tff(con, conjecture, (({$box} @ ((! [X:$i]: ({$box} @ (e(X))))) & (a & {$dia} @ ((! [X:$i]: ((f(X) => {$box} @ ((a => ~ (f(X)))))))))) => {$box} @ ((? [X:$i]: ({$dia} @ (~ (f(X)))))))).
