tff(t_constant_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $constant,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:31 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(q_decl, type, q: $o).
tff(r_decl, type, r: $o).
tff(con, conjecture, (({$box} @ ((p => q)) & {$box} @ ((q => r))) => {$box} @ ((p => r)))).
