tff(s4_cumulative_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $cumulative,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:09 CEST 2022 using command 'downgrade(tff)'.
tff(v1_decl, type, v1: $o).
tff(v2_decl, type, v2: $o).
tff(v3_decl, type, v3: $o).
tff(v4_decl, type, v4: $o).
tff(persat1, axiom-local, (v1 | (v4 | (~ (v3) | {$box} @ ({$box} @ (v4)))))).
tff(persat2, axiom-local, (v1 | ({$box} @ (~ (v4)) | ({$box} @ ({$box} @ (v4)) | {$box} @ ({$box} @ (~ (v3))))))).
tff(persat3, axiom-local, (v2 | (v4 | ({$box} @ (v1) | {$box} @ ({$box} @ (v2)))))).
tff(persat4, axiom-local, (v2 | ({$box} @ (v4) | ({$box} @ (~ (v1)) | {$box} @ ({$box} @ (v4)))))).
tff(persat5, axiom-local, (v3 | (v4 | ({$box} @ ({$box} @ (v1)) | {$box} @ ({$box} @ (v4)))))).
tff(persat6, axiom-local, (v3 | (v4 | ({$box} @ ({$box} @ (v1)) | {$box} @ ({$box} @ (~ (v2))))))).
tff(persat7, axiom-local, (v3 | (~ (v1) | ({$box} @ ({$box} @ (~ (v2))) | {$box} @ ({$box} @ (~ (v4))))))).
tff(persat8, axiom-local, (v3 | (~ (v2) | ({$box} @ (v1) | {$box} @ ({$box} @ (v2)))))).
tff(persat9, axiom-local, (v3 | (~ (v2) | ({$box} @ ({$box} @ (v2)) | {$box} @ ({$box} @ (~ (v2))))))).
tff(persat10, axiom-local, (v3 | (~ (v4) | ({$box} @ (~ (v2)) | {$box} @ ({$box} @ (v1)))))).
tff(persat11, axiom-local, (v3 | ({$box} @ (~ (v3)) | ({$box} @ (~ (v4)) | {$box} @ ({$box} @ (v3)))))).
tff(persat12, axiom-local, (v3 | ({$box} @ ({$box} @ (v3)) | ({$box} @ ({$box} @ (~ (v2))) | {$box} @ ({$box} @ (~ (v3))))))).
tff(persat13, axiom-local, (v4 | (~ (v2) | ({$box} @ (~ (v1)) | {$box} @ ({$box} @ (v4)))))).
tff(persat14, axiom-local, (v4 | ({$box} @ (v2) | ({$box} @ (~ (v2)) | {$box} @ ({$box} @ (v1)))))).
tff(persat15, axiom-local, (v4 | ({$box} @ (v4) | ({$box} @ ({$box} @ (v2)) | {$box} @ ({$box} @ (v4)))))).
tff(persat16, axiom-local, (v4 | ({$box} @ (~ (v1)) | ({$box} @ (~ (v3)) | {$box} @ ({$box} @ (~ (v3))))))).
tff(persat17, axiom-local, (~ (v1) | (~ (v2) | ({$box} @ ({$box} @ (~ (v1))) | {$box} @ ({$box} @ (~ (v4))))))).
tff(persat18, axiom-local, (~ (v3) | ({$box} @ (v2) | ({$box} @ ({$box} @ (v4)) | {$box} @ ({$box} @ (~ (v3))))))).
tff(persat19, axiom-local, (~ (v3) | ({$box} @ (~ (v2)) | ({$box} @ ({$box} @ (v1)) | {$box} @ ({$box} @ (v2)))))).
tff(persat20, axiom-local, (~ (v4) | ({$box} @ (v2) | ({$box} @ ({$box} @ (v1)) | {$box} @ ({$box} @ (v4)))))).
tff(deontic1, axiom-local, {$dia} @ ($true)).
tff(result1, conjecture, $false).
