% semantics
% modalities

% propositions

% individual constants

% predicates
thf(chevy_type,type,(chevy : ($i>$o))).
thf(dirty_type,type,(dirty : ($i>$o))).
thf(barrel_type,type,(barrel : ($i>$i>$o))).
thf(hollywood_type,type,(hollywood : ($i>$o))).
thf(city_type,type,(city : ($i>$o))).
thf(in_type,type,(in : ($i>$i>$o))).
thf(young_type,type,(young : ($i>$o))).
thf(old_type,type,(old : ($i>$o))).
thf(down_type,type,(down : ($i>$i>$o))).
thf(way_type,type,(way : ($i>$o))).
thf(qmltpeq_type,type,(qmltpeq : ($i>$i>$o))).
thf(seat_type,type,(seat : ($i>$o))).
thf(white_type,type,(white : ($i>$o))).
thf(car_type,type,(car : ($i>$o))).
thf(furniture_type,type,(furniture : ($i>$o))).
thf(street_type,type,(street : ($i>$o))).
thf(fellow_type,type,(fellow : ($i>$o))).
thf(front_type,type,(front : ($i>$o))).
thf(man_type,type,(man : ($i>$o))).
thf(event_type,type,(event : ($i>$o))).
thf(lonely_type,type,(lonely : ($i>$o))).

% functions

% converted problem
%------------------------------------------------------------------------------
% File     : NLP004+1 : TPTP v51.1
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem 4
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".
% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner (1999), FTP'2000 - Problem Sets
% Source   : [Bau99]
% Names    :
% Status   :      varying      cumulative   constant
%             K   Unsolved     Unsolved     Unsolved      v1.1
%             D   Theorem      Theorem      Theorem       v1.1
%             T   Theorem      Theorem      Theorem       v1.1
%             S4  Theorem      Theorem      Theorem       v1.1
%             S5  Theorem      Theorem      Theorem       v1.1
%
% Rating   :      varying      cumulative   constant
%             K   1.00         1.00         1.00          v1.1
%             D   0.50         0.67         0.67          v1.1
%             T   0.50         0.67         0.67          v1.1
%             S4  0.50         0.67         0.67          v1.1
%             S5  0.50         0.60         0.60          v1.1
%
%  term conditions for all terms: designation: rigid, extension: local
% Comments :
%--------------------------------------------------------------------------
thf ( reflexivity , axiom , ( ! [ X :$i ] : ( qmltpeq @ X @ X ) ) ) .
thf ( symmetry , axiom , ( ! [ X :$i , Y :$i ] : ( ( qmltpeq @ X @ Y ) => ( qmltpeq @ Y @ X ) ) ) ) .
thf ( transitivity , axiom , ( ! [ X :$i , Y :$i , Z :$i ] : ( ( ( qmltpeq @ X @ Y ) & ( qmltpeq @ Y @ Z ) ) => ( qmltpeq @ X @ Z ) ) ) ) .
thf ( barrel_substitution_1 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( barrel @ A @ C ) ) => ( barrel @ B @ C ) ) ) ) .
thf ( barrel_substitution_2 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( barrel @ C @ A ) ) => ( barrel @ C @ B ) ) ) ) .
thf ( car_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( car @ A ) ) => ( car @ B ) ) ) ) .
thf ( chevy_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( chevy @ A ) ) => ( chevy @ B ) ) ) ) .
thf ( city_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( city @ A ) ) => ( city @ B ) ) ) ) .
thf ( dirty_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( dirty @ A ) ) => ( dirty @ B ) ) ) ) .
thf ( down_substitution_1 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( down @ A @ C ) ) => ( down @ B @ C ) ) ) ) .
thf ( down_substitution_2 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( down @ C @ A ) ) => ( down @ C @ B ) ) ) ) .
thf ( event_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( event @ A ) ) => ( event @ B ) ) ) ) .
thf ( fellow_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( fellow @ A ) ) => ( fellow @ B ) ) ) ) .
thf ( front_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( front @ A ) ) => ( front @ B ) ) ) ) .
thf ( furniture_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( furniture @ A ) ) => ( furniture @ B ) ) ) ) .
thf ( hollywood_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( hollywood @ A ) ) => ( hollywood @ B ) ) ) ) .
thf ( in_substitution_1 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( in @ A @ C ) ) => ( in @ B @ C ) ) ) ) .
thf ( in_substitution_2 , axiom , ( ! [ A :$i , B :$i , C :$i ] : ( ( ( qmltpeq @ A @ B ) & ( in @ C @ A ) ) => ( in @ C @ B ) ) ) ) .
thf ( lonely_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( lonely @ A ) ) => ( lonely @ B ) ) ) ) .
thf ( man_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( man @ A ) ) => ( man @ B ) ) ) ) .
thf ( old_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( old @ A ) ) => ( old @ B ) ) ) ) .
thf ( seat_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( seat @ A ) ) => ( seat @ B ) ) ) ) .
thf ( street_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( street @ A ) ) => ( street @ B ) ) ) ) .
thf ( way_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( way @ A ) ) => ( way @ B ) ) ) ) .
thf ( white_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( white @ A ) ) => ( white @ B ) ) ) ) .
thf ( young_substitution_1 , axiom , ( ! [ A :$i , B :$i ] : ( ( ( qmltpeq @ A @ B ) & ( young @ A ) ) => ( young @ B ) ) ) ) .
thf ( co1 , conjecture , ( ( ( ? [ U :$i , V :$i , W :$i , X :$i , Y :$i , Z :$i , X1 :$i , X2 :$i , X4 :$i , X5 :$i ] : ( ( seat @ U ) & ( furniture @ U ) & ( front @ U ) & ( seat @ V ) & ( furniture @ V ) & ( front @ V ) & ( hollywood @ W ) & ( city @ W ) & ( event @ X ) & ( street @ Y ) & ( way @ Y ) & ( lonely @ Y ) & ( chevy @ Z ) & ( car @ Z ) & ( white @ Z ) & ( dirty @ Z ) & ( old @ Z ) & ( barrel @ X @ Z ) & ( down @ X @ Y ) & ( in @ X @ W ) & ~ ( ( qmltpeq @ X1 @ X2 ) ) & ( fellow @ X1 ) & ( man @ X1 ) & ( young @ X1 ) & ( fellow @ X2 ) & ( man @ X2 ) & ( young @ X2 ) & ( qmltpeq @ X1 @ X4 ) & ( in @ X4 @ U ) & ( qmltpeq @ X2 @ X5 ) & ( in @ X5 @ V ) ) => ? [ X6 :$i , X7 :$i , X8 :$i , X9 :$i , X10 :$i , X11 :$i , X12 :$i , X13 :$i , X15 :$i , X16 :$i ] : ( ( seat @ X6 ) & ( furniture @ X6 ) & ( front @ X6 ) & ( seat @ X7 ) & ( furniture @ X7 ) & ( front @ X7 ) & ( hollywood @ X8 ) & ( city @ X8 ) & ( event @ X9 ) & ( chevy @ X10 ) & ( car @ X10 ) & ( white @ X10 ) & ( dirty @ X10 ) & ( old @ X10 ) & ( street @ X11 ) & ( way @ X11 ) & ( lonely @ X11 ) & ( barrel @ X9 @ X10 ) & ( down @ X9 @ X11 ) & ( in @ X9 @ X8 ) & ~ ( ( qmltpeq @ X12 @ X13 ) ) & ( fellow @ X12 ) & ( man @ X12 ) & ( young @ X12 ) & ( fellow @ X13 ) & ( man @ X13 ) & ( young @ X13 ) & ( qmltpeq @ X12 @ X15 ) & ( in @ X15 @ X6 ) & ( qmltpeq @ X13 @ X16 ) & ( in @ X16 @ X7 ) ) ) & ( ? [ X17 :$i , X18 :$i , X19 :$i , X20 :$i , X21 :$i , X22 :$i , X23 :$i , X24 :$i , X26 :$i , X27 :$i ] : ( ( seat @ X17 ) & ( furniture @ X17 ) & ( front @ X17 ) & ( seat @ X18 ) & ( furniture @ X18 ) & ( front @ X18 ) & ( hollywood @ X19 ) & ( city @ X19 ) & ( event @ X20 ) & ( chevy @ X21 ) & ( car @ X21 ) & ( white @ X21 ) & ( dirty @ X21 ) & ( old @ X21 ) & ( street @ X22 ) & ( way @ X22 ) & ( lonely @ X22 ) & ( barrel @ X20 @ X21 ) & ( down @ X20 @ X22 ) & ( in @ X20 @ X19 ) & ~ ( ( qmltpeq @ X23 @ X24 ) ) & ( fellow @ X23 ) & ( man @ X23 ) & ( young @ X23 ) & ( fellow @ X24 ) & ( man @ X24 ) & ( young @ X24 ) & ( qmltpeq @ X23 @ X26 ) & ( in @ X26 @ X17 ) & ( qmltpeq @ X24 @ X27 ) & ( in @ X27 @ X18 ) ) => ? [ X28 :$i , X29 :$i , X30 :$i , X31 :$i , X32 :$i , X33 :$i , X34 :$i , X35 :$i , X37 :$i , X38 :$i ] : ( ( seat @ X28 ) & ( furniture @ X28 ) & ( front @ X28 ) & ( seat @ X29 ) & ( furniture @ X29 ) & ( front @ X29 ) & ( hollywood @ X30 ) & ( city @ X30 ) & ( event @ X31 ) & ( street @ X32 ) & ( way @ X32 ) & ( lonely @ X32 ) & ( chevy @ X33 ) & ( car @ X33 ) & ( white @ X33 ) & ( dirty @ X33 ) & ( old @ X33 ) & ( barrel @ X31 @ X33 ) & ( down @ X31 @ X32 ) & ( in @ X31 @ X30 ) & ~ ( ( qmltpeq @ X34 @ X35 ) ) & ( fellow @ X34 ) & ( man @ X34 ) & ( young @ X34 ) & ( fellow @ X35 ) & ( man @ X35 ) & ( young @ X35 ) & ( qmltpeq @ X34 @ X37 ) & ( in @ X37 @ X28 ) & ( qmltpeq @ X35 @ X38 ) & ( in @ X38 @ X29 ) ) ) ) ) ) .
%------------------------------------------------------------------------------