tff(s5_decreasing_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $decreasing,
     $modalities == $modal_system_S5U
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:50 CEST 2022 using command 'downgrade(tff)'.
tff(a_decl, type, a: ($i > $o)).
tff(b_decl, type, b: ($i > $o)).
tff(con, conjecture, (({$dia}((! [X:$i]: (a(X)))) & {$box}((? [X:$i]: (b(X))))) => {$box}((? [X:$i]: ((a(X) & b(X))))))).
