%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : Goedel translation of SYN047+1 (from TPTP-v5.0.0)
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GSY047+1 [QMLTP]

% Status   : Theorem 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   25 (   9 unt;  15 typ;   8 def)
%            Number of atoms       :   97 (   8 equ;   0 cnn)
%            Maximal formula atoms :   78 (   9 avg)
%            Number of connectives :  102 (   1   ~;   1   |;   2   &;  95   @)
%                                         (   1 <=>;   2  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   15 (   3 avg)
%            Number of types       :    2 (   1 usr)
%            Number of type conns  :   49 (  49   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   15 (  14 usr;   1 con; 0-3 aty)
%            Number of variables   :   23 (  19   ^   3   !;   1   ?;  23   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $varying,
%            $modalities == $modal_system_S5U].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_universal,axiom,
    ! [W: mworld,V: mworld] : ( mrel @ W @ V ) ).

%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:46 CEST 2022 using command 'downgrade(tff)'.
thf(p_decl,type,
    p: mworld > $o ).

thf(q_decl,type,
    q: mworld > $o ).

thf(r_decl,type,
    r: mworld > $o ).

thf(s_decl,type,
    s: mworld > $o ).

thf(pel17,conjecture,
    mlocal @ ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ p ) @ ( mbox @ ( mimplies @ ( mbox @ q ) @ ( mbox @ r ) ) ) ) @ ( mbox @ s ) ) ) @ ( mand @ ( mor @ ( mbox @ ( mnot @ ( mbox @ p ) ) ) @ ( mor @ ( mbox @ q ) @ ( mbox @ s ) ) ) @ ( mor @ ( mbox @ ( mnot @ ( mbox @ p ) ) ) @ ( mor @ ( mbox @ ( mnot @ ( mbox @ r ) ) ) @ ( mbox @ s ) ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mand @ ( mor @ ( mbox @ ( mnot @ ( mbox @ p ) ) ) @ ( mor @ ( mbox @ q ) @ ( mbox @ s ) ) ) @ ( mor @ ( mbox @ ( mnot @ ( mbox @ p ) ) ) @ ( mor @ ( mbox @ ( mnot @ ( mbox @ r ) ) ) @ ( mbox @ s ) ) ) ) @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ p ) @ ( mbox @ ( mimplies @ ( mbox @ q ) @ ( mbox @ r ) ) ) ) @ ( mbox @ s ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
