%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : Goedel translation of SYN364+1 (from TPTP-v5.0.0)
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GSY364+1 [QMLTP]

% Status   : Theorem 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   30 (  11 unt;  18 typ;  10 def)
%            Number of atoms       :   68 (  10 equ;   0 cnn)
%            Maximal formula atoms :   45 (   5 avg)
%            Number of connectives :   91 (   1   ~;   1   |;   2   &;  84   @)
%                                         (   1 <=>;   2  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   19 (   3 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :   67 (  67   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   18 (  17 usr;   1 con; 0-3 aty)
%            Number of variables   :   37 (  31   ^   4   !;   2   ?;  37   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $constant,
%            $modalities == $modal_system_S5U].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_universal,axiom,
    ! [W: mworld,V: mworld] : ( mrel @ W @ V ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] : ( A @ X @ W ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] : ( A @ X @ W ) ) ) ).

%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:54 CEST 2022 using command 'downgrade(tff)'.
thf(big_q_decl,type,
    big_q: $i > mworld > $o ).

thf(big_p_decl,type,
    big_p: $i > $i > mworld > $o ).

thf(big_m_decl,type,
    big_m: $i > mworld > $o ).

thf(f_decl,type,
    f: $i > $i > $i ).

thf(g_decl,type,
    g: $i > $i ).

thf(x2115,conjecture,
    ( mlocal
    @ ( mbox
      @ ( mimplies
        @ ( mand
          @ ( mbox
            @ ( mforall_di
              @ ^ [X: $i] :
                  ( mbox
                  @ ( mimplies
                    @ ( mexists_di
                      @ ^ [Y: $i] : ( mbox @ ( big_p @ X @ Y ) ) )
                    @ ( mbox
                      @ ( mforall_di
                        @ ^ [Z: $i] : ( mbox @ ( big_p @ Z @ Z ) ) ) ) ) ) ) )
          @ ( mand
            @ ( mbox
              @ ( mforall_di
                @ ^ [U: $i] :
                    ( mexists_di
                    @ ^ [V: $i] : ( mor @ ( mbox @ ( big_p @ U @ V ) ) @ ( mand @ ( mbox @ ( big_m @ U ) ) @ ( mbox @ ( big_q @ ( f @ U @ V ) ) ) ) ) ) ) )
            @ ( mbox
              @ ( mforall_di
                @ ^ [W: $i] : ( mbox @ ( mimplies @ ( mbox @ ( big_q @ W ) ) @ ( mbox @ ( mnot @ ( mbox @ ( big_m @ ( g @ W ) ) ) ) ) ) ) ) ) ) )
        @ ( mbox
          @ ( mforall_di
            @ ^ [U: $i] :
                ( mexists_di
                @ ^ [V: $i] : ( mand @ ( mbox @ ( big_p @ ( g @ U ) @ V ) ) @ ( mbox @ ( big_p @ U @ U ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
