%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:59 CEST 2022 using command 'downgrade(tff)'.
tff(semantics, logic, $modal == ([$constants == $rigid,$quantification == $constant,$modalities == $modal_system_S5])).
tff(big_p_decl, type, big_p: ($i > $o)).
tff(x2125, conjecture, ({$box}(((? [X:$i]: ({$box}((! [Y:$i]: (({$box}(({$box}(big_p(X)) => {$box}(big_p(Y)))) & {$box}(({$box}(big_p(Y)) => {$box}(big_p(X)))))))))) => ({$box}(((? [X:$i]: ({$box}(big_p(X)))) => {$box}((! [Y:$i]: ({$box}(big_p(Y))))))) & {$box}(({$box}((! [Y:$i]: ({$box}(big_p(Y))))) => (? [X:$i]: ({$box}(big_p(X))))))))) & {$box}((({$box}(((? [X:$i]: ({$box}(big_p(X)))) => {$box}((! [Y:$i]: ({$box}(big_p(Y))))))) & {$box}(({$box}((! [Y:$i]: ({$box}(big_p(Y))))) => (? [X:$i]: ({$box}(big_p(X))))))) => (? [X:$i]: ({$box}((! [Y:$i]: (({$box}(({$box}(big_p(X)) => {$box}(big_p(Y)))) & {$box}(({$box}(big_p(Y)) => {$box}(big_p(X)))))))))))))).
