%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:49:43 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $i).
tff(fortytwo_type, type, fortytwo: $i).
tff(balance_type, type, balance: (($i * $i) > $o)).
tff(account_type, type, account: (($i * $i) > $o)).
tff(axiom_1, axiom, {$box(#bank)}((! [X:$i]: ({$box(#cr)}((account(p,X) => (? [B:$i]: ({$box(#t)}(balance(p,B)))))))))).
tff(axiom_1_0, axiom, {$box(#cr)}(account(p,fortytwo))).
tff(con, conjecture, (? [B:$i]: ({$box(#t)}(balance(p,B))))).
