%------------------------------------------------------------------------------
% File     : SYM354^1.001 : TPTP v8.1.0. Released v8.1.0.
% Domain   : Syntactic
% Problem  : QBF-CNFSSS-K=4 C=40 V=8 D=4.6
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : SYM354+1 [QMLTP]

% Status   : Unknown 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :  101 (   8 unt;  51 typ;   8 def)
%            Number of atoms       : 1913 (   8 equ;   0 cnn)
%            Maximal formula atoms :  223 (  38 avg)
%            Number of connectives : 1876 (   1   ~;   1   |;   2   &;1869   @)
%                                         (   1 <=>;   2  =>;   0  <=;   0 <~>)
%            Maximal formula depth :  121 (  32 avg)
%            Number of types       :    2 (   1 usr)
%            Number of type conns  :   85 (  85   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   53 (  50 usr;   3 con; 0-3 aty)
%            Number of variables   :   46 (  44   ^   1   !;   1   ?;  46   :)
% SPC      : TH0_UNK_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $constant,
%            $modalities == $modal_system_K].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(v1_decl,type,
    v1: mworld > $o ).

thf(v2_decl,type,
    v2: mworld > $o ).

thf(v3_decl,type,
    v3: mworld > $o ).

thf(v4_decl,type,
    v4: mworld > $o ).

thf(v5_decl,type,
    v5: mworld > $o ).

thf(v6_decl,type,
    v6: mworld > $o ).

thf(v7_decl,type,
    v7: mworld > $o ).

thf(v8_decl,type,
    v8: mworld > $o ).

thf(v9_decl,type,
    v9: mworld > $o ).

thf(v10_decl,type,
    v10: mworld > $o ).

thf(v12_decl,type,
    v12: mworld > $o ).

thf(v11_decl,type,
    v11: mworld > $o ).

thf(v14_decl,type,
    v14: mworld > $o ).

thf(v13_decl,type,
    v13: mworld > $o ).

thf(v16_decl,type,
    v16: mworld > $o ).

thf(v15_decl,type,
    v15: mworld > $o ).

thf(v18_decl,type,
    v18: mworld > $o ).

thf(v17_decl,type,
    v17: mworld > $o ).

thf(v19_decl,type,
    v19: mworld > $o ).

thf(v21_decl,type,
    v21: mworld > $o ).

thf(v20_decl,type,
    v20: mworld > $o ).

thf(v23_decl,type,
    v23: mworld > $o ).

thf(v22_decl,type,
    v22: mworld > $o ).

thf(v25_decl,type,
    v25: mworld > $o ).

thf(v24_decl,type,
    v24: mworld > $o ).

thf(v27_decl,type,
    v27: mworld > $o ).

thf(v26_decl,type,
    v26: mworld > $o ).

thf(v29_decl,type,
    v29: mworld > $o ).

thf(v28_decl,type,
    v28: mworld > $o ).

thf(v30_decl,type,
    v30: mworld > $o ).

thf(v32_decl,type,
    v32: mworld > $o ).

thf(v31_decl,type,
    v31: mworld > $o ).

thf(v34_decl,type,
    v34: mworld > $o ).

thf(v33_decl,type,
    v33: mworld > $o ).

thf(v36_decl,type,
    v36: mworld > $o ).

thf(v35_decl,type,
    v35: mworld > $o ).

thf(v38_decl,type,
    v38: mworld > $o ).

thf(v37_decl,type,
    v37: mworld > $o ).

thf(v39_decl,type,
    v39: mworld > $o ).

thf(v40_decl,type,
    v40: mworld > $o ).

thf(mod1,axiom,
    mlocal @ ( mbox @ ( mor @ v40 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v31 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v15 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod2,axiom,
    mlocal @ ( mbox @ ( mor @ v40 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v25 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v22 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod3,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v40 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v30 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v22 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v14 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod4,axiom,
    mlocal @ ( mbox @ ( mor @ ( mnot @ v40 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v26 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v22 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v14 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod5,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ v39 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v25 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v21 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v13 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod6,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ v39 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v24 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v9 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod7,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v39 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v32 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod8,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v39 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v32 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v28 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v17 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod9,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v39 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v31 ) @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v28 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod10,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v39 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v29 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v11 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod11,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v39 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v27 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v16 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod12,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v38 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v29 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v18 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v13 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod13,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v37 @ ( mbox @ ( mor @ ( mnot @ v36 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v31 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v12 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod14,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v37 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v34 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v29 @ ( mbox @ ( mnot @ v28 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod15,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v37 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v31 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v21 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v9 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod16,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v37 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v21 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v15 @ ( mbox @ v14 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod17,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v37 ) @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v34 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v26 ) @ ( mbox @ v25 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod18,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v37 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v31 @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v29 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v22 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod19,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v37 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v31 ) @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v28 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod20,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v36 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v33 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v29 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v16 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod21,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v36 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v25 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v18 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod22,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v36 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v30 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v24 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v10 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod23,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v35 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v30 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v11 @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod24,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v35 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v28 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v13 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod25,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v35 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v14 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v10 @ ( mbox @ ( mbox @ ( mnot @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod26,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v34 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v27 @ ( mbox @ ( mor @ v26 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v21 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod27,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v33 ) @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v31 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v9 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod28,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v33 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v22 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v14 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v10 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod29,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v30 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v9 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v6 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod30,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v29 @ ( mbox @ ( mor @ ( mnot @ v28 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v18 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v6 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod31,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v29 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v26 ) @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v24 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v6 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod32,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v29 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v25 @ ( mbox @ ( mor @ ( mnot @ v24 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod33,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v28 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v25 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v19 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod34,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v28 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v23 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v17 @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v14 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod35,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v28 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v21 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v15 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod36,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v27 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v23 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v10 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod37,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v27 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v13 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v4 @ ( mbox @ ( mnot @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod38,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v27 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v20 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v12 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod39,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v19 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v16 @ ( mbox @ ( mor @ v15 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mnot @ v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(mod40,axiom,
    mlocal @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v18 @ ( mbox @ ( mbox @ ( mbox @ ( mor @ ( mnot @ v15 ) @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mor @ v10 @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ ( mbox @ v5 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(alt1,axiom,
    ( mlocal
    @ ( mand
      @ ( mbox
        @ ( mand
          @ ( mbox
            @ ( mand
              @ ( mbox
                @ ( mand
                  @ ( mbox
                    @ ( mand
                      @ ( mbox
                        @ ( mand
                          @ ( mbox
                            @ ( mand
                              @ ( mbox
                                @ ( mand
                                  @ ( mbox
                                    @ ( mand
                                      @ ( mbox
                                        @ ( mand
                                          @ ( mbox
                                            @ ( mand
                                              @ ( mbox
                                                @ ( mand
                                                  @ ( mbox
                                                    @ ( mand
                                                      @ ( mbox
                                                        @ ( mand
                                                          @ ( mbox
                                                            @ ( mand
                                                              @ ( mbox
                                                                @ ( mand
                                                                  @ ( mbox
                                                                    @ ( mand
                                                                      @ ( mbox
                                                                        @ ( mand
                                                                          @ ( mbox
                                                                            @ ( mand
                                                                              @ ( mbox
                                                                                @ ( mand
                                                                                  @ ( mbox
                                                                                    @ ( mand
                                                                                      @ ( mbox
                                                                                        @ ( mand
                                                                                          @ ( mbox
                                                                                            @ ( mand
                                                                                              @ ( mbox
                                                                                                @ ( mand
                                                                                                  @ ( mbox
                                                                                                    @ ( mand
                                                                                                      @ ( mbox
                                                                                                        @ ( mand
                                                                                                          @ ( mbox
                                                                                                            @ ( mand
                                                                                                              @ ( mbox
                                                                                                                @ ( mand
                                                                                                                  @ ( mbox
                                                                                                                    @ ( mand
                                                                                                                      @ ( mbox
                                                                                                                        @ ( mand
                                                                                                                          @ ( mbox
                                                                                                                            @ ( mand
                                                                                                                              @ ( mbox
                                                                                                                                @ ( mand
                                                                                                                                  @ ( mbox
                                                                                                                                    @ ( mand
                                                                                                                                      @ ( mbox
                                                                                                                                        @ ( mand
                                                                                                                                          @ ( mbox
                                                                                                                                            @ ( mand
                                                                                                                                              @ ( mbox
                                                                                                                                                @ ( mand
                                                                                                                                                  @ ( mbox
                                                                                                                                                    @ ( mand
                                                                                                                                                      @ ( mbox
                                                                                                                                                        @ ( mand
                                                                                                                                                          @ ( mbox
                                                                                                                                                            @ ( mand
                                                                                                                                                              @ ( mbox
                                                                                                                                                                @ ( mdia
                                                                                                                                                                  @ ^ [W: mworld] : $true ) )
                                                                                                                                                              @ ( mdia
                                                                                                                                                                @ ^ [W: mworld] : $true ) ) )
                                                                                                                                                          @ ( mdia
                                                                                                                                                            @ ^ [W: mworld] : $true ) ) )
                                                                                                                                                      @ ( mdia
                                                                                                                                                        @ ^ [W: mworld] : $true ) ) )
                                                                                                                                                  @ ( mdia
                                                                                                                                                    @ ^ [W: mworld] : $true ) ) )
                                                                                                                                              @ ( mdia
                                                                                                                                                @ ^ [W: mworld] : $true ) ) )
                                                                                                                                          @ ( mdia
                                                                                                                                            @ ^ [W: mworld] : $true ) ) )
                                                                                                                                      @ ( mdia
                                                                                                                                        @ ^ [W: mworld] : $true ) ) )
                                                                                                                                  @ ( mand @ ( mdia @ v9 ) @ ( mdia @ ( mnot @ v9 ) ) ) ) )
                                                                                                                              @ ( mand @ ( mdia @ v10 ) @ ( mdia @ ( mnot @ v10 ) ) ) ) )
                                                                                                                          @ ( mand @ ( mdia @ v11 ) @ ( mdia @ ( mnot @ v11 ) ) ) ) )
                                                                                                                      @ ( mand @ ( mdia @ v12 ) @ ( mdia @ ( mnot @ v12 ) ) ) ) )
                                                                                                                  @ ( mand @ ( mdia @ v13 ) @ ( mdia @ ( mnot @ v13 ) ) ) ) )
                                                                                                              @ ( mand @ ( mdia @ v14 ) @ ( mdia @ ( mnot @ v14 ) ) ) ) )
                                                                                                          @ ( mand @ ( mdia @ v15 ) @ ( mdia @ ( mnot @ v15 ) ) ) ) )
                                                                                                      @ ( mand @ ( mdia @ v16 ) @ ( mdia @ ( mnot @ v16 ) ) ) ) )
                                                                                                  @ ( mdia
                                                                                                    @ ^ [W: mworld] : $true ) ) )
                                                                                              @ ( mdia
                                                                                                @ ^ [W: mworld] : $true ) ) )
                                                                                          @ ( mdia
                                                                                            @ ^ [W: mworld] : $true ) ) )
                                                                                      @ ( mdia
                                                                                        @ ^ [W: mworld] : $true ) ) )
                                                                                  @ ( mdia
                                                                                    @ ^ [W: mworld] : $true ) ) )
                                                                              @ ( mdia
                                                                                @ ^ [W: mworld] : $true ) ) )
                                                                          @ ( mdia
                                                                            @ ^ [W: mworld] : $true ) ) )
                                                                      @ ( mdia
                                                                        @ ^ [W: mworld] : $true ) ) )
                                                                  @ ( mand @ ( mdia @ v25 ) @ ( mdia @ ( mnot @ v25 ) ) ) ) )
                                                              @ ( mand @ ( mdia @ v26 ) @ ( mdia @ ( mnot @ v26 ) ) ) ) )
                                                          @ ( mand @ ( mdia @ v27 ) @ ( mdia @ ( mnot @ v27 ) ) ) ) )
                                                      @ ( mand @ ( mdia @ v28 ) @ ( mdia @ ( mnot @ v28 ) ) ) ) )
                                                  @ ( mand @ ( mdia @ v29 ) @ ( mdia @ ( mnot @ v29 ) ) ) ) )
                                              @ ( mand @ ( mdia @ v30 ) @ ( mdia @ ( mnot @ v30 ) ) ) ) )
                                          @ ( mand @ ( mdia @ v31 ) @ ( mdia @ ( mnot @ v31 ) ) ) ) )
                                      @ ( mand @ ( mdia @ v32 ) @ ( mdia @ ( mnot @ v32 ) ) ) ) )
                                  @ ( mdia
                                    @ ^ [W: mworld] : $true ) ) )
                              @ ( mdia
                                @ ^ [W: mworld] : $true ) ) )
                          @ ( mdia
                            @ ^ [W: mworld] : $true ) ) )
                      @ ( mdia
                        @ ^ [W: mworld] : $true ) ) )
                  @ ( mdia
                    @ ^ [W: mworld] : $true ) ) )
              @ ( mdia
                @ ^ [W: mworld] : $true ) ) )
          @ ( mdia
            @ ^ [W: mworld] : $true ) ) )
      @ ( mdia
        @ ^ [W: mworld] : $true ) ) ) ).

thf(result1,conjecture,
    ( mlocal
    @ ^ [W: mworld] : $false ) ).

%------------------------------------------------------------------------------
