%%% This output was generated by embedproblem, version 1.7.1 (library version 1.3).
%%% Generated on Thu Apr 28 16:43:52 EDT 2022
%%% using 'modal' embedding, version 1.5.2.
%%% Logic specification used:
%%% tff(d_cumulative_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($cumulative),($modalities) == ($modal_system_D)])).

thf(mworld, type, mworld: $tType).
thf(mrel_type, type, mrel: (mworld > (mworld > $o))).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: ((mworld > $o) > (mworld > $o))).
thf(mbox_def, definition, (mbox = (^ [Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: ((((mrel @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: ((mworld > $o) > (mworld > $o))).
thf(mdia_def, definition, (mdia = (^ [Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: ((((mrel @ W) @ V) & (Phi @ V)))))))).
thf(mrel_serial, axiom, (! [W:mworld]: ((? [V:mworld]: (((mrel @ W) @ V)))))).
thf(eiw_di_type, type, eiw_di: ($i > (mworld > $o))).
thf(eiw_di_nonempty, axiom, (! [W:mworld]: ((? [X:$i]: (((eiw_di @ X) @ W)))))).
thf(eiw_di_cumul, axiom, (! [W:mworld,V:mworld,X:$i]: (((((eiw_di @ X) @ W) & ((mrel @ W) @ V)) => ((eiw_di @ X) @ V))))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: ((((eiw_di @ X) @ W) => ((A @ X) @ W)))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: ((((eiw_di @ X) @ W) & ((A @ X) @ W)))))))).
thf(qmltpeq_decl, type, qmltpeq: ($i > ($i > (mworld > $o)))).
thf(in_decl, type, in: ($i > ($i > (mworld > $o)))).
thf(empty_decl, type, empty: ($i > (mworld > $o))).
thf(singleton_decl, type, singleton: ($i > $i)).
thf(set_difference_decl, type, set_difference: ($i > ($i > $i))).
thf(reflexivity, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: (((qmltpeq @ X) @ X)))))).
thf(symmetry, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: (((mimplies @ ((qmltpeq @ X) @ Y)) @ ((qmltpeq @ Y) @ X)))))))))).
thf(transitivity, axiom, (mlocal @ (mforall_di @ (^ [X:$i]: ((mforall_di @ (^ [Y:$i]: ((mforall_di @ (^ [Z:$i]: (((mimplies @ ((mand @ ((qmltpeq @ X) @ Y)) @ ((qmltpeq @ Y) @ Z))) @ ((qmltpeq @ X) @ Z))))))))))))).
thf(set_difference_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((set_difference @ A) @ C)) @ ((set_difference @ B) @ C)))))))))))))).
thf(set_difference_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ ((set_difference @ C) @ A)) @ ((set_difference @ C) @ B)))))))))))))).
thf(singleton_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((qmltpeq @ A) @ B)) @ ((qmltpeq @ (singleton @ A)) @ (singleton @ B))))))))))).
thf(empty_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ (empty @ A))) @ (empty @ B)))))))))).
thf(in_substitution_1, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((in @ A) @ C))) @ ((in @ B) @ C))))))))))))).
thf(in_substitution_2, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mimplies @ ((mand @ ((qmltpeq @ A) @ B)) @ ((in @ C) @ A))) @ ((in @ C) @ B))))))))))))).
thf(antisymmetry_r2_hidden, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mimplies @ ((in @ A) @ B)) @ (mnot @ ((in @ B) @ A))))))))))).
thf(d1_tarski, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: (((mequiv @ ((qmltpeq @ B) @ (singleton @ A))) @ (mforall_di @ (^ [C:$i]: (((mequiv @ ((in @ C) @ B)) @ ((qmltpeq @ C) @ A)))))))))))))).
thf(d4_xboole_0, axiom, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mequiv @ ((qmltpeq @ C) @ ((set_difference @ A) @ B))) @ (mforall_di @ (^ [D:$i]: (((mequiv @ ((in @ D) @ C)) @ ((mand @ ((in @ D) @ A)) @ (mnot @ ((in @ D) @ B))))))))))))))))))).
thf(rc1_xboole_0, axiom, (mlocal @ (mexists_di @ (^ [A:$i]: ((empty @ A)))))).
thf(rc2_xboole_0, axiom, (mlocal @ (mexists_di @ (^ [A:$i]: ((mnot @ (empty @ A))))))).
thf(t64_zfmisc_1, conjecture, (mlocal @ (mforall_di @ (^ [A:$i]: ((mforall_di @ (^ [B:$i]: ((mforall_di @ (^ [C:$i]: (((mequiv @ ((in @ A) @ ((set_difference @ B) @ (singleton @ C)))) @ ((mand @ ((in @ A) @ B)) @ (mnot @ ((qmltpeq @ A) @ C))))))))))))))).
