%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:22:07 CEST 2022 using command 'downgrade(tff)'.
tff(u_type, type, u: $i).
tff(one_type, type, one: $i).
tff(number_type, type, number: (($i * $i) > $o)).
tff(string_type, type, string: ($i > $o)).
tff(in_type, type, in: (($i * $i * $i) > $o)).
tff(do_type, type, do: (($i * $i * $i) > $o)).
tff(entry_box_type, type, entry_box: ($i > $o)).
tff(userid_type, type, userid: (($i * $i) > $o)).
tff(ax1, axiom, {$box}((? [I:$i]: ({$box}((userid(u,I) & string(I))))))).
tff(ax2, axiom, (? [B:$i]: ({$box}((entry_box(B) & number(B,one)))))).
tff(ax3, axiom, {$box}((! [S:$i,I:$i,B:$i]: (((string(I) & entry_box(B)) => (? [A:$i]: ({$box}((! [S2:$i]: ((do(S,A,S2) => in(I,B,S2)))))))))))).
tff(con, conjecture, {$box}((? [I:$i,B:$i,A:$i,S:$i]: (({$box}((userid(u,I) & (entry_box(B) & number(B,one)))) & {$box}((! [S2:$i]: ((do(S,A,S2) => in(I,B,S2)))))))))).
