%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GLC354+1 [QMLTP]

% Status   : Unknown 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   29 (  11 unt;  14 typ;  10 def)
%            Number of atoms       :  160 (  10 equ;   0 cnn)
%            Maximal formula atoms :   81 (  10 avg)
%            Number of connectives :  220 (   1   ~;   1   |;   2   &; 213   @)
%                                         (   1 <=>;   2  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   36 (   7 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :   60 (  60   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   14 (  13 usr;   1 con; 0-3 aty)
%            Number of variables   :   50 (  45   ^   3   !;   2   ?;  50   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $constant,
%            $modalities == $modal_system_T].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] : ( A @ X @ W ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] : ( A @ X @ W ) ) ) ).

thf(meets_decl,type,
    meets: $i > $i > mworld > $o ).

thf(m1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [P: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Q: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [R: $i] :
                        ( mbox
                        @ ( mforall_di
                          @ ^ [S: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( meets @ P @ Q ) ) @ ( mand @ ( mbox @ ( meets @ P @ S ) ) @ ( mbox @ ( meets @ R @ Q ) ) ) ) @ ( mbox @ ( meets @ R @ S ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(m2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [P: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Q: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [R: $i] :
                        ( mbox
                        @ ( mforall_di
                          @ ^ [S: $i] :
                              ( mbox
                              @ ( mimplies @ ( mand @ ( mbox @ ( meets @ P @ Q ) ) @ ( mbox @ ( meets @ R @ S ) ) )
                                @ ( mbox
                                  @ ( mnot
                                    @ ( mand
                                      @ ( mbox
                                        @ ( mimplies
                                          @ ( mbox
                                            @ ( mnot
                                              @ ( mand
                                                @ ( mbox
                                                  @ ( mimplies @ ( mbox @ ( meets @ P @ S ) )
                                                    @ ( mexists_di
                                                      @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ P @ T ) ) @ ( mbox @ ( meets @ T @ S ) ) ) ) ) )
                                                @ ( mbox
                                                  @ ( mimplies
                                                    @ ( mexists_di
                                                      @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ P @ T ) ) @ ( mbox @ ( meets @ T @ S ) ) ) )
                                                    @ ( mbox @ ( meets @ P @ S ) ) ) ) ) ) )
                                          @ ( mexists_di
                                            @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ R @ T ) ) @ ( mbox @ ( meets @ T @ Q ) ) ) ) ) )
                                      @ ( mbox
                                        @ ( mimplies
                                          @ ( mexists_di
                                            @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ R @ T ) ) @ ( mbox @ ( meets @ T @ Q ) ) ) )
                                          @ ( mbox
                                            @ ( mnot
                                              @ ( mand
                                                @ ( mbox
                                                  @ ( mimplies @ ( mbox @ ( meets @ P @ S ) )
                                                    @ ( mexists_di
                                                      @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ P @ T ) ) @ ( mbox @ ( meets @ T @ S ) ) ) ) ) )
                                                @ ( mbox
                                                  @ ( mimplies
                                                    @ ( mexists_di
                                                      @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ P @ T ) ) @ ( mbox @ ( meets @ T @ S ) ) ) )
                                                    @ ( mbox @ ( meets @ P @ S ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(m3,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [P: $i] :
            ( mexists_di
            @ ^ [Q: $i] :
                ( mexists_di
                @ ^ [R: $i] : ( mand @ ( mbox @ ( meets @ Q @ P ) ) @ ( mbox @ ( meets @ P @ R ) ) ) ) ) ) ) ) ).

thf(not_m5,axiom,
    ( mlocal
    @ ( mbox
      @ ( mnot
        @ ( mbox
          @ ( mforall_di
            @ ^ [P: $i] :
                ( mbox
                @ ( mforall_di
                  @ ^ [Q: $i] :
                      ( mbox
                      @ ( mimplies @ ( mbox @ ( meets @ P @ Q ) )
                        @ ( mexists_di
                          @ ^ [R: $i] :
                              ( mexists_di
                              @ ^ [S: $i] :
                                  ( mexists_di
                                  @ ^ [T: $i] : ( mand @ ( mbox @ ( meets @ R @ P ) ) @ ( mand @ ( mbox @ ( meets @ Q @ S ) ) @ ( mand @ ( mbox @ ( meets @ R @ T ) ) @ ( mbox @ ( meets @ T @ S ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
