%%% This output was generated by embedproblem, version 1.7.1 (library version 1.3).
%%% Generated on Thu Apr 28 13:32:02 EDT 2022
%%% using 'modal' embedding, version 1.5.2.
%%% Logic specification used:
%%% tff(s5_varying_rigid, logic, ($modal) == ([($constants) == ($rigid),($quantification) == ($varying),($modalities) == ($modal_system_S5)])).

thf(mworld, type, mworld: $tType).
thf(mrel_type, type, mrel: (mworld > (mworld > $o))).
thf(mactual_type, type, mactual: mworld).
thf(mlocal_type, type, mlocal: ((mworld > $o) > $o)).
thf(mlocal_def, definition, (mlocal = (^ [Phi:(mworld > $o)]: ((Phi @ mactual))))).
thf(mnot_type, type, mnot: ((mworld > $o) > (mworld > $o))).
thf(mand_type, type, mand: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mor_type, type, mor: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mimplies_type, type, mimplies: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mequiv_type, type, mequiv: ((mworld > $o) > ((mworld > $o) > (mworld > $o)))).
thf(mnot_def, definition, (mnot = (^ [A:(mworld > $o),W:mworld]: ((~ ((A @ W))))))).
thf(mand_def, definition, (mand = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) & (B @ W)))))).
thf(mor_def, definition, (mor = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) | (B @ W)))))).
thf(mimplies_def, definition, (mimplies = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) => (B @ W)))))).
thf(mequiv_def, definition, (mequiv = (^ [A:(mworld > $o),B:(mworld > $o),W:mworld]: (((A @ W) <=> (B @ W)))))).
thf(mbox_type, type, mbox: ((mworld > $o) > (mworld > $o))).
thf(mbox_def, definition, (mbox = (^ [Phi:(mworld > $o),W:mworld]: ((! [V:mworld]: ((((mrel @ W) @ V) => (Phi @ V)))))))).
thf(mdia_type, type, mdia: ((mworld > $o) > (mworld > $o))).
thf(mdia_def, definition, (mdia = (^ [Phi:(mworld > $o),W:mworld]: ((? [V:mworld]: ((((mrel @ W) @ V) & (Phi @ V)))))))).
thf(mrel_reflexive, axiom, (! [W:mworld]: (((mrel @ W) @ W)))).
thf(mrel_euclidean, axiom, (! [W:mworld,V:mworld,U:mworld]: (((((mrel @ W) @ U) & ((mrel @ W) @ V)) => ((mrel @ U) @ V))))).
thf(eiw_di_type, type, eiw_di: ($i > (mworld > $o))).
thf(eiw_di_nonempty, axiom, (! [W:mworld]: ((? [X:$i]: (((eiw_di @ X) @ W)))))).
thf(mforall_di_type, type, mforall_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mforall_di_def, definition, (mforall_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((! [X:$i]: ((((eiw_di @ X) @ W) => ((A @ X) @ W)))))))).
thf(mexists_di_type, type, mexists_di: (($i > (mworld > $o)) > (mworld > $o))).
thf(mexists_di_def, definition, (mexists_di = (^ [A:($i > (mworld > $o)),W:mworld]: ((? [X:$i]: ((((eiw_di @ X) @ W) & ((A @ X) @ W)))))))).
thf(a_truth_decl, type, a_truth: ($i > (mworld > $o))).
thf(not_decl, type, not: ($i > $i)).
thf(implies_decl, type, implies: ($i > ($i > $i))).
thf(thm147, conjecture, (mlocal @ (mbox @ (mnot @ ((mand @ (mbox @ (mforall_di @ (^ [P:$i]: ((mbox @ (mforall_di @ (^ [Q:$i]: (((mor @ (mbox @ (mnot @ (mbox @ (a_truth @ ((implies @ P) @ Q)))))) @ ((mor @ (mbox @ (mnot @ (mbox @ (a_truth @ P))))) @ (mbox @ (a_truth @ Q))))))))))))) @ ((mand @ (mbox @ (mforall_di @ (^ [P:$i]: ((mbox @ (mforall_di @ (^ [Q:$i]: ((mbox @ (a_truth @ ((implies @ P) @ ((implies @ Q) @ P))))))))))))) @ ((mand @ (mbox @ (mforall_di @ (^ [P:$i]: ((mbox @ (mforall_di @ (^ [Q:$i]: ((mbox @ (mforall_di @ (^ [R:$i]: ((mbox @ (a_truth @ ((implies @ ((implies @ P) @ ((implies @ Q) @ R))) @ ((implies @ ((implies @ P) @ Q)) @ ((implies @ P) @ R)))))))))))))))))) @ ((mand @ (mbox @ (mforall_di @ (^ [P:$i]: ((mbox @ (mforall_di @ (^ [Q:$i]: ((mbox @ (a_truth @ ((implies @ ((implies @ (not @ P)) @ (not @ Q))) @ ((implies @ Q) @ P))))))))))))) @ (mexists_di @ (^ [A:$i]: ((mbox @ (mnot @ (mbox @ (a_truth @ ((implies @ A) @ A)))))))))))))))).
