tff(s5_cumulative_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $cumulative,
     $modalities == $modal_system_S5U
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:14 CEST 2022 using command 'downgrade(tff)'.
tff(f_decl, type, f: ($i > $o)).
tff(g_decl, type, g: ($i > $o)).
tff(kalish239, conjecture, {$box}((({$box}((! [X:$i]: ({$box}(f(X))))) & (? [Y:$i]: ({$box}(g(Y))))) => (? [Z:$i]: (({$box}(f(Z)) & {$box}(g(Z)))))))).
