%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : TBA
% Source   : [TPTP]
% Names    :

% Status   : Theorem
% Rating   : ? b8.1.0
% Syntax   : Number of formulae    :   29 (  14 unt;  14 typ;  14 def)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S5].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(mrel_euclidean,axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ W @ U )
        & ( mrel @ W @ V ) )
     => ( mrel @ U @ V ) ) ).

thf(eiw_di_type,type,
    eiw_di: $i > mworld > $o ).

thf(eiw_di_nonempty,axiom,
    ! [W: mworld] :
    ? [X: $i] : ( eiw_di @ X @ W ) ).

thf(eiw_di_decr,axiom,
    ! [W: mworld,V: mworld,X: $i] :
      ( ( ( eiw_di @ X @ W )
        & ( mrel @ V @ W ) )
     => ( eiw_di @ X @ V ) ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] :
          ( ( eiw_di @ X @ W )
         => ( A @ X @ W ) ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] :
          ( ( eiw_di @ X @ W )
          & ( A @ X @ W ) ) ) ) ).

thf(chevy_decl,type,
    chevy: $i > mworld > $o ).

thf(dirty_decl,type,
    dirty: $i > mworld > $o ).

thf(barrel_decl,type,
    barrel: $i > $i > mworld > $o ).

thf(hollywood_decl,type,
    hollywood: $i > mworld > $o ).

thf(city_decl,type,
    city: $i > mworld > $o ).

thf(in_decl,type,
    in: $i > $i > mworld > $o ).

thf(old_decl,type,
    old: $i > mworld > $o ).

thf(down_decl,type,
    down: $i > $i > mworld > $o ).

thf(way_decl,type,
    way: $i > mworld > $o ).

thf(white_decl,type,
    white: $i > mworld > $o ).

thf(car_decl,type,
    car: $i > mworld > $o ).

thf(street_decl,type,
    street: $i > mworld > $o ).

thf(event_decl,type,
    event: $i > mworld > $o ).

thf(lonely_decl,type,
    lonely: $i > mworld > $o ).

thf(co1,conjecture,
    ( mlocal
    @ ( mand
      @ ( mbox
        @ ( mimplies
          @ ( mexists_di
            @ ^ [U: $i] :
                ( mexists_di
                @ ^ [V: $i] :
                    ( mexists_di
                    @ ^ [W: $i] :
                        ( mexists_di
                        @ ^ [X: $i] : ( mand @ ( mbox @ ( hollywood @ U ) ) @ ( mand @ ( mbox @ ( city @ U ) ) @ ( mand @ ( mbox @ ( event @ V ) ) @ ( mand @ ( mbox @ ( street @ W ) ) @ ( mand @ ( mbox @ ( way @ W ) ) @ ( mand @ ( mbox @ ( lonely @ W ) ) @ ( mand @ ( mbox @ ( chevy @ X ) ) @ ( mand @ ( mbox @ ( car @ X ) ) @ ( mand @ ( mbox @ ( white @ X ) ) @ ( mand @ ( mbox @ ( dirty @ X ) ) @ ( mand @ ( mbox @ ( old @ X ) ) @ ( mand @ ( mbox @ ( barrel @ V @ X ) ) @ ( mand @ ( mbox @ ( down @ V @ W ) ) @ ( mbox @ ( in @ V @ U ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
          @ ( mexists_di
            @ ^ [Y: $i] :
                ( mexists_di
                @ ^ [Z: $i] :
                    ( mexists_di
                    @ ^ [X1: $i] :
                        ( mexists_di
                        @ ^ [X2: $i] : ( mand @ ( mbox @ ( hollywood @ Y ) ) @ ( mand @ ( mbox @ ( city @ Y ) ) @ ( mand @ ( mbox @ ( event @ Z ) ) @ ( mand @ ( mbox @ ( chevy @ X1 ) ) @ ( mand @ ( mbox @ ( car @ X1 ) ) @ ( mand @ ( mbox @ ( white @ X1 ) ) @ ( mand @ ( mbox @ ( dirty @ X1 ) ) @ ( mand @ ( mbox @ ( old @ X1 ) ) @ ( mand @ ( mbox @ ( street @ X2 ) ) @ ( mand @ ( mbox @ ( way @ X2 ) ) @ ( mand @ ( mbox @ ( lonely @ X2 ) ) @ ( mand @ ( mbox @ ( barrel @ Z @ X1 ) ) @ ( mand @ ( mbox @ ( down @ Z @ X2 ) ) @ ( mbox @ ( in @ Z @ Y ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
      @ ( mbox
        @ ( mimplies
          @ ( mexists_di
            @ ^ [X3: $i] :
                ( mexists_di
                @ ^ [X4: $i] :
                    ( mexists_di
                    @ ^ [X5: $i] :
                        ( mexists_di
                        @ ^ [X6: $i] : ( mand @ ( mbox @ ( hollywood @ X3 ) ) @ ( mand @ ( mbox @ ( city @ X3 ) ) @ ( mand @ ( mbox @ ( event @ X4 ) ) @ ( mand @ ( mbox @ ( chevy @ X5 ) ) @ ( mand @ ( mbox @ ( car @ X5 ) ) @ ( mand @ ( mbox @ ( white @ X5 ) ) @ ( mand @ ( mbox @ ( dirty @ X5 ) ) @ ( mand @ ( mbox @ ( old @ X5 ) ) @ ( mand @ ( mbox @ ( street @ X6 ) ) @ ( mand @ ( mbox @ ( way @ X6 ) ) @ ( mand @ ( mbox @ ( lonely @ X6 ) ) @ ( mand @ ( mbox @ ( barrel @ X4 @ X5 ) ) @ ( mand @ ( mbox @ ( down @ X4 @ X6 ) ) @ ( mbox @ ( in @ X4 @ X3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
          @ ( mexists_di
            @ ^ [X7: $i] :
                ( mexists_di
                @ ^ [X8: $i] :
                    ( mexists_di
                    @ ^ [X9: $i] :
                        ( mexists_di
                        @ ^ [X10: $i] : ( mand @ ( mbox @ ( hollywood @ X7 ) ) @ ( mand @ ( mbox @ ( city @ X7 ) ) @ ( mand @ ( mbox @ ( event @ X8 ) ) @ ( mand @ ( mbox @ ( street @ X9 ) ) @ ( mand @ ( mbox @ ( way @ X9 ) ) @ ( mand @ ( mbox @ ( lonely @ X9 ) ) @ ( mand @ ( mbox @ ( chevy @ X10 ) ) @ ( mand @ ( mbox @ ( car @ X10 ) ) @ ( mand @ ( mbox @ ( white @ X10 ) ) @ ( mand @ ( mbox @ ( dirty @ X10 ) ) @ ( mand @ ( mbox @ ( old @ X10 ) ) @ ( mand @ ( mbox @ ( barrel @ X8 @ X10 ) ) @ ( mand @ ( mbox @ ( down @ X8 @ X9 ) ) @ ( mbox @ ( in @ X8 @ X7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
