%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : TBA
% Source   : [TPTP]
% Names    :

% Status   : Theorem
% Rating   : ? b8.1.0
% Syntax   : Number of formulae    :   29 (  14 unt;  14 typ;  14 def)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_T].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(eiw_di_type,type,
    eiw_di: $i > mworld > $o ).

thf(eiw_di_nonempty,axiom,
    ! [W: mworld] :
    ? [X: $i] : ( eiw_di @ X @ W ) ).

thf(eiw_di_decr,axiom,
    ! [W: mworld,V: mworld,X: $i] :
      ( ( ( eiw_di @ X @ W )
        & ( mrel @ V @ W ) )
     => ( eiw_di @ X @ V ) ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] :
          ( ( eiw_di @ X @ W )
         => ( A @ X @ W ) ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] :
          ( ( eiw_di @ X @ W )
          & ( A @ X @ W ) ) ) ) ).

thf(chevy_decl,type,
    chevy: $i > mworld > $o ).

thf(hollywood_decl,type,
    hollywood: $i > mworld > $o ).

thf(woman_decl,type,
    woman: $i > mworld > $o ).

thf(city_decl,type,
    city: $i > mworld > $o ).

thf(down_decl,type,
    down: $i > $i > mworld > $o ).

thf(vehicle_decl,type,
    vehicle: $i > mworld > $o ).

thf(artifact_decl,type,
    artifact: $i > mworld > $o ).

thf(white_decl,type,
    white: $i > mworld > $o ).

thf(car_decl,type,
    car: $i > mworld > $o ).

thf(street_decl,type,
    street: $i > mworld > $o ).

thf(of_decl,type,
    of: $i > $i > mworld > $o ).

thf(proposition_decl,type,
    proposition: $i > mworld > $o ).

thf(have_decl,type,
    have: $i > $i > $i > mworld > $o ).

thf(man_decl,type,
    man: $i > mworld > $o ).

thf(event_decl,type,
    event: $i > mworld > $o ).

thf(female_decl,type,
    female: $i > mworld > $o ).

thf(lonely_decl,type,
    lonely: $i > mworld > $o ).

thf(human_decl,type,
    human: $i > mworld > $o ).

thf(dirty_decl,type,
    dirty: $i > mworld > $o ).

thf(owner_decl,type,
    owner: $i > mworld > $o ).

thf(barrel_decl,type,
    barrel: $i > $i > mworld > $o ).

thf(new_decl,type,
    new: $i > mworld > $o ).

thf(partof_decl,type,
    partof: $i > $i > mworld > $o ).

thf(drs_decl,type,
    drs: $i > mworld > $o ).

thf(in_decl,type,
    in: $i > $i > mworld > $o ).

thf(old_decl,type,
    old: $i > mworld > $o ).

thf(abstraction_decl,type,
    abstraction: $i > mworld > $o ).

thf(transport_decl,type,
    transport: $i > mworld > $o ).

thf(instrumentality_decl,type,
    instrumentality: $i > mworld > $o ).

thf(way_decl,type,
    way: $i > mworld > $o ).

thf(qmltpeq_decl,type,
    qmltpeq: $i > $i > mworld > $o ).

thf(eventuality_decl,type,
    eventuality: $i > mworld > $o ).

thf(location_decl,type,
    location: $i > mworld > $o ).

thf(nonhuman_decl,type,
    nonhuman: $i > mworld > $o ).

thf(entity_decl,type,
    entity: $i > mworld > $o ).

thf(male_decl,type,
    male: $i > mworld > $o ).

thf(object_decl,type,
    object: $i > mworld > $o ).

thf(reflexivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] : ( mbox @ ( qmltpeq @ X @ X ) ) ) ) ) ).

thf(symmetry,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ X ) ) ) ) ) ) ) ) ) ).

thf(transitivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [Z: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ Z ) ) ) @ ( mbox @ ( qmltpeq @ X @ Z ) ) ) ) ) ) ) ) ) ) ) ).

thf(abstraction_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( abstraction @ A ) ) ) @ ( mbox @ ( abstraction @ B ) ) ) ) ) ) ) ) ) ).

thf(artifact_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( artifact @ A ) ) ) @ ( mbox @ ( artifact @ B ) ) ) ) ) ) ) ) ) ).

thf(barrel_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( barrel @ A @ C ) ) ) @ ( mbox @ ( barrel @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(barrel_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( barrel @ C @ A ) ) ) @ ( mbox @ ( barrel @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(car_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( car @ A ) ) ) @ ( mbox @ ( car @ B ) ) ) ) ) ) ) ) ) ).

thf(chevy_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( chevy @ A ) ) ) @ ( mbox @ ( chevy @ B ) ) ) ) ) ) ) ) ) ).

thf(city_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( city @ A ) ) ) @ ( mbox @ ( city @ B ) ) ) ) ) ) ) ) ) ).

thf(dirty_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( dirty @ A ) ) ) @ ( mbox @ ( dirty @ B ) ) ) ) ) ) ) ) ) ).

thf(down_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( down @ A @ C ) ) ) @ ( mbox @ ( down @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(down_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( down @ C @ A ) ) ) @ ( mbox @ ( down @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(drs_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( drs @ A ) ) ) @ ( mbox @ ( drs @ B ) ) ) ) ) ) ) ) ) ).

thf(entity_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( entity @ A ) ) ) @ ( mbox @ ( entity @ B ) ) ) ) ) ) ) ) ) ).

thf(event_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( event @ A ) ) ) @ ( mbox @ ( event @ B ) ) ) ) ) ) ) ) ) ).

thf(eventuality_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( eventuality @ A ) ) ) @ ( mbox @ ( eventuality @ B ) ) ) ) ) ) ) ) ) ).

thf(female_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( female @ A ) ) ) @ ( mbox @ ( female @ B ) ) ) ) ) ) ) ) ) ).

thf(have_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] :
                        ( mbox
                        @ ( mforall_di
                          @ ^ [D: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( have @ A @ C @ D ) ) ) @ ( mbox @ ( have @ B @ C @ D ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(have_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] :
                        ( mbox
                        @ ( mforall_di
                          @ ^ [D: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( have @ C @ A @ D ) ) ) @ ( mbox @ ( have @ C @ B @ D ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(have_substitution_3,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] :
                        ( mbox
                        @ ( mforall_di
                          @ ^ [D: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( have @ C @ D @ A ) ) ) @ ( mbox @ ( have @ C @ D @ B ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(hollywood_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( hollywood @ A ) ) ) @ ( mbox @ ( hollywood @ B ) ) ) ) ) ) ) ) ) ).

thf(human_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( human @ A ) ) ) @ ( mbox @ ( human @ B ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ A @ C ) ) ) @ ( mbox @ ( in @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ C @ A ) ) ) @ ( mbox @ ( in @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(instrumentality_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( instrumentality @ A ) ) ) @ ( mbox @ ( instrumentality @ B ) ) ) ) ) ) ) ) ) ).

thf(location_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( location @ A ) ) ) @ ( mbox @ ( location @ B ) ) ) ) ) ) ) ) ) ).

thf(lonely_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( lonely @ A ) ) ) @ ( mbox @ ( lonely @ B ) ) ) ) ) ) ) ) ) ).

thf(male_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( male @ A ) ) ) @ ( mbox @ ( male @ B ) ) ) ) ) ) ) ) ) ).

thf(man_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( man @ A ) ) ) @ ( mbox @ ( man @ B ) ) ) ) ) ) ) ) ) ).

thf(new_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( new @ A ) ) ) @ ( mbox @ ( new @ B ) ) ) ) ) ) ) ) ) ).

thf(nonhuman_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( nonhuman @ A ) ) ) @ ( mbox @ ( nonhuman @ B ) ) ) ) ) ) ) ) ) ).

thf(object_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( object @ A ) ) ) @ ( mbox @ ( object @ B ) ) ) ) ) ) ) ) ) ).

thf(of_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( of @ A @ C ) ) ) @ ( mbox @ ( of @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(of_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( of @ C @ A ) ) ) @ ( mbox @ ( of @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(old_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( old @ A ) ) ) @ ( mbox @ ( old @ B ) ) ) ) ) ) ) ) ) ).

thf(owner_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( owner @ A ) ) ) @ ( mbox @ ( owner @ B ) ) ) ) ) ) ) ) ) ).

thf(partof_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( partof @ A @ C ) ) ) @ ( mbox @ ( partof @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(partof_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( partof @ C @ A ) ) ) @ ( mbox @ ( partof @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(proposition_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( proposition @ A ) ) ) @ ( mbox @ ( proposition @ B ) ) ) ) ) ) ) ) ) ).

thf(street_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( street @ A ) ) ) @ ( mbox @ ( street @ B ) ) ) ) ) ) ) ) ) ).

thf(transport_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( transport @ A ) ) ) @ ( mbox @ ( transport @ B ) ) ) ) ) ) ) ) ) ).

thf(vehicle_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( vehicle @ A ) ) ) @ ( mbox @ ( vehicle @ B ) ) ) ) ) ) ) ) ) ).

thf(way_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( way @ A ) ) ) @ ( mbox @ ( way @ B ) ) ) ) ) ) ) ) ) ).

thf(white_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( white @ A ) ) ) @ ( mbox @ ( white @ B ) ) ) ) ) ) ) ) ) ).

thf(woman_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( woman @ A ) ) ) @ ( mbox @ ( woman @ B ) ) ) ) ) ) ) ) ) ).

thf(ax1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( chevy @ U ) ) @ ( mbox @ ( car @ U ) ) ) ) ) ) ) ).

thf(ax2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( car @ U ) ) @ ( mbox @ ( vehicle @ U ) ) ) ) ) ) ) ).

thf(ax3,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( vehicle @ U ) ) @ ( mbox @ ( transport @ U ) ) ) ) ) ) ) ).

thf(ax4,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( transport @ U ) ) @ ( mbox @ ( instrumentality @ U ) ) ) ) ) ) ) ).

thf(ax5,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( instrumentality @ U ) ) @ ( mbox @ ( artifact @ U ) ) ) ) ) ) ) ).

thf(ax6,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( instrumentality @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( way @ U ) ) ) ) ) ) ) ) ) ).

thf(ax7,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( street @ U ) ) @ ( mbox @ ( way @ U ) ) ) ) ) ) ) ).

thf(ax8,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( way @ U ) ) @ ( mbox @ ( artifact @ U ) ) ) ) ) ) ) ).

thf(ax9,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( artifact @ U ) ) @ ( mbox @ ( object @ U ) ) ) ) ) ) ) ).

thf(ax10,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( artifact @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( location @ U ) ) ) ) ) ) ) ) ) ).

thf(ax11,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( event @ U ) ) @ ( mbox @ ( eventuality @ U ) ) ) ) ) ) ) ).

thf(ax12,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( hollywood @ U ) ) @ ( mbox @ ( city @ U ) ) ) ) ) ) ) ).

thf(ax13,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( city @ U ) ) @ ( mbox @ ( location @ U ) ) ) ) ) ) ) ).

thf(ax14,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( location @ U ) ) @ ( mbox @ ( object @ U ) ) ) ) ) ) ) ).

thf(ax15,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( object @ U ) ) @ ( mbox @ ( entity @ U ) ) ) ) ) ) ) ).

thf(ax16,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( old @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( new @ U ) ) ) ) ) ) ) ) ) ).

thf(ax17,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( eventuality @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( entity @ U ) ) ) ) ) ) ) ) ) ).

thf(ax18,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( abstraction @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( entity @ U ) ) ) ) ) ) ) ) ) ).

thf(ax19,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( abstraction @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( eventuality @ U ) ) ) ) ) ) ) ) ) ).

thf(ax20,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( male @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( female @ U ) ) ) ) ) ) ) ) ) ).

thf(ax21,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( man @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( woman @ U ) ) ) ) ) ) ) ) ) ).

thf(ax22,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( man @ U ) ) @ ( mbox @ ( male @ U ) ) ) ) ) ) ) ).

thf(ax23,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( male @ U ) ) @ ( mbox @ ( human @ U ) ) ) ) ) ) ) ).

thf(ax24,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( female @ U ) ) @ ( mbox @ ( human @ U ) ) ) ) ) ) ) ).

thf(ax25,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( woman @ U ) ) @ ( mbox @ ( female @ U ) ) ) ) ) ) ) ).

thf(ax26,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( drs @ U ) ) @ ( mbox @ ( proposition @ U ) ) ) ) @ ( mbox @ ( mimplies @ ( mbox @ ( proposition @ U ) ) @ ( mbox @ ( drs @ U ) ) ) ) ) ) ) ) ).

thf(ax27,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( nonhuman @ U ) ) @ ( mbox @ ( entity @ U ) ) ) ) ) ) ) ).

thf(ax28,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] : ( mbox @ ( mimplies @ ( mbox @ ( human @ U ) ) @ ( mbox @ ( mnot @ ( mbox @ ( nonhuman @ U ) ) ) ) ) ) ) ) ) ).

thf(ax29,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [V: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [W: $i] : ( mand @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( have @ U @ V @ W ) ) @ ( mbox @ ( human @ V ) ) ) @ ( mand @ ( mbox @ ( owner @ V ) ) @ ( mbox @ ( of @ V @ W ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( owner @ V ) ) @ ( mbox @ ( of @ V @ W ) ) ) @ ( mand @ ( mbox @ ( have @ U @ V @ W ) ) @ ( mbox @ ( human @ V ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(ax30,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [V: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [W: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( have @ U @ V @ W ) ) @ ( mand @ ( mbox @ ( nonhuman @ V ) ) @ ( mbox @ ( nonhuman @ W ) ) ) ) @ ( mbox @ ( partof @ W @ V ) ) ) ) ) ) ) ) ) ) ) ).

thf(ax31,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [V: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [W: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( event @ U ) ) @ ( mbox @ ( have @ U @ V @ W ) ) ) @ ( mbox @ ( of @ V @ W ) ) ) ) ) ) ) ) ) ) ) ).

thf(ax32,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [V: $i] :
                  ( mbox
                  @ ( mimplies @ ( mbox @ ( of @ V @ U ) )
                    @ ( mexists_di
                      @ ^ [W: $i] : ( mand @ ( mbox @ ( event @ W ) ) @ ( mbox @ ( have @ W @ U @ V ) ) ) ) ) ) ) ) ) ) ) ).

thf(ax33,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [U: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [V: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [W: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( partof @ U @ V ) ) @ ( mbox @ ( partof @ U @ W ) ) ) @ ( mbox @ ( qmltpeq @ V @ W ) ) ) ) ) ) ) ) ) ) ) ).

thf(co1,conjecture,
    ( mlocal
    @ ( mbox
      @ ( mnot
        @ ( mexists_di
          @ ^ [U: $i] :
              ( mexists_di
              @ ^ [V: $i] :
                  ( mexists_di
                  @ ^ [W: $i] :
                      ( mexists_di
                      @ ^ [X: $i] : ( mand @ ( mbox @ ( hollywood @ U ) ) @ ( mand @ ( mbox @ ( city @ U ) ) @ ( mand @ ( mbox @ ( event @ V ) ) @ ( mand @ ( mbox @ ( chevy @ W ) ) @ ( mand @ ( mbox @ ( car @ W ) ) @ ( mand @ ( mbox @ ( white @ W ) ) @ ( mand @ ( mbox @ ( dirty @ W ) ) @ ( mand @ ( mbox @ ( old @ W ) ) @ ( mand @ ( mbox @ ( street @ X ) ) @ ( mand @ ( mbox @ ( way @ X ) ) @ ( mand @ ( mbox @ ( lonely @ X ) ) @ ( mand @ ( mbox @ ( barrel @ V @ W ) ) @ ( mand @ ( mbox @ ( down @ V @ X ) ) @ ( mbox @ ( in @ V @ U ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
