%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : Goedel translation of NLP004+1 (from TPTP-v5.0.0)
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GNL004+1 [QMLTP]

% Status   : Theorem 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   76 (  12 unt;  35 typ;  10 def)
%            Number of atoms       :  820 (  10 equ;   0 cnn)
%            Maximal formula atoms :  422 (  20 avg)
%            Number of connectives : 1086 (   1   ~;   1   |;   5   &;1073   @)
%                                         (   1 <=>;   5  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   61 (  13 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :  105 ( 105   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   35 (  34 usr;   1 con; 0-3 aty)
%            Number of variables   :  134 ( 121   ^  10   !;   3   ?; 134   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $decreasing,
%            $modalities == $modal_system_S5].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(mrel_euclidean,axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ W @ U )
        & ( mrel @ W @ V ) )
     => ( mrel @ U @ V ) ) ).

thf(eiw_di_type,type,
    eiw_di: $i > mworld > $o ).

thf(eiw_di_nonempty,axiom,
    ! [W: mworld] :
    ? [X: $i] : ( eiw_di @ X @ W ) ).

thf(eiw_di_decr,axiom,
    ! [W: mworld,V: mworld,X: $i] :
      ( ( ( eiw_di @ X @ W )
        & ( mrel @ V @ W ) )
     => ( eiw_di @ X @ V ) ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] :
          ( ( eiw_di @ X @ W )
         => ( A @ X @ W ) ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] :
          ( ( eiw_di @ X @ W )
          & ( A @ X @ W ) ) ) ) ).

thf(chevy_decl,type,
    chevy: $i > mworld > $o ).

thf(dirty_decl,type,
    dirty: $i > mworld > $o ).

thf(barrel_decl,type,
    barrel: $i > $i > mworld > $o ).

thf(hollywood_decl,type,
    hollywood: $i > mworld > $o ).

thf(city_decl,type,
    city: $i > mworld > $o ).

thf(in_decl,type,
    in: $i > $i > mworld > $o ).

thf(young_decl,type,
    young: $i > mworld > $o ).

thf(old_decl,type,
    old: $i > mworld > $o ).

thf(down_decl,type,
    down: $i > $i > mworld > $o ).

thf(way_decl,type,
    way: $i > mworld > $o ).

thf(qmltpeq_decl,type,
    qmltpeq: $i > $i > mworld > $o ).

thf(seat_decl,type,
    seat: $i > mworld > $o ).

thf(white_decl,type,
    white: $i > mworld > $o ).

thf(car_decl,type,
    car: $i > mworld > $o ).

thf(furniture_decl,type,
    furniture: $i > mworld > $o ).

thf(street_decl,type,
    street: $i > mworld > $o ).

thf(fellow_decl,type,
    fellow: $i > mworld > $o ).

thf(front_decl,type,
    front: $i > mworld > $o ).

thf(man_decl,type,
    man: $i > mworld > $o ).

thf(event_decl,type,
    event: $i > mworld > $o ).

thf(lonely_decl,type,
    lonely: $i > mworld > $o ).

thf(reflexivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] : ( mbox @ ( qmltpeq @ X @ X ) ) ) ) ) ).

thf(symmetry,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ X ) ) ) ) ) ) ) ) ) ).

thf(transitivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [Z: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ Z ) ) ) @ ( mbox @ ( qmltpeq @ X @ Z ) ) ) ) ) ) ) ) ) ) ) ).

thf(barrel_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( barrel @ A @ C ) ) ) @ ( mbox @ ( barrel @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(barrel_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( barrel @ C @ A ) ) ) @ ( mbox @ ( barrel @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(car_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( car @ A ) ) ) @ ( mbox @ ( car @ B ) ) ) ) ) ) ) ) ) ).

thf(chevy_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( chevy @ A ) ) ) @ ( mbox @ ( chevy @ B ) ) ) ) ) ) ) ) ) ).

thf(city_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( city @ A ) ) ) @ ( mbox @ ( city @ B ) ) ) ) ) ) ) ) ) ).

thf(dirty_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( dirty @ A ) ) ) @ ( mbox @ ( dirty @ B ) ) ) ) ) ) ) ) ) ).

thf(down_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( down @ A @ C ) ) ) @ ( mbox @ ( down @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(down_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( down @ C @ A ) ) ) @ ( mbox @ ( down @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(event_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( event @ A ) ) ) @ ( mbox @ ( event @ B ) ) ) ) ) ) ) ) ) ).

thf(fellow_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( fellow @ A ) ) ) @ ( mbox @ ( fellow @ B ) ) ) ) ) ) ) ) ) ).

thf(front_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( front @ A ) ) ) @ ( mbox @ ( front @ B ) ) ) ) ) ) ) ) ) ).

thf(furniture_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( furniture @ A ) ) ) @ ( mbox @ ( furniture @ B ) ) ) ) ) ) ) ) ) ).

thf(hollywood_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( hollywood @ A ) ) ) @ ( mbox @ ( hollywood @ B ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ A @ C ) ) ) @ ( mbox @ ( in @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ C @ A ) ) ) @ ( mbox @ ( in @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(lonely_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( lonely @ A ) ) ) @ ( mbox @ ( lonely @ B ) ) ) ) ) ) ) ) ) ).

thf(man_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( man @ A ) ) ) @ ( mbox @ ( man @ B ) ) ) ) ) ) ) ) ) ).

thf(old_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( old @ A ) ) ) @ ( mbox @ ( old @ B ) ) ) ) ) ) ) ) ) ).

thf(seat_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( seat @ A ) ) ) @ ( mbox @ ( seat @ B ) ) ) ) ) ) ) ) ) ).

thf(street_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( street @ A ) ) ) @ ( mbox @ ( street @ B ) ) ) ) ) ) ) ) ) ).

thf(way_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( way @ A ) ) ) @ ( mbox @ ( way @ B ) ) ) ) ) ) ) ) ) ).

thf(white_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( white @ A ) ) ) @ ( mbox @ ( white @ B ) ) ) ) ) ) ) ) ) ).

thf(young_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( young @ A ) ) ) @ ( mbox @ ( young @ B ) ) ) ) ) ) ) ) ) ).

thf(co1,conjecture,
    ( mlocal
    @ ( mand
      @ ( mbox
        @ ( mimplies
          @ ( mexists_di
            @ ^ [U: $i] :
                ( mexists_di
                @ ^ [V: $i] :
                    ( mexists_di
                    @ ^ [W: $i] :
                        ( mexists_di
                        @ ^ [X: $i] :
                            ( mexists_di
                            @ ^ [Y: $i] :
                                ( mexists_di
                                @ ^ [Z: $i] :
                                    ( mexists_di
                                    @ ^ [X1: $i] :
                                        ( mexists_di
                                        @ ^ [X2: $i] :
                                            ( mexists_di
                                            @ ^ [X4: $i] :
                                                ( mexists_di
                                                @ ^ [X5: $i] : ( mand @ ( mbox @ ( seat @ U ) ) @ ( mand @ ( mbox @ ( furniture @ U ) ) @ ( mand @ ( mbox @ ( front @ U ) ) @ ( mand @ ( mbox @ ( seat @ V ) ) @ ( mand @ ( mbox @ ( furniture @ V ) ) @ ( mand @ ( mbox @ ( front @ V ) ) @ ( mand @ ( mbox @ ( hollywood @ W ) ) @ ( mand @ ( mbox @ ( city @ W ) ) @ ( mand @ ( mbox @ ( event @ X ) ) @ ( mand @ ( mbox @ ( street @ Y ) ) @ ( mand @ ( mbox @ ( way @ Y ) ) @ ( mand @ ( mbox @ ( lonely @ Y ) ) @ ( mand @ ( mbox @ ( chevy @ Z ) ) @ ( mand @ ( mbox @ ( car @ Z ) ) @ ( mand @ ( mbox @ ( white @ Z ) ) @ ( mand @ ( mbox @ ( dirty @ Z ) ) @ ( mand @ ( mbox @ ( old @ Z ) ) @ ( mand @ ( mbox @ ( barrel @ X @ Z ) ) @ ( mand @ ( mbox @ ( down @ X @ Y ) ) @ ( mand @ ( mbox @ ( in @ X @ W ) ) @ ( mand @ ( mbox @ ( mnot @ ( mbox @ ( qmltpeq @ X1 @ X2 ) ) ) ) @ ( mand @ ( mbox @ ( fellow @ X1 ) ) @ ( mand @ ( mbox @ ( man @ X1 ) ) @ ( mand @ ( mbox @ ( young @ X1 ) ) @ ( mand @ ( mbox @ ( fellow @ X2 ) ) @ ( mand @ ( mbox @ ( man @ X2 ) ) @ ( mand @ ( mbox @ ( young @ X2 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X1 @ X4 ) ) @ ( mand @ ( mbox @ ( in @ X4 @ U ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X2 @ X5 ) ) @ ( mbox @ ( in @ X5 @ V ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
          @ ( mexists_di
            @ ^ [X6: $i] :
                ( mexists_di
                @ ^ [X7: $i] :
                    ( mexists_di
                    @ ^ [X8: $i] :
                        ( mexists_di
                        @ ^ [X9: $i] :
                            ( mexists_di
                            @ ^ [X10: $i] :
                                ( mexists_di
                                @ ^ [X11: $i] :
                                    ( mexists_di
                                    @ ^ [X12: $i] :
                                        ( mexists_di
                                        @ ^ [X13: $i] :
                                            ( mexists_di
                                            @ ^ [X15: $i] :
                                                ( mexists_di
                                                @ ^ [X16: $i] : ( mand @ ( mbox @ ( seat @ X6 ) ) @ ( mand @ ( mbox @ ( furniture @ X6 ) ) @ ( mand @ ( mbox @ ( front @ X6 ) ) @ ( mand @ ( mbox @ ( seat @ X7 ) ) @ ( mand @ ( mbox @ ( furniture @ X7 ) ) @ ( mand @ ( mbox @ ( front @ X7 ) ) @ ( mand @ ( mbox @ ( hollywood @ X8 ) ) @ ( mand @ ( mbox @ ( city @ X8 ) ) @ ( mand @ ( mbox @ ( event @ X9 ) ) @ ( mand @ ( mbox @ ( chevy @ X10 ) ) @ ( mand @ ( mbox @ ( car @ X10 ) ) @ ( mand @ ( mbox @ ( white @ X10 ) ) @ ( mand @ ( mbox @ ( dirty @ X10 ) ) @ ( mand @ ( mbox @ ( old @ X10 ) ) @ ( mand @ ( mbox @ ( street @ X11 ) ) @ ( mand @ ( mbox @ ( way @ X11 ) ) @ ( mand @ ( mbox @ ( lonely @ X11 ) ) @ ( mand @ ( mbox @ ( barrel @ X9 @ X10 ) ) @ ( mand @ ( mbox @ ( down @ X9 @ X11 ) ) @ ( mand @ ( mbox @ ( in @ X9 @ X8 ) ) @ ( mand @ ( mbox @ ( mnot @ ( mbox @ ( qmltpeq @ X12 @ X13 ) ) ) ) @ ( mand @ ( mbox @ ( fellow @ X12 ) ) @ ( mand @ ( mbox @ ( man @ X12 ) ) @ ( mand @ ( mbox @ ( young @ X12 ) ) @ ( mand @ ( mbox @ ( fellow @ X13 ) ) @ ( mand @ ( mbox @ ( man @ X13 ) ) @ ( mand @ ( mbox @ ( young @ X13 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X12 @ X15 ) ) @ ( mand @ ( mbox @ ( in @ X15 @ X6 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X13 @ X16 ) ) @ ( mbox @ ( in @ X16 @ X7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
      @ ( mbox
        @ ( mimplies
          @ ( mexists_di
            @ ^ [X17: $i] :
                ( mexists_di
                @ ^ [X18: $i] :
                    ( mexists_di
                    @ ^ [X19: $i] :
                        ( mexists_di
                        @ ^ [X20: $i] :
                            ( mexists_di
                            @ ^ [X21: $i] :
                                ( mexists_di
                                @ ^ [X22: $i] :
                                    ( mexists_di
                                    @ ^ [X23: $i] :
                                        ( mexists_di
                                        @ ^ [X24: $i] :
                                            ( mexists_di
                                            @ ^ [X26: $i] :
                                                ( mexists_di
                                                @ ^ [X27: $i] : ( mand @ ( mbox @ ( seat @ X17 ) ) @ ( mand @ ( mbox @ ( furniture @ X17 ) ) @ ( mand @ ( mbox @ ( front @ X17 ) ) @ ( mand @ ( mbox @ ( seat @ X18 ) ) @ ( mand @ ( mbox @ ( furniture @ X18 ) ) @ ( mand @ ( mbox @ ( front @ X18 ) ) @ ( mand @ ( mbox @ ( hollywood @ X19 ) ) @ ( mand @ ( mbox @ ( city @ X19 ) ) @ ( mand @ ( mbox @ ( event @ X20 ) ) @ ( mand @ ( mbox @ ( chevy @ X21 ) ) @ ( mand @ ( mbox @ ( car @ X21 ) ) @ ( mand @ ( mbox @ ( white @ X21 ) ) @ ( mand @ ( mbox @ ( dirty @ X21 ) ) @ ( mand @ ( mbox @ ( old @ X21 ) ) @ ( mand @ ( mbox @ ( street @ X22 ) ) @ ( mand @ ( mbox @ ( way @ X22 ) ) @ ( mand @ ( mbox @ ( lonely @ X22 ) ) @ ( mand @ ( mbox @ ( barrel @ X20 @ X21 ) ) @ ( mand @ ( mbox @ ( down @ X20 @ X22 ) ) @ ( mand @ ( mbox @ ( in @ X20 @ X19 ) ) @ ( mand @ ( mbox @ ( mnot @ ( mbox @ ( qmltpeq @ X23 @ X24 ) ) ) ) @ ( mand @ ( mbox @ ( fellow @ X23 ) ) @ ( mand @ ( mbox @ ( man @ X23 ) ) @ ( mand @ ( mbox @ ( young @ X23 ) ) @ ( mand @ ( mbox @ ( fellow @ X24 ) ) @ ( mand @ ( mbox @ ( man @ X24 ) ) @ ( mand @ ( mbox @ ( young @ X24 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X23 @ X26 ) ) @ ( mand @ ( mbox @ ( in @ X26 @ X17 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X24 @ X27 ) ) @ ( mbox @ ( in @ X27 @ X18 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
          @ ( mexists_di
            @ ^ [X28: $i] :
                ( mexists_di
                @ ^ [X29: $i] :
                    ( mexists_di
                    @ ^ [X30: $i] :
                        ( mexists_di
                        @ ^ [X31: $i] :
                            ( mexists_di
                            @ ^ [X32: $i] :
                                ( mexists_di
                                @ ^ [X33: $i] :
                                    ( mexists_di
                                    @ ^ [X34: $i] :
                                        ( mexists_di
                                        @ ^ [X35: $i] :
                                            ( mexists_di
                                            @ ^ [X37: $i] :
                                                ( mexists_di
                                                @ ^ [X38: $i] : ( mand @ ( mbox @ ( seat @ X28 ) ) @ ( mand @ ( mbox @ ( furniture @ X28 ) ) @ ( mand @ ( mbox @ ( front @ X28 ) ) @ ( mand @ ( mbox @ ( seat @ X29 ) ) @ ( mand @ ( mbox @ ( furniture @ X29 ) ) @ ( mand @ ( mbox @ ( front @ X29 ) ) @ ( mand @ ( mbox @ ( hollywood @ X30 ) ) @ ( mand @ ( mbox @ ( city @ X30 ) ) @ ( mand @ ( mbox @ ( event @ X31 ) ) @ ( mand @ ( mbox @ ( street @ X32 ) ) @ ( mand @ ( mbox @ ( way @ X32 ) ) @ ( mand @ ( mbox @ ( lonely @ X32 ) ) @ ( mand @ ( mbox @ ( chevy @ X33 ) ) @ ( mand @ ( mbox @ ( car @ X33 ) ) @ ( mand @ ( mbox @ ( white @ X33 ) ) @ ( mand @ ( mbox @ ( dirty @ X33 ) ) @ ( mand @ ( mbox @ ( old @ X33 ) ) @ ( mand @ ( mbox @ ( barrel @ X31 @ X33 ) ) @ ( mand @ ( mbox @ ( down @ X31 @ X32 ) ) @ ( mand @ ( mbox @ ( in @ X31 @ X30 ) ) @ ( mand @ ( mbox @ ( mnot @ ( mbox @ ( qmltpeq @ X34 @ X35 ) ) ) ) @ ( mand @ ( mbox @ ( fellow @ X34 ) ) @ ( mand @ ( mbox @ ( man @ X34 ) ) @ ( mand @ ( mbox @ ( young @ X34 ) ) @ ( mand @ ( mbox @ ( fellow @ X35 ) ) @ ( mand @ ( mbox @ ( man @ X35 ) ) @ ( mand @ ( mbox @ ( young @ X35 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X34 @ X37 ) ) @ ( mand @ ( mbox @ ( in @ X37 @ X28 ) ) @ ( mand @ ( mbox @ ( qmltpeq @ X35 @ X38 ) ) @ ( mbox @ ( in @ X38 @ X29 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
