
% propositions
thf(v1_type,type,(v1 : ($o))).
thf(v2_type,type,(v2 : ($o))).
thf(v3_type,type,(v3 : ($o))).
thf(v4_type,type,(v4 : ($o))).
thf(v5_type,type,(v5 : ($o))).
thf(v6_type,type,(v6 : ($o))).
thf(v7_type,type,(v7 : ($o))).
thf(v8_type,type,(v8 : ($o))).
thf(v9_type,type,(v9 : ($o))).
thf(v10_type,type,(v10 : ($o))).
thf(v12_type,type,(v12 : ($o))).
thf(v11_type,type,(v11 : ($o))).
thf(v14_type,type,(v14 : ($o))).
thf(v13_type,type,(v13 : ($o))).
thf(v16_type,type,(v16 : ($o))).
thf(v15_type,type,(v15 : ($o))).
thf(v18_type,type,(v18 : ($o))).
thf(v17_type,type,(v17 : ($o))).
thf(v19_type,type,(v19 : ($o))).
thf(v20_type,type,(v20 : ($o))).
thf(v23_type,type,(v23 : ($o))).
thf(v22_type,type,(v22 : ($o))).
thf(v25_type,type,(v25 : ($o))).
thf(v24_type,type,(v24 : ($o))).
thf(v27_type,type,(v27 : ($o))).
thf(v26_type,type,(v26 : ($o))).
thf(v29_type,type,(v29 : ($o))).
thf(v28_type,type,(v28 : ($o))).
thf(v30_type,type,(v30 : ($o))).
thf(v32_type,type,(v32 : ($o))).
thf(v34_type,type,(v34 : ($o))).
thf(v33_type,type,(v33 : ($o))).
thf(v36_type,type,(v36 : ($o))).
thf(v35_type,type,(v35 : ($o))).
thf(v38_type,type,(v38 : ($o))).
thf(v37_type,type,(v37 : ($o))).
thf(v39_type,type,(v39 : ($o))).
thf(v41_type,type,(v41 : ($o))).
thf(v40_type,type,(v40 : ($o))).
thf(v43_type,type,(v43 : ($o))).
thf(v42_type,type,(v42 : ($o))).
thf(v45_type,type,(v45 : ($o))).
thf(v44_type,type,(v44 : ($o))).
thf(v47_type,type,(v47 : ($o))).
thf(v46_type,type,(v46 : ($o))).
thf(v49_type,type,(v49 : ($o))).
thf(v48_type,type,(v48 : ($o))).
thf(v50_type,type,(v50 : ($o))).
thf(v52_type,type,(v52 : ($o))).
thf(v51_type,type,(v51 : ($o))).
thf(v54_type,type,(v54 : ($o))).
thf(v53_type,type,(v53 : ($o))).
thf(v56_type,type,(v56 : ($o))).
thf(v55_type,type,(v55 : ($o))).

% individual constants

% predicates

% functions

% converted problem
%--------------------------------------------------------------------------
% File     : SYM356+1: QMLTP v11.1
% Domain   : Syntactic (modal)
% Problem  : QBF-CNFSSS-K=4 C=40 V=8 D=6.1
% Version  : Especial.
% English  :
% Refs     : [Sch99] Schmidt (1999), Decidability by Resolution for Proposit
%          : [HS00a] Hustadt & Schmidt (2000), MSPASS: Modal Reasoning by Tr
%          : [HS00b] Hustadt & Schmidt (2000), Issues of Decidability for De
%          : [Sch01] Schmidt (2001), Email to G. Sutcliffe
% Source   : [Sch01]
% Names    : p-qbf-cnfSSS-K4-C40-V8-D6.1 [Sch01]
% Status   :      varying      cumulative   constant
%             K   Unsolved     Non-Theorem  Unsolved      v1.1
%             D   Unsolved     Unsolved     Unsolved      v1.1
%             T   Unsolved     Unsolved     Unsolved      v1.1
%             S4  Unsolved     Unsolved     Unsolved      v1.1
%             S5  Unsolved     Unsolved     Unsolved      v1.1
%
% Rating   :      varying      cumulative   constant
%             K   1.00         0.75         1.00          v1.1
%             D   1.00         1.00         1.00          v1.1
%             T   1.00         1.00         1.00          v1.1
%             S4  1.00         1.00         1.00          v1.1
%             S5  1.00         1.00         1.00          v1.1
%
%  term conditions for all terms: designation: rigid, extension: local
%
% Comments :
%--------------------------------------------------------------------------
thf(mod1,hypothesis,( {$box} @ ( v56 | ( {$box} @ ( {$box} @ ( ( ~ ( v54 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v16 ) ) | ( {$box} @ v15 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod2,hypothesis,( {$box} @ ( {$box} @ ( v55 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v45 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v30 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod3,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( v54 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v32 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v9 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod4,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v54 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v49 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v12 | ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v9 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod5,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v54 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v34 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v16 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v12 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod6,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v53 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v38 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v14 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v10 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod7,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v53 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v47 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v41 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod8,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v53 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v43 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v39 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v25 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod9,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v53 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v41 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v10 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod10,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v52 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v48 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v22 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod11,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v52 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v41 ) ) | ( {$box} @ ( {$box} @ ( ( ~ ( v39 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v28 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod12,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v51 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v43 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v27 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod13,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v51 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v47 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v34 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v26 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod14,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v50 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v42 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v25 | ( {$box} @ ( {$box} @ v23 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod15,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v49 | ( {$box} @ ( v48 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v37 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v16 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod16,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v49 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v30 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v15 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod17,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v49 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v41 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v30 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v8 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod18,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v49 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v29 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v14 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod19,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v48 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v33 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v18 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v9 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod20,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v48 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v32 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v22 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod21,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v48 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v24 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v11 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod22,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v46 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v34 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v14 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod23,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v45 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v19 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v12 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod24,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v44 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v27 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v22 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v6 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod25,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v44 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v23 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v14 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v4 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod26,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v44 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v33 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v20 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v15 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod27,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v43 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v34 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v30 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v5 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod28,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v43 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v24 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v11 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod29,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v43 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v36 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v12 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod30,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v42 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v17 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v9 ) ) | ( {$box} @ ( {$box} @ ( ~ ( v7 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod31,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v40 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v33 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v16 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod32,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v39 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v29 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( v26 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v19 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod33,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v38 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v27 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v13 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v2 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod34,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v37 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v14 ) ) | ( {$box} @ ( ( ~ ( v13 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v1 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod35,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v36 ) ) | ( {$box} @ ( ( ~ ( v35 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v29 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod36,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v35 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v17 | ( {$box} @ ( {$box} @ ( {$box} @ ( v14 | ( {$box} @ ( {$box} @ ( {$box} @ v11 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod37,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v34 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v25 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v9 | ( {$box} @ ( {$box} @ ( {$box} @ ( ~ ( v6 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod38,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v30 ) ) | ( {$box} @ ( {$box} @ ( {$box} @ ( v27 | ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v24 ) ) | ( {$box} @ ( {$box} @ v22 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod39,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v29 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( ( ~ ( v20 ) ) | ( {$box} @ ( {$box} @ ( v18 | ( {$box} @ ( {$box} @ ( {$box} @ v15 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(mod40,hypothesis,( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v18 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( v12 | ( {$box} @ ( {$box} @ ( {$box} @ ( v9 | ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ ( {$box} @ v3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ).
thf(alt1,hypothesis,( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( ( {$box} @ ( {$dia} @ $true ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ v9 ) & ( {$dia} @ ( ~ ( v9 ) ) ) ) ) & ( {$dia} @ v10 ) & ( {$dia} @ ( ~ ( v10 ) ) ) ) ) & ( {$dia} @ v11 ) & ( {$dia} @ ( ~ ( v11 ) ) ) ) ) & ( {$dia} @ v12 ) & ( {$dia} @ ( ~ ( v12 ) ) ) ) ) & ( {$dia} @ v13 ) & ( {$dia} @ ( ~ ( v13 ) ) ) ) ) & ( {$dia} @ v14 ) & ( {$dia} @ ( ~ ( v14 ) ) ) ) ) & ( {$dia} @ v15 ) & ( {$dia} @ ( ~ ( v15 ) ) ) ) ) & ( {$dia} @ v16 ) & ( {$dia} @ ( ~ ( v16 ) ) ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ v25 ) & ( {$dia} @ ( ~ ( v25 ) ) ) ) ) & ( {$dia} @ v26 ) & ( {$dia} @ ( ~ ( v26 ) ) ) ) ) & ( {$dia} @ v27 ) & ( {$dia} @ ( ~ ( v27 ) ) ) ) ) & ( {$dia} @ v28 ) & ( {$dia} @ ( ~ ( v28 ) ) ) ) ) & ( {$dia} @ v29 ) & ( {$dia} @ ( ~ ( v29 ) ) ) ) ) & ( {$dia} @ v30 ) & ( {$dia} @ ( ~ ( v30 ) ) ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ v32 ) & ( {$dia} @ ( ~ ( v32 ) ) ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ v41 ) & ( {$dia} @ ( ~ ( v41 ) ) ) ) ) & ( {$dia} @ v42 ) & ( {$dia} @ ( ~ ( v42 ) ) ) ) ) & ( {$dia} @ v43 ) & ( {$dia} @ ( ~ ( v43 ) ) ) ) ) & ( {$dia} @ v44 ) & ( {$dia} @ ( ~ ( v44 ) ) ) ) ) & ( {$dia} @ v45 ) & ( {$dia} @ ( ~ ( v45 ) ) ) ) ) & ( {$dia} @ v46 ) & ( {$dia} @ ( ~ ( v46 ) ) ) ) ) & ( {$dia} @ v47 ) & ( {$dia} @ ( ~ ( v47 ) ) ) ) ) & ( {$dia} @ v48 ) & ( {$dia} @ ( ~ ( v48 ) ) ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ) & ( {$dia} @ $true ) ) ).
thf(result1,conjecture,$false ).
