%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:05 CEST 2022 using command 'downgrade(tff)'.
tff(intersect_type, type, intersect: (($i * $i) > $o)).
tff(disjoint_type, type, disjoint: (($i * $i) > $o)).
tff(member_type, type, member: (($i * $i) > $o)).
tff(intersect_defn, axiom, (! [B:$i,C:$i]: ((intersect(B,C) <=> (? [D:$i]: ((member(D,B) & member(D,C)))))))).
tff(disjoint_defn, axiom, (! [B:$i,C:$i]: ((disjoint(B,C) <=> ~ (intersect(B,C)))))).
tff(symmetry_of_intersect, axiom, (! [B:$i,C:$i]: ((intersect(B,C) => intersect(C,B))))).
tff(prove_th17, conjecture, (! [B:$i,C:$i]: (((! [D:$i]: ((member(D,B) => ~ (member(D,C))))) => disjoint(B,C))))).
