%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:06 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(member_type, type, member: (($i * $i) > $o)).
tff(subset_type, type, subset: (($i * $i) > $o)).
tff(difference_type, type, difference: (($i * $i) > $i)).
tff(reflexivity, axiom, (! [X:$i]: (qmltpeq(X,X)))).
tff(symmetry, axiom, (! [X:$i,Y:$i]: ((qmltpeq(X,Y) => qmltpeq(Y,X))))).
tff(transitivity, axiom, (! [X:$i,Y:$i,Z:$i]: (((qmltpeq(X,Y) & qmltpeq(Y,Z)) => qmltpeq(X,Z))))).
tff(difference_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(difference(A,C),difference(B,C)))))).
tff(difference_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(difference(C,A),difference(C,B)))))).
tff(member_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & member(A,C)) => member(B,C))))).
tff(member_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & member(C,A)) => member(C,B))))).
tff(subset_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(A,C)) => subset(B,C))))).
tff(subset_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(C,A)) => subset(C,B))))).
tff(difference_defn, axiom, (! [B:$i,C:$i,D:$i]: ((member(D,difference(B,C)) <=> (member(D,B) & ~ (member(D,C))))))).
tff(equal_defn, axiom, (! [B:$i,C:$i]: ((qmltpeq(B,C) <=> (subset(B,C) & subset(C,B)))))).
tff(subset_defn, axiom, (! [B:$i,C:$i]: ((subset(B,C) <=> (! [D:$i]: ((member(D,B) => member(D,C)))))))).
tff(reflexivity_of_subset, axiom, (! [B:$i]: (subset(B,B)))).
tff(prove_th20, conjecture, (! [B:$i,C:$i,D:$i]: (((! [E:$i]: ((member(E,B) <=> (member(E,C) & ~ (member(E,D)))))) => qmltpeq(B,difference(C,D)))))).
