%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:11 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(in_type, type, in: (($i * $i) > $o)).
tff(subset_type, type, subset: (($i * $i) > $o)).
tff(empty_type, type, empty: ($i > $o)).
tff(singleton_type, type, singleton: ($i > $i)).
tff(set_union2_type, type, set_union2: (($i * $i) > $i)).
tff(reflexivity, axiom, (! [X:$i]: (qmltpeq(X,X)))).
tff(symmetry, axiom, (! [X:$i,Y:$i]: ((qmltpeq(X,Y) => qmltpeq(Y,X))))).
tff(transitivity, axiom, (! [X:$i,Y:$i,Z:$i]: (((qmltpeq(X,Y) & qmltpeq(Y,Z)) => qmltpeq(X,Z))))).
tff(set_union2_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_union2(A,C),set_union2(B,C)))))).
tff(set_union2_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_union2(C,A),set_union2(C,B)))))).
tff(singleton_substitution_1, axiom, (! [A:$i,B:$i]: ((qmltpeq(A,B) => qmltpeq(singleton(A),singleton(B)))))).
tff(empty_substitution_1, axiom, (! [A:$i,B:$i]: (((qmltpeq(A,B) & empty(A)) => empty(B))))).
tff(in_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(A,C)) => in(B,C))))).
tff(in_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(C,A)) => in(C,B))))).
tff(subset_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(A,C)) => subset(B,C))))).
tff(subset_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(C,A)) => subset(C,B))))).
tff(fc2_xboole_0, axiom, (! [A:$i,B:$i]: ((~ (empty(A)) => ~ (empty(set_union2(A,B))))))).
tff(fc3_xboole_0, axiom, (! [A:$i,B:$i]: ((~ (empty(A)) => ~ (empty(set_union2(B,A))))))).
tff(commutativity_k2_xboole_0, axiom, (! [A:$i,B:$i]: (qmltpeq(set_union2(A,B),set_union2(B,A))))).
tff(idempotence_k2_xboole_0, axiom, (! [A:$i,B:$i]: (qmltpeq(set_union2(A,A),A)))).
tff(reflexivity_r1_tarski, axiom, (! [A:$i,B:$i]: (subset(A,A)))).
tff(antisymmetry_r2_hidden, axiom, (! [A:$i,B:$i]: ((in(A,B) => ~ (in(B,A)))))).
tff(rc1_xboole_0, axiom, (? [A:$i]: (empty(A)))).
tff(rc2_xboole_0, axiom, (? [A:$i]: (~ (empty(A))))).
tff(t45_zfmisc_1, conjecture, (! [A:$i,B:$i]: ((subset(set_union2(singleton(A),B),B) => in(A,B))))).
tff(l21_zfmisc_1, axiom, (! [A:$i,B:$i]: ((subset(set_union2(singleton(A),B),B) => in(A,B))))).
