%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:16 CEST 2022 using command 'downgrade(tff)'.
tff(in_type, type, in: (($i * $i) > $o)).
tff(disjoint_type, type, disjoint: (($i * $i) > $o)).
tff(empty_type, type, empty: ($i > $o)).
tff(singleton_type, type, singleton: ($i > $i)).
tff(symmetry_r1_xboole_0, axiom, (! [A:$i,B:$i]: ((disjoint(A,B) => disjoint(B,A))))).
tff(antisymmetry_r2_hidden, axiom, (! [A:$i,B:$i]: ((in(A,B) => ~ (in(B,A)))))).
tff(rc1_xboole_0, axiom, (? [A:$i]: (empty(A)))).
tff(rc2_xboole_0, axiom, (? [A:$i]: (~ (empty(A))))).
tff(t56_zfmisc_1, conjecture, (! [A:$i,B:$i]: ((~ (in(A,B)) => disjoint(singleton(A),B))))).
tff(l28_zfmisc_1, axiom, (! [A:$i,B:$i]: ((~ (in(A,B)) => disjoint(singleton(A),B))))).
