%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:38:15 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(in_type, type, in: (($i * $i) > $o)).
tff(subset_type, type, subset: (($i * $i) > $o)).
tff(empty_type, type, empty: ($i > $o)).
tff(set_intersection2_type, type, set_intersection2: (($i * $i) > $i)).
tff(unordered_pair_type, type, unordered_pair: (($i * $i) > $i)).
tff(reflexivity, axiom, (! [X:$i]: (qmltpeq(X,X)))).
tff(symmetry, axiom, (! [X:$i,Y:$i]: ((qmltpeq(X,Y) => qmltpeq(Y,X))))).
tff(transitivity, axiom, (! [X:$i,Y:$i,Z:$i]: (((qmltpeq(X,Y) & qmltpeq(Y,Z)) => qmltpeq(X,Z))))).
tff(set_intersection2_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_intersection2(A,C),set_intersection2(B,C)))))).
tff(set_intersection2_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(set_intersection2(C,A),set_intersection2(C,B)))))).
tff(unordered_pair_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(unordered_pair(A,C),unordered_pair(B,C)))))).
tff(unordered_pair_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: ((qmltpeq(A,B) => qmltpeq(unordered_pair(C,A),unordered_pair(C,B)))))).
tff(empty_substitution_1, axiom, (! [A:$i,B:$i]: (((qmltpeq(A,B) & empty(A)) => empty(B))))).
tff(in_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(A,C)) => in(B,C))))).
tff(in_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & in(C,A)) => in(C,B))))).
tff(subset_substitution_1, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(A,C)) => subset(B,C))))).
tff(subset_substitution_2, axiom, (! [A:$i,B:$i,C:$i]: (((qmltpeq(A,B) & subset(C,A)) => subset(C,B))))).
tff(antisymmetry_r2_hidden, axiom, (! [A:$i,B:$i]: ((in(A,B) => ~ (in(B,A)))))).
tff(commutativity_k2_tarski, axiom, (! [A:$i,B:$i]: (qmltpeq(unordered_pair(A,B),unordered_pair(B,A))))).
tff(commutativity_k3_xboole_0, axiom, (! [A:$i,B:$i]: (qmltpeq(set_intersection2(A,B),set_intersection2(B,A))))).
tff(idempotence_k3_xboole_0, axiom, (! [A:$i,B:$i]: (qmltpeq(set_intersection2(A,A),A)))).
tff(rc1_xboole_0, axiom, (? [A:$i]: (empty(A)))).
tff(rc2_xboole_0, axiom, (? [A:$i]: (~ (empty(A))))).
tff(reflexivity_r1_tarski, axiom, (! [A:$i,B:$i]: (subset(A,A)))).
tff(t28_xboole_1, axiom, (! [A:$i,B:$i]: ((subset(A,B) => qmltpeq(set_intersection2(A,B),A))))).
tff(t38_zfmisc_1, axiom, (! [A:$i,B:$i,C:$i]: ((subset(unordered_pair(A,B),C) <=> (in(A,C) & in(B,C)))))).
tff(t53_zfmisc_1, conjecture, (! [A:$i,B:$i,C:$i]: (((in(A,B) & in(C,B)) => qmltpeq(set_intersection2(unordered_pair(A,C),B),unordered_pair(A,C)))))).
