#!/bin/tcsh
#----Put this in the NX0_SEMs (with semantic specifications) directory

foreach problem (*/*.p)
    set name = `basename $problem .p`
    set domain = `dirname $problem`
    java -jar ~/Systems/NTF2THF---1.7.2/logic-embedding-app.jar $problem > ../5_THF_S5U/$domain/${name}.p
    echo "Done $name"
end
