% semantics
% modalities

% propositions

% individual constants

% predicates
thf(chevy_type,type,(chevy : ($i>$o))).
thf(dirty_type,type,(dirty : ($i>$o))).
thf(barrel_type,type,(barrel : ($i>$i>$o))).
thf(hollywood_type,type,(hollywood : ($i>$o))).
thf(city_type,type,(city : ($i>$o))).
thf(in_type,type,(in : ($i>$i>$o))).
thf(old_type,type,(old : ($i>$o))).
thf(down_type,type,(down : ($i>$i>$o))).
thf(way_type,type,(way : ($i>$o))).
thf(white_type,type,(white : ($i>$o))).
thf(car_type,type,(car : ($i>$o))).
thf(street_type,type,(street : ($i>$o))).
thf(event_type,type,(event : ($i>$o))).
thf(lonely_type,type,(lonely : ($i>$o))).

% functions

% converted problem
%--------------------------------------------------------------------------
% File     : NLP001+1 : QMLTP v1.1
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".
% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner 999), FTP'2000 - Problem Sets
% Source   : [Bau99]
% Names    :
% Status   :      varying      cumulative   constant
%             K   Theorem      Theorem      Theorem       v1.1
%             D   Theorem      Theorem      Theorem       v1.1
%             T   Theorem      Theorem      Theorem       v1.1
%             S4  Theorem      Theorem      Theorem       v1.1
%             S5  Theorem      Theorem      Theorem       v1.1
%
% Rating   :      varying      cumulative   constant
%             K   0.50         0.25         0.50          v1.1
%             D   0.25         0.17         0.33          v1.1
%             T   0.25         0.17         0.33          v1.1
%             S4  0.25         0.17         0.50          v1.1
%             S5  0.25         0.20         0.40          v1.1
%
%  term conditions for all terms: designation: rigid, extension: local
%  Comments :
%
%--------------------------------------------------------------------------
% Comments :
%--------------------------------------------------------------------------
thf ( co1 , conjecture , ( ( ? [ U :$i , V :$i , W :$i , X :$i ] : ( ( hollywood @ U ) & ( city @ U ) & ( event @ V ) & ( street @ W ) & ( way @ W ) & ( lonely @ W ) & ( chevy @ X ) & ( car @ X ) & ( white @ X ) & ( dirty @ X ) & ( old @ X ) & ( barrel @ V @ X ) & ( down @ V @ W ) & ( in @ V @ U ) ) => ? [ Y :$i , Z :$i , X1 :$i , X2 :$i ] : ( ( hollywood @ Y ) & ( city @ Y ) & ( event @ Z ) & ( chevy @ X1 ) & ( car @ X1 ) & ( white @ X1 ) & ( dirty @ X1 ) & ( old @ X1 ) & ( street @ X2 ) & ( way @ X2 ) & ( lonely @ X2 ) & ( barrel @ Z @ X1 ) & ( down @ Z @ X2 ) & ( in @ Z @ Y ) ) ) & ( ? [ X3 :$i , X4 :$i , X5 :$i , X6 :$i ] : ( ( hollywood @ X3 ) & ( city @ X3 ) & ( event @ X4 ) & ( chevy @ X5 ) & ( car @ X5 ) & ( white @ X5 ) & ( dirty @ X5 ) & ( old @ X5 ) & ( street @ X6 ) & ( way @ X6 ) & ( lonely @ X6 ) & ( barrel @ X4 @ X5 ) & ( down @ X4 @ X6 ) & ( in @ X4 @ X3 ) ) => ? [ X7 :$i , X8 :$i , X9 :$i , X10 :$i ] : ( ( hollywood @ X7 ) & ( city @ X7 ) & ( event @ X8 ) & ( street @ X9 ) & ( way @ X9 ) & ( lonely @ X9 ) & ( chevy @ X10 ) & ( car @ X10 ) & ( white @ X10 ) & ( dirty @ X10 ) & ( old @ X10 ) & ( barrel @ X8 @ X10 ) & ( down @ X8 @ X9 ) & ( in @ X8 @ X7 ) ) ) ) ) .
%--------------------------------------------------------------------------