tff(s5_constant_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $constant,
     $modalities == $modal_system_S5U
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:49:43 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $i).
tff(fortytwo_decl, type, fortytwo: $i).
tff(balance_decl, type, balance: (($i * $i) > $o)).
tff(account_decl, type, account: (($i * $i) > $o)).
tff(axiom_1, axiom-local, {$box(#bank)}((! [X:$i]: ({$box(#cr)}((account(p,X) => (? [B:$i]: ({$box(#t)}(balance(p,B)))))))))).
tff(axiom_1_0, axiom-local, {$box(#cr)}(account(p,fortytwo))).
tff(con, conjecture, (? [B:$i]: ({$box(#t)}(balance(p,B))))).
