tff(t_cumulative_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $cumulative,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:49:41 CEST 2022 using command 'downgrade(tff)'.
tff(portland_decl, type, portland: $i).
tff(bigcity_decl, type, bigcity: ($i > $o)).
tff(axiom_1_alice, axiom-local, {$box(#b_alice)}(((bigcity(portland) & {$box(#b_alice)}({$box(#b_bob)}(~ (bigcity(portland))))) => {$box(#i_alice)}({$box(#b_bob)}(bigcity(portland)))))).
tff(axiom_1_bob, axiom-local, {$box(#b_bob)}(((bigcity(portland) & {$box(#b_bob)}({$box(#b_alice)}(~ (bigcity(portland))))) => {$box(#i_bob)}({$box(#b_alice)}(bigcity(portland)))))).
tff(axiom_2, axiom-local, {$box(#b_alice)}(bigcity(portland))).
tff(axiom_3, axiom-local, {$box(#b_alice)}({$box(#b_bob)}(~ (bigcity(portland))))).
tff(con, conjecture, {$box(#i_alice)}({$box(#b_bob)}(bigcity(portland)))).
