%--------------------------------------------------------------------------
% File     : NLP001+1 : QMLTP v1.1
% Domain   : Natural Language Processing
% Problem  : "The old dirty white Chevy" problem
% Version  : [Bos00] axioms.
% English  : A problem generated by the DORIS [Bos00] system when parsing
%            the statement "The old dirty white Chevy barrels down a lonely
%            street in Hollywood".

% Refs     : [Bos00] Bos (2000), DORIS: Discourse Oriented Representation an
%            [Bau99] Baumgartner 999), FTP'2000 - Problem Sets
% Source   : [Bau99]
% Names    :

% Status   :      varying      cumulative   constant   
%             K   Theorem      Theorem      Theorem       v1.1
%             D   Theorem      Theorem      Theorem       v1.1
%             T   Theorem      Theorem      Theorem       v1.1
%             S4  Theorem      Theorem      Theorem       v1.1
%             S5  Theorem      Theorem      Theorem       v1.1
%
% Rating   :      varying      cumulative   constant   
%             K   0.50         0.25         0.50          v1.1
%             D   0.25         0.17         0.33          v1.1
%             T   0.25         0.17         0.33          v1.1
%             S4  0.25         0.17         0.50          v1.1
%             S5  0.25         0.20         0.40          v1.1
%
%  term conditions for all terms: designation: rigid, extension: local
%  Comments :
%
%--------------------------------------------------------------------------
% Comments :
%--------------------------------------------------------------------------
qmf(co1,conjecture,
    ( ( ? [U,V,W,X] :
          ( hollywood(U)
          & city(U)
          & event(V)
          & street(W)
          & way(W)
          & lonely(W)
          & chevy(X)
          & car(X)
          & white(X)
          & dirty(X)
          & old(X)
          & barrel(V,X)
          & down(V,W)
          & in(V,U) )
     => ? [Y,Z,X1,X2] :
          ( hollywood(Y)
          & city(Y)
          & event(Z)
          & chevy(X1)
          & car(X1)
          & white(X1)
          & dirty(X1)
          & old(X1)
          & street(X2)
          & way(X2)
          & lonely(X2)
          & barrel(Z,X1)
          & down(Z,X2)
          & in(Z,Y) ) )
    & ( ? [X3,X4,X5,X6] :
          ( hollywood(X3)
          & city(X3)
          & event(X4)
          & chevy(X5)
          & car(X5)
          & white(X5)
          & dirty(X5)
          & old(X5)
          & street(X6)
          & way(X6)
          & lonely(X6)
          & barrel(X4,X5)
          & down(X4,X6)
          & in(X4,X3) )
     => ? [X7,X8,X9,X10] :
          ( hollywood(X7)
          & city(X7)
          & event(X8)
          & street(X9)
          & way(X9)
          & lonely(X9)
          & chevy(X10)
          & car(X10)
          & white(X10)
          & dirty(X10)
          & old(X10)
          & barrel(X8,X10)
          & down(X8,X9)
          & in(X8,X7) ) ) )).

%--------------------------------------------------------------------------
