tff(s4_decreasing_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $decreasing,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:48 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(big_f_decl, type, big_f: ($i > $o)).
tff(pel21_1, axiom-local, (? [X:$i]: ({$box} @ (({$box} @ (p) => {$box} @ (big_f(X))))))).
tff(pel21_2, axiom-local, (? [X:$i]: ({$box} @ (({$box} @ (big_f(X)) => {$box} @ (p)))))).
tff(pel21, conjecture, (? [X:$i]: (({$box} @ (({$box} @ (p) => {$box} @ (big_f(X)))) & {$box} @ (({$box} @ (big_f(X)) => {$box} @ (p))))))).
