tff(s4_constant_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $constant,
     $modalities == $modal_system_S4
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:44 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(q_decl, type, q: $o).
tff(pel3, conjecture, {$box} @ (({$box} @ (~ ({$box} @ (({$box} @ (p) => {$box} @ (q))))) => {$box} @ (({$box} @ (q) => {$box} @ (p)))))).
