tff(k_varying_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $varying,
     $modalities == $modal_system_K
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:34:46 CEST 2022 using command 'downgrade(tff)'.
tff(big_f_decl, type, big_f: ($i > $o)).
tff(pel18, conjecture, (? [Y:$i]: ({$box}((! [X:$i]: ({$box}(({$box}(big_f(Y)) => {$box}(big_f(X)))))))))).
