tff(d_cumulative_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $cumulative,
     $modalities == $modal_system_D
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:06 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(q_decl, type, q: $o).
tff(pel8, conjecture, {$box} @ (({$box} @ (({$box} @ (({$box} @ (p) => {$box} @ (q))) => {$box} @ (p))) => {$box} @ (p)))).
