%------------------------------------------------------------------------------
% File     : NTF001^1 : TPTP v8.1.0. Released v8.1.0.
% Domain   : TBA
% Problem  : TBA
% Version  : TBA
% English  : TBA

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GLC450+1 [QMLTP]

% Status   : Theorem
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :  127 (  12 unt;  52 typ;  10 def)
%            Number of atoms       :  958 (  10 equ;   0 cnn)
%            Maximal formula atoms :   56 (  12 avg)
%            Number of connectives : 1465 (   1   ~;   1   |;   4   &;1454   @)
%                                         (   1 <=>;   4  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   24 (  12 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :  104 ( 104   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   52 (  51 usr;   1 con; 0-3 aty)
%            Number of variables   :  199 ( 188   ^   7   !;   4   ?; 199   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $flexible, $quantification == $constant,
%            $modalities == $modal_system_S5]
%------------------------------------------------------------------------------
tff(p1_decl, type, p1: $o).
tff(p2_decl, type, p2: $o).
tff(p3_decl, type, p3: $o).
tff(pel12, conjecture, ({$box} @ ((({$box} @ ((({$box} @ (({$box} @ (p1) => {$box} @ (p2))) & {$box} @ (({$box} @ (p2) => {$box} @ (p1)))) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => ({$box} @ (({$box} @ (p1) => {$box} @ (p2))) & {$box} @ (({$box} @ (p2) => {$box} @ (p1))))))) => ({$box} @ (({$box} @ (p1) => ({$box} @ (({$box} @ (p2) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => {$box} @ (p2)))))) & {$box} @ ((({$box} @ (({$box} @ (p2) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => {$box} @ (p2)))) => {$box} @ (p1)))))) & {$box} @ ((({$box} @ (({$box} @ (p1) => ({$box} @ (({$box} @ (p2) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => {$box} @ (p2)))))) & {$box} @ ((({$box} @ (({$box} @ (p2) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => {$box} @ (p2)))) => {$box} @ (p1)))) => ({$box} @ ((({$box} @ (({$box} @ (p1) => {$box} @ (p2))) & {$box} @ (({$box} @ (p2) => {$box} @ (p1)))) => {$box} @ (p3))) & {$box} @ (({$box} @ (p3) => ({$box} @ (({$box} @ (p1) => {$box} @ (p2))) & {$box} @ (({$box} @ (p2) => {$box} @ (p1))))))))))).

%------------------------------------------------------------------------------
