tff(d_varying_flexible,logic, ( $modal ==
    [$constants == $flexible,
     $quantification == $varying,
     $modalities == $modal_system_D
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:07 CEST 2022 using command 'downgrade(tff)'.
tff(p1_decl, type, p1: $o).
tff(p2_decl, type, p2: $o).
tff(pel14, conjecture, ({$box}((({$box}(({$box}(p1) => {$box}(p2))) & {$box}(({$box}(p2) => {$box}(p1)))) => (({$box}(p2) | {$box}(~ ({$box}(p1)))) & ({$box}(~ ({$box}(p2))) | {$box}(p1))))) & {$box}(((({$box}(p2) | {$box}(~ ({$box}(p1)))) & ({$box}(~ ({$box}(p2))) | {$box}(p1))) => ({$box}(({$box}(p1) => {$box}(p2))) & {$box}(({$box}(p2) => {$box}(p1)))))))).
