tff(t_cumulative_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $cumulative,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:35:06 CEST 2022 using command 'downgrade(tff)'.
tff(p_decl, type, p: $o).
tff(pel11, conjecture, ({$box} @ (({$box} @ (p) => {$box} @ (p))) & {$box} @ (({$box} @ (p) => {$box} @ (p))))).
