%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:06 CEST 2022 using command 'downgrade(tff)'.
tff(element_type, type, element: (($i * $i) > $o)).
tff(pel41_1, axiom, {$box}((! [Z:$i]: ((? [Y:$i]: ({$box}((! [X:$i]: (({$box}(({$box}(element(X,Y)) => ({$box}(element(X,Z)) & {$box}(~ ({$box}(element(X,X))))))) & {$box}((({$box}(element(X,Z)) & {$box}(~ ({$box}(element(X,X))))) => {$box}(element(X,Y)))))))))))))).
tff(pel41, conjecture, {$box}(~ ((? [Z:$i]: ({$box}((! [X:$i]: ({$box}(element(X,Z)))))))))).
