%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:03 CEST 2022 using command 'downgrade(tff)'.
tff(member_type, type, member: (($i * $i) > $o)).
tff(subset_type, type, subset: (($i * $i) > $o)).
tff(subset_defn, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: (({$box}(({$box}(subset(B,C)) => {$box}((! [D:$i]: ({$box}(({$box}(member(D,B)) => {$box}(member(D,C))))))))) & {$box}(({$box}((! [D:$i]: ({$box}(({$box}(member(D,B)) => {$box}(member(D,C))))))) => {$box}(subset(B,C)))))))))))).
tff(reflexivity_of_subset, axiom, {$box}((! [B:$i]: ({$box}(subset(B,B)))))).
tff(prove_transitivity_of_subset, conjecture, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((! [D:$i]: ({$box}((({$box}(subset(B,C)) & {$box}(subset(C,D))) => {$box}(subset(B,D)))))))))))))).
