%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:21 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(member_type, type, member: (($i * $i) > $o)).
tff(difference_type, type, difference: (($i * $i) > $i)).
tff(symmetric_difference_type, type, symmetric_difference: (($i * $i) > $i)).
tff(union_type, type, union: (($i * $i) > $i)).
tff(reflexivity, axiom, {$box}((! [X:$i]: ({$box}(qmltpeq(X,X)))))).
tff(symmetry, axiom, {$box}((! [X:$i]: ({$box}((! [Y:$i]: ({$box}(({$box}(qmltpeq(X,Y)) => {$box}(qmltpeq(Y,X))))))))))).
tff(transitivity, axiom, {$box}((! [X:$i]: ({$box}((! [Y:$i]: ({$box}((! [Z:$i]: ({$box}((({$box}(qmltpeq(X,Y)) & {$box}(qmltpeq(Y,Z))) => {$box}(qmltpeq(X,Z)))))))))))))).
tff(difference_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(difference(A,C),difference(B,C))))))))))))))).
tff(difference_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(difference(C,A),difference(C,B))))))))))))))).
tff(symmetric_difference_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(symmetric_difference(A,C),symmetric_difference(B,C))))))))))))))).
tff(symmetric_difference_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(symmetric_difference(C,A),symmetric_difference(C,B))))))))))))))).
tff(union_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(union(A,C),union(B,C))))))))))))))).
tff(union_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(union(C,A),union(C,B))))))))))))))).
tff(member_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(member(A,C))) => {$box}(member(B,C)))))))))))))).
tff(member_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(member(C,A))) => {$box}(member(C,B)))))))))))))).
tff(union_defn, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((! [D:$i]: (({$box}(({$box}(member(D,union(B,C))) => ({$box}(member(D,B)) | {$box}(member(D,C))))) & {$box}((({$box}(member(D,B)) | {$box}(member(D,C))) => {$box}(member(D,union(B,C)))))))))))))))).
tff(difference_defn, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((! [D:$i]: (({$box}(({$box}(member(D,difference(B,C))) => ({$box}(member(D,B)) & {$box}(~ ({$box}(member(D,C))))))) & {$box}((({$box}(member(D,B)) & {$box}(~ ({$box}(member(D,C))))) => {$box}(member(D,difference(B,C)))))))))))))))).
tff(symmetric_difference_defn, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(qmltpeq(symmetric_difference(B,C),union(difference(B,C),difference(C,B))))))))))).
tff(commutativity_of_union, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(qmltpeq(union(B,C),union(C,B)))))))))).
tff(commutativity_of_symmetric_difference, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(qmltpeq(symmetric_difference(B,C),symmetric_difference(C,B)))))))))).
tff(equal_member_defn, axiom, {$box}((! [B:$i]: ({$box}((! [C:$i]: (({$box}(({$box}(qmltpeq(B,C)) => {$box}((! [D:$i]: (({$box}(({$box}(member(D,B)) => {$box}(member(D,C)))) & {$box}(({$box}(member(D,C)) => {$box}(member(D,B)))))))))) & {$box}(({$box}((! [D:$i]: (({$box}(({$box}(member(D,B)) => {$box}(member(D,C)))) & {$box}(({$box}(member(D,C)) => {$box}(member(D,B)))))))) => {$box}(qmltpeq(B,C)))))))))))).
tff(prove_th23, conjecture, {$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((! [D:$i]: (({$box}(({$box}(member(B,symmetric_difference(C,D))) => {$box}(~ (({$box}(({$box}(member(B,C)) => {$box}(member(B,D)))) & {$box}(({$box}(member(B,D)) => {$box}(member(B,C))))))))) & {$box}(({$box}(~ (({$box}(({$box}(member(B,C)) => {$box}(member(B,D)))) & {$box}(({$box}(member(B,D)) => {$box}(member(B,C))))))) => {$box}(member(B,symmetric_difference(C,D)))))))))))))))).
