%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:32:28 CEST 2022 using command 'downgrade(tff)'.
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(in_type, type, in: (($i * $i) > $o)).
tff(subset_type, type, subset: (($i * $i) > $o)).
tff(empty_type, type, empty: ($i > $o)).
tff(unordered_pair_type, type, unordered_pair: (($i * $i) > $i)).
tff(set_union2_type, type, set_union2: (($i * $i) > $i)).
tff(reflexivity, axiom, {$box}((! [X:$i]: ({$box}(qmltpeq(X,X)))))).
tff(symmetry, axiom, {$box}((! [X:$i]: ({$box}((! [Y:$i]: ({$box}(({$box}(qmltpeq(X,Y)) => {$box}(qmltpeq(Y,X))))))))))).
tff(transitivity, axiom, {$box}((! [X:$i]: ({$box}((! [Y:$i]: ({$box}((! [Z:$i]: ({$box}((({$box}(qmltpeq(X,Y)) & {$box}(qmltpeq(Y,Z))) => {$box}(qmltpeq(X,Z)))))))))))))).
tff(set_union2_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(set_union2(A,C),set_union2(B,C))))))))))))))).
tff(set_union2_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(set_union2(C,A),set_union2(C,B))))))))))))))).
tff(unordered_pair_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(unordered_pair(A,C),unordered_pair(B,C))))))))))))))).
tff(unordered_pair_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}(({$box}(qmltpeq(A,B)) => {$box}(qmltpeq(unordered_pair(C,A),unordered_pair(C,B))))))))))))))).
tff(empty_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(empty(A))) => {$box}(empty(B))))))))))).
tff(in_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(in(A,C))) => {$box}(in(B,C)))))))))))))).
tff(in_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(in(C,A))) => {$box}(in(C,B)))))))))))))).
tff(subset_substitution_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(subset(A,C))) => {$box}(subset(B,C)))))))))))))).
tff(subset_substitution_2, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(qmltpeq(A,B)) & {$box}(subset(C,A))) => {$box}(subset(C,B)))))))))))))).
tff(antisymmetry_r2_hidden, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(({$box}(in(A,B)) => {$box}(~ ({$box}(in(B,A))))))))))))).
tff(commutativity_k2_tarski, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(qmltpeq(unordered_pair(A,B),unordered_pair(B,A)))))))))).
tff(commutativity_k2_xboole_0, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(qmltpeq(set_union2(A,B),set_union2(B,A)))))))))).
tff(fc2_xboole_0, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(({$box}(~ ({$box}(empty(A)))) => {$box}(~ ({$box}(empty(set_union2(A,B)))))))))))))).
tff(fc3_xboole_0, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(({$box}(~ ({$box}(empty(A)))) => {$box}(~ ({$box}(empty(set_union2(B,A)))))))))))))).
tff(idempotence_k2_xboole_0, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(qmltpeq(set_union2(A,A),A))))))))).
tff(rc1_xboole_0, axiom, (? [A:$i]: ({$box}(empty(A))))).
tff(rc2_xboole_0, axiom, (? [A:$i]: ({$box}(~ ({$box}(empty(A))))))).
tff(reflexivity_r1_tarski, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(subset(A,A))))))))).
tff(t12_xboole_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}(({$box}(subset(A,B)) => {$box}(qmltpeq(set_union2(A,B),B))))))))))).
tff(t38_zfmisc_1, axiom, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: (({$box}(({$box}(subset(unordered_pair(A,B),C)) => ({$box}(in(A,C)) & {$box}(in(B,C))))) & {$box}((({$box}(in(A,C)) & {$box}(in(B,C))) => {$box}(subset(unordered_pair(A,B),C))))))))))))))).
tff(t48_zfmisc_1, conjecture, {$box}((! [A:$i]: ({$box}((! [B:$i]: ({$box}((! [C:$i]: ({$box}((({$box}(in(A,B)) & {$box}(in(C,B))) => {$box}(qmltpeq(set_union2(unordered_pair(A,C),B),B)))))))))))))).
