%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:37:25 CEST 2022 using command 'downgrade(tff)'.
tff(chevy_type, type, chevy: ($i > $o)).
tff(dirty_type, type, dirty: ($i > $o)).
tff(barrel_type, type, barrel: (($i * $i) > $o)).
tff(hollywood_type, type, hollywood: ($i > $o)).
tff(city_type, type, city: ($i > $o)).
tff(in_type, type, in: (($i * $i) > $o)).
tff(old_type, type, old: ($i > $o)).
tff(down_type, type, down: (($i * $i) > $o)).
tff(way_type, type, way: ($i > $o)).
tff(white_type, type, white: ($i > $o)).
tff(car_type, type, car: ($i > $o)).
tff(street_type, type, street: ($i > $o)).
tff(event_type, type, event: ($i > $o)).
tff(lonely_type, type, lonely: ($i > $o)).
tff(co1, conjecture, (((? [U:$i,V:$i,W:$i,X:$i]: ((hollywood(U) & (city(U) & (event(V) & (street(W) & (way(W) & (lonely(W) & (chevy(X) & (car(X) & (white(X) & (dirty(X) & (old(X) & (barrel(V,X) & (down(V,W) & in(V,U)))))))))))))))) => (? [Y:$i,Z:$i,X1:$i,X2:$i]: ((hollywood(Y) & (city(Y) & (event(Z) & (chevy(X1) & (car(X1) & (white(X1) & (dirty(X1) & (old(X1) & (street(X2) & (way(X2) & (lonely(X2) & (barrel(Z,X1) & (down(Z,X2) & in(Z,Y))))))))))))))))) & ((? [X3:$i,X4:$i,X5:$i,X6:$i]: ((hollywood(X3) & (city(X3) & (event(X4) & (chevy(X5) & (car(X5) & (white(X5) & (dirty(X5) & (old(X5) & (street(X6) & (way(X6) & (lonely(X6) & (barrel(X4,X5) & (down(X4,X6) & in(X4,X3)))))))))))))))) => (? [X7:$i,X8:$i,X9:$i,X10:$i]: ((hollywood(X7) & (city(X7) & (event(X8) & (street(X9) & (way(X9) & (lonely(X9) & (chevy(X10) & (car(X10) & (white(X10) & (dirty(X10) & (old(X10) & (barrel(X8,X10) & (down(X8,X9) & in(X8,X7))))))))))))))))))).
