%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:12 CEST 2022 using command 'downgrade(tff)'.
tff(c_type, type, c: $i).
tff(p_type, type, p: ($i > $o)).
tff(con, conjecture, ({$box}(p(c)) => (? [X:$i]: ({$box}(p(X)))))).
