%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:05 CEST 2022 using command 'downgrade(tff)'.
tff(a_type, type, a: $o).
tff(qmltpeq_type, type, qmltpeq: (($i * $i) > $o)).
tff(e_type, type, e: ($i > $o)).
tff(reflexivity, axiom, (! [X:$i]: (qmltpeq(X,X)))).
tff(symmetry, axiom, (! [X:$i,Y:$i]: ((qmltpeq(X,Y) => qmltpeq(Y,X))))).
tff(transitivity, axiom, (! [X:$i,Y:$i,Z:$i]: (((qmltpeq(X,Y) & qmltpeq(Y,Z)) => qmltpeq(X,Z))))).
tff(e_substitution_1, axiom, (! [A:$i,B:$i]: (((qmltpeq(A,B) & e(A)) => e(B))))).
tff(con, conjecture, (({$dia}((? [X:$i]: ({$dia}((? [Y:$i]: (~ (qmltpeq(X,Y)))))))) & (a & {$box}((! [X:$i]: ({$box}((a => e(X)))))))) => (? [X:$i]: ((? [Y:$i]: (~ (qmltpeq(X,Y)))))))).
