%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:14 CEST 2022 using command 'downgrade(tff)'.
tff(f_type, type, f: ($i > $o)).
tff(con, conjecture, ({$dia}((! [X:$i]: (f(X)))) => (! [X:$i]: ({$dia}(f(X)))))).
