%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:59 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $o).
tff(con, conjecture, ({$dia}({$dia}({$box}(p))) <=> {$box}(p))).
