%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:49 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $o).
tff(q_type, type, q: $o).
tff(con, conjecture, ({$box}((~ (p) | {$dia}(q))) <=> (~ ({$dia}(p)) | {$dia}(q)))).
