%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:39:48 CEST 2022 using command 'downgrade(tff)'.
tff(p_type, type, p: $o).
tff(con, conjecture, ({$box}({$dia}({$dia}({$box}(p)))) <=> {$box}({$box}(p)))).
