%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:25 CEST 2022 using command 'downgrade(tff)'.
tff(v1_type, type, v1: $o).
tff(v2_type, type, v2: $o).
tff(v3_type, type, v3: $o).
tff(v4_type, type, v4: $o).
tff(persat1, axiom, (v1 | (v2 | (v3 | {$box}({$box}(~ (v1))))))).
tff(persat2, axiom, (v1 | (v2 | (~ (v3) | {$box}({$box}(~ (v3))))))).
tff(persat3, axiom, (v1 | (v2 | (~ (v3) | {$box}({$box}(~ (v4))))))).
tff(persat4, axiom, (v1 | (v2 | ({$box}(~ (v3)) | {$box}({$box}(v1)))))).
tff(persat5, axiom, (v1 | (v3 | ({$box}({$box}(v3)) | {$box}({$box}(v4)))))).
tff(persat6, axiom, (v1 | (v4 | ({$box}(~ (v1)) | {$box}({$box}(~ (v1))))))).
tff(persat7, axiom, (v1 | (~ (v2) | (~ (v4) | {$box}({$box}(~ (v2))))))).
tff(persat8, axiom, (v1 | (~ (v2) | ({$box}(~ (v3)) | {$box}({$box}(v3)))))).
tff(persat9, axiom, (v1 | (~ (v3) | ({$box}(v4) | {$box}({$box}(~ (v4))))))).
tff(persat10, axiom, (v1 | (~ (v3) | ({$box}(~ (v1)) | {$box}({$box}(~ (v1))))))).
tff(persat11, axiom, (v1 | (~ (v4) | ({$box}({$box}(~ (v3))) | {$box}({$box}(~ (v4))))))).
tff(persat12, axiom, (v1 | ({$box}(v1) | ({$box}(~ (v1)) | {$box}({$box}(~ (v1))))))).
tff(persat13, axiom, (v1 | ({$box}(v2) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v2))))))).
tff(persat14, axiom, (v2 | (v3 | (v4 | {$box}({$box}(~ (v4))))))).
tff(persat15, axiom, (v2 | (v4 | (~ (v3) | {$box}({$box}(~ (v4))))))).
tff(persat16, axiom, (v2 | (v4 | ({$box}(~ (v2)) | {$box}({$box}(v2)))))).
tff(persat17, axiom, (v2 | (~ (v1) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v3))))))).
tff(persat18, axiom, (v2 | (~ (v3) | ({$box}(~ (v1)) | {$box}({$box}(~ (v1))))))).
tff(persat19, axiom, (v2 | ({$box}(v4) | ({$box}({$box}(v2)) | {$box}({$box}(v3)))))).
tff(persat20, axiom, (v2 | ({$box}(~ (v1)) | ({$box}({$box}(v3)) | {$box}({$box}(~ (v2))))))).
tff(persat21, axiom, (v2 | ({$box}({$box}(v3)) | ({$box}({$box}(~ (v3))) | {$box}({$box}(~ (v4))))))).
tff(persat22, axiom, (v3 | (v4 | ({$box}(v2) | {$box}({$box}(v1)))))).
tff(persat23, axiom, (v3 | (v4 | ({$box}({$box}(v1)) | {$box}({$box}(~ (v4))))))).
tff(persat24, axiom, (v3 | (v4 | ({$box}({$box}(v2)) | {$box}({$box}(v4)))))).
tff(persat25, axiom, (v3 | (~ (v1) | ({$box}({$box}(v1)) | {$box}({$box}(v2)))))).
tff(persat26, axiom, (v3 | (~ (v4) | ({$box}({$box}(v3)) | {$box}({$box}(~ (v4))))))).
tff(persat27, axiom, (v3 | ({$box}(v1) | ({$box}(~ (v1)) | {$box}({$box}(v4)))))).
tff(persat28, axiom, (v4 | (~ (v1) | ({$box}(v1) | {$box}({$box}(~ (v2))))))).
tff(persat29, axiom, (v4 | (~ (v1) | ({$box}(~ (v1)) | {$box}({$box}(v3)))))).
tff(persat30, axiom, (v4 | (~ (v3) | ({$box}(v1) | {$box}({$box}(v2)))))).
tff(persat31, axiom, (v4 | (~ (v3) | ({$box}({$box}(v1)) | {$box}({$box}(v4)))))).
tff(persat32, axiom, (v4 | ({$box}(~ (v1)) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v1))))))).
tff(persat33, axiom, (~ (v1) | (~ (v2) | ({$box}(v3) | {$box}({$box}(~ (v1))))))).
tff(persat34, axiom, (~ (v1) | (~ (v2) | ({$box}(~ (v4)) | {$box}({$box}(~ (v1))))))).
tff(persat35, axiom, (~ (v1) | (~ (v3) | ({$box}(~ (v3)) | {$box}({$box}(v4)))))).
tff(persat36, axiom, (~ (v1) | (~ (v3) | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v3))))))).
tff(persat37, axiom, (~ (v1) | ({$box}(~ (v1)) | ({$box}({$box}(v1)) | {$box}({$box}(v4)))))).
tff(persat38, axiom, (~ (v1) | ({$box}(~ (v4)) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v4))))))).
tff(persat39, axiom, (~ (v1) | ({$box}({$box}(v1)) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v3))))))).
tff(persat40, axiom, (~ (v2) | (~ (v3) | ({$box}({$box}(v1)) | {$box}({$box}(v4)))))).
tff(persat41, axiom, (~ (v2) | (~ (v4) | ({$box}(~ (v2)) | {$box}({$box}(v3)))))).
tff(persat42, axiom, (~ (v2) | ({$box}(v4) | ({$box}({$box}(v2)) | {$box}({$box}(~ (v3))))))).
tff(persat43, axiom, (~ (v2) | ({$box}({$box}(v3)) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v1))))))).
tff(persat44, axiom, (~ (v3) | (~ (v4) | ({$box}(~ (v4)) | {$box}({$box}(v4)))))).
tff(persat45, axiom, (~ (v3) | ({$box}(v3) | ({$box}(~ (v4)) | {$box}({$box}(v3)))))).
tff(persat46, axiom, (~ (v3) | ({$box}(~ (v4)) | ({$box}({$box}(~ (v2))) | {$box}({$box}(~ (v4))))))).
tff(persat47, axiom, (~ (v4) | ({$box}(v1) | ({$box}({$box}(v3)) | {$box}({$box}(v4)))))).
tff(persat48, axiom, (~ (v4) | ({$box}(v3) | ({$box}({$box}(v2)) | {$box}({$box}(~ (v4))))))).
tff(persat49, axiom, (~ (v4) | ({$box}(v4) | ({$box}(~ (v1)) | {$box}({$box}(v1)))))).
tff(persat50, axiom, (~ (v4) | ({$box}(~ (v2)) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v4))))))).
tff(deontic1, axiom, {$dia}($true)).
tff(result1, conjecture, $false).
