%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:13 CEST 2022 using command 'downgrade(tff)'.
tff(v1_type, type, v1: $o).
tff(v2_type, type, v2: $o).
tff(v3_type, type, v3: $o).
tff(v4_type, type, v4: $o).
tff(v5_type, type, v5: $o).
tff(v6_type, type, v6: $o).
tff(v7_type, type, v7: $o).
tff(v8_type, type, v8: $o).
tff(persat1, axiom, (v1 | (v7 | (~ (v5) | {$box}(~ (v2)))))).
tff(persat2, axiom, (v1 | (v8 | (~ (v4) | {$box}(~ (v2)))))).
tff(persat3, axiom, (v1 | ({$box}(v2) | ({$box}(~ (v1)) | {$box}(~ (v4)))))).
tff(persat4, axiom, (v2 | (~ (v4) | (~ (v7) | {$box}(~ (v2)))))).
tff(persat5, axiom, (v2 | (~ (v8) | ({$box}(v3) | {$box}(~ (v8)))))).
tff(persat6, axiom, (v3 | (~ (v4) | ({$box}(v1) | {$box}(~ (v4)))))).
tff(persat7, axiom, (v3 | (~ (v4) | ({$box}(~ (v2)) | {$box}(~ (v5)))))).
tff(persat8, axiom, (v4 | (v6 | ({$box}(v1) | {$box}(v4))))).
tff(persat9, axiom, (v4 | (v8 | ({$box}(~ (v3)) | {$box}(~ (v4)))))).
tff(persat10, axiom, (v4 | (~ (v5) | ({$box}(~ (v6)) | {$box}(~ (v8)))))).
tff(persat11, axiom, (v4 | (~ (v6) | (~ (v8) | {$box}(v5))))).
tff(persat12, axiom, (v4 | ({$box}(v1) | ({$box}(~ (v2)) | {$box}(~ (v4)))))).
tff(persat13, axiom, (v4 | ({$box}(v6) | ({$box}(v7) | {$box}(~ (v8)))))).
tff(persat14, axiom, (v5 | (~ (v6) | ({$box}(v2) | {$box}(~ (v8)))))).
tff(persat15, axiom, (v6 | (v7 | (~ (v3) | {$box}(~ (v6)))))).
tff(persat16, axiom, (v6 | (~ (v4) | ({$box}(~ (v4)) | {$box}(~ (v6)))))).
tff(persat17, axiom, (v6 | (~ (v7) | ({$box}(v4) | {$box}(v6))))).
tff(persat18, axiom, (v7 | (v8 | (~ (v3) | {$box}(~ (v5)))))).
tff(persat19, axiom, (~ (v1) | (~ (v4) | ({$box}(v1) | {$box}(v8))))).
tff(persat20, axiom, (~ (v1) | (~ (v5) | ({$box}(v5) | {$box}(~ (v5)))))).
tff(persat21, axiom, (~ (v1) | ({$box}(v2) | ({$box}(v4) | {$box}(~ (v7)))))).
tff(persat22, axiom, (~ (v2) | (~ (v6) | ({$box}(v2) | {$box}(~ (v6)))))).
tff(persat23, axiom, (~ (v3) | ({$box}(v1) | ({$box}(~ (v1)) | {$box}(~ (v5)))))).
tff(persat24, axiom, (~ (v3) | ({$box}(v1) | ({$box}(~ (v2)) | {$box}(~ (v3)))))).
tff(persat25, axiom, (~ (v4) | ({$box}(v1) | ({$box}(v3) | {$box}(~ (v7)))))).
tff(persat26, axiom, (~ (v4) | ({$box}(v1) | ({$box}(~ (v1)) | {$box}(~ (v5)))))).
tff(persat27, axiom, (~ (v5) | ({$box}(v5) | ({$box}(~ (v1)) | {$box}(~ (v5)))))).
tff(persat28, axiom, (~ (v7) | ({$box}(v3) | ({$box}(v4) | {$box}(v8))))).
tff(persat29, axiom, (~ (v8) | ({$box}(v2) | ({$box}(v4) | {$box}(~ (v8)))))).
tff(persat30, axiom, (~ (v8) | ({$box}(v2) | ({$box}(~ (v1)) | {$box}(~ (v7)))))).
tff(deontic1, axiom, {$dia}($true)).
tff(result1, conjecture, $false).
