%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:40:28 CEST 2022 using command 'downgrade(tff)'.
tff(v1_type, type, v1: $o).
tff(v2_type, type, v2: $o).
tff(v3_type, type, v3: $o).
tff(v4_type, type, v4: $o).
tff(v5_type, type, v5: $o).
tff(v6_type, type, v6: $o).
tff(v7_type, type, v7: $o).
tff(v8_type, type, v8: $o).
tff(persat1, axiom, (v1 | (v6 | ({$box}({$box}(v6)) | {$box}({$box}(~ (v5))))))).
tff(persat2, axiom, (v1 | (~ (v5) | ({$box}({$box}(~ (v7))) | {$box}({$box}(~ (v8))))))).
tff(persat3, axiom, (v1 | (~ (v8) | ({$box}({$box}(~ (v3))) | {$box}({$box}(~ (v5))))))).
tff(persat4, axiom, (v1 | ({$box}({$box}(~ (v1))) | ({$box}({$box}(~ (v3))) | {$box}({$box}(~ (v4))))))).
tff(persat5, axiom, (v2 | (v3 | (~ (v6) | {$box}({$box}(v3)))))).
tff(persat6, axiom, (v2 | (v3 | ({$box}(v8) | {$box}({$box}(~ (v8))))))).
tff(persat7, axiom, (v2 | (v3 | ({$box}({$box}(v6)) | {$box}({$box}(v8)))))).
tff(persat8, axiom, (v2 | (v6 | (~ (v1) | {$box}({$box}(~ (v8))))))).
tff(persat9, axiom, (v2 | (~ (v4) | ({$box}({$box}(v6)) | {$box}({$box}(v7)))))).
tff(persat10, axiom, (v2 | (~ (v5) | ({$box}(v2) | {$box}({$box}(v7)))))).
tff(persat11, axiom, (v2 | (~ (v6) | ({$box}(~ (v5)) | {$box}({$box}(~ (v3))))))).
tff(persat12, axiom, (v2 | ({$box}(v4) | ({$box}({$box}(v5)) | {$box}({$box}(~ (v8))))))).
tff(persat13, axiom, (v3 | (v5 | (~ (v7) | {$box}({$box}(v3)))))).
tff(persat14, axiom, (v3 | (v8 | ({$box}(~ (v4)) | {$box}({$box}(~ (v2))))))).
tff(persat15, axiom, (v3 | (~ (v4) | ({$box}(~ (v4)) | {$box}({$box}(v5)))))).
tff(persat16, axiom, (v3 | (~ (v4) | ({$box}(~ (v8)) | {$box}({$box}(v7)))))).
tff(persat17, axiom, (v3 | (~ (v8) | ({$box}(~ (v6)) | {$box}({$box}(v4)))))).
tff(persat18, axiom, (v4 | (v6 | ({$box}({$box}(v8)) | {$box}({$box}(~ (v1))))))).
tff(persat19, axiom, (v4 | (v7 | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v7))))))).
tff(persat20, axiom, (v4 | (~ (v7) | ({$box}(~ (v2)) | {$box}({$box}(v6)))))).
tff(persat21, axiom, (v4 | ({$box}(v8) | ({$box}({$box}(v4)) | {$box}({$box}(v6)))))).
tff(persat22, axiom, (v4 | ({$box}(v8) | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v6))))))).
tff(persat23, axiom, (v5 | (v8 | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v4))))))).
tff(persat24, axiom, (v5 | (~ (v2) | ({$box}(~ (v7)) | {$box}({$box}(v6)))))).
tff(persat25, axiom, (v5 | ({$box}(v1) | ({$box}({$box}(v6)) | {$box}({$box}(~ (v1))))))).
tff(persat26, axiom, (v5 | ({$box}(v4) | ({$box}({$box}(v3)) | {$box}({$box}(~ (v3))))))).
tff(persat27, axiom, (v5 | ({$box}(v5) | ({$box}({$box}(~ (v6))) | {$box}({$box}(~ (v7))))))).
tff(persat28, axiom, (v6 | (~ (v1) | ({$box}({$box}(~ (v4))) | {$box}({$box}(~ (v8))))))).
tff(persat29, axiom, (v6 | ({$box}(v7) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v7))))))).
tff(persat30, axiom, (v6 | ({$box}({$box}(v3)) | ({$box}({$box}(v6)) | {$box}({$box}(~ (v6))))))).
tff(persat31, axiom, (v7 | (~ (v3) | ({$box}({$box}(v6)) | {$box}({$box}(~ (v2))))))).
tff(persat32, axiom, (v8 | (~ (v1) | ({$box}(~ (v2)) | {$box}({$box}(~ (v1))))))).
tff(persat33, axiom, (v8 | ({$box}(~ (v2)) | ({$box}(~ (v7)) | {$box}({$box}(v2)))))).
tff(persat34, axiom, (v8 | ({$box}(~ (v3)) | ({$box}({$box}(v3)) | {$box}({$box}(~ (v2))))))).
tff(persat35, axiom, (v8 | ({$box}(~ (v6)) | ({$box}(~ (v8)) | {$box}({$box}(v1)))))).
tff(persat36, axiom, (~ (v2) | (~ (v4) | ({$box}(v5) | {$box}({$box}(~ (v2))))))).
tff(persat37, axiom, (~ (v2) | (~ (v8) | ({$box}(~ (v2)) | {$box}({$box}(v1)))))).
tff(persat38, axiom, (~ (v2) | ({$box}(~ (v1)) | ({$box}(~ (v7)) | {$box}({$box}(v5)))))).
tff(persat39, axiom, (~ (v2) | ({$box}(~ (v1)) | ({$box}({$box}(v2)) | {$box}({$box}(~ (v4))))))).
tff(persat40, axiom, (~ (v2) | ({$box}(~ (v7)) | ({$box}({$box}(~ (v5))) | {$box}({$box}(~ (v6))))))).
tff(persat41, axiom, (~ (v3) | (~ (v7) | ({$box}(v2) | {$box}({$box}(~ (v1))))))).
tff(persat42, axiom, (~ (v3) | ({$box}(v8) | ({$box}(~ (v3)) | {$box}({$box}(~ (v3))))))).
tff(persat43, axiom, (~ (v4) | (~ (v5) | ({$box}(~ (v7)) | {$box}({$box}(v8)))))).
tff(persat44, axiom, (~ (v4) | (~ (v8) | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v8))))))).
tff(persat45, axiom, (~ (v4) | ({$box}(v2) | ({$box}(~ (v1)) | {$box}({$box}(v5)))))).
tff(persat46, axiom, (~ (v5) | (~ (v6) | ({$box}({$box}(v4)) | {$box}({$box}(~ (v6))))))).
tff(persat47, axiom, (~ (v5) | ({$box}(~ (v7)) | ({$box}({$box}(~ (v3))) | {$box}({$box}(~ (v4))))))).
tff(persat48, axiom, (~ (v6) | ({$box}({$box}(v4)) | ({$box}({$box}(v8)) | {$box}({$box}(~ (v4))))))).
tff(persat49, axiom, (~ (v8) | ({$box}(v4) | ({$box}(~ (v5)) | {$box}({$box}(v1)))))).
tff(persat50, axiom, (~ (v8) | ({$box}(~ (v3)) | ({$box}({$box}(~ (v1))) | {$box}({$box}(~ (v5))))))).
tff(deontic1, axiom, {$dia}($true)).
tff(result1, conjecture, $false).
