tff(t_constant_rigid,logic, ( $modal ==
    [$constants == $rigid,
     $quantification == $constant,
     $modalities == $modal_system_T
    ] )).
%%% This output was generated by tptputils, version 1.2.
%%% Generated on Wed Apr 27 15:22:07 CEST 2022 using command 'downgrade(tff)'.
tff(happens_decl, type, happens: ($i > $o)).
tff(bomb_decl, type, bomb: ($i > $o)).
tff(defused_decl, type, defused: ($i > $o)).

%----Necessarily there is a bomb
tff(ax1, axiom-local, {$box} @ ((? [B:$i]: (bomb(B))))).

%----There exists an action
tff(ax2, axiom-local, (? [A:$i]: ({$box} @ ((! [X:$i]: (((bomb(X) & happens(A)) => {$box} @ (bomb(X))))))))).
tff(ax3, axiom-local, {$box} @ ((! [X:$i]: ((? [D:$i]: ({$box} @ (((bomb(X) & happens(D)) => defused(X))))))))).
tff(con, conjecture, {$box} @ ((! [X:$i]: ((? [D:$i]: (((bomb(X) & happens(D)) => defused(X)))))))).
