%------------------------------------------------------------------------------
% File     : GSE914^1.005 : TPTP v8.1.0. Released v8.1.0.
% Domain   : Logic Calculi
% Problem  : Goedel translation of SET914+1 (from TPTP-v5.0.0)
% Version  : [BP13] axioms.
% English  : 

% Refs     : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
%          : [BP13]  Benzmueller & Paulson (2013), Quantified Multimodal Lo
%          : [Ste22] Steen (2022), An Extensible Logic Embedding Tool for L
% Source   : [TPTP]
% Names    : GSE914+1 [QMLTP]

% Status   : Theorem 
% Rating   : ? v8.1.0
% Syntax   : Number of formulae    :   57 (  11 unt;  20 typ;  10 def)
%            Number of atoms       :  418 (  10 equ;   0 cnn)
%            Maximal formula atoms :   58 (  11 avg)
%            Number of connectives :  593 (   1   ~;   1   |;   3   &; 584   @)
%                                         (   1 <=>;   3  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   27 (  11 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :   72 (  72   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   20 (  19 usr;   2 con; 0-3 aty)
%            Number of variables   :   93 (  85   ^   6   !;   2   ?;  93   :)
% SPC      : TH0_THM_EQU_NAR

% Comments : This output was generated by embedproblem, version 1.7.1 (library
%            version 1.3). Generated on Thu Apr 28 13:18:18 EDT 2022 using
%            'modal' embedding, version 1.5.2. Logic specification used:
%            $modal == [$constants == $rigid,$quantification == $constant,
%            $modalities == $modal_system_S5].
%------------------------------------------------------------------------------
thf(mworld,type,
    mworld: $tType ).

thf(mrel_type,type,
    mrel: mworld > mworld > $o ).

thf(mactual_type,type,
    mactual: mworld ).

thf(mlocal_type,type,
    mlocal: ( mworld > $o ) > $o ).

thf(mlocal_def,definition,
    ( mlocal
    = ( ^ [Phi: mworld > $o] : ( Phi @ mactual ) ) ) ).

thf(mnot_type,type,
    mnot: ( mworld > $o ) > mworld > $o ).

thf(mand_type,type,
    mand: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mor_type,type,
    mor: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mimplies_type,type,
    mimplies: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mequiv_type,type,
    mequiv: ( mworld > $o ) > ( mworld > $o ) > mworld > $o ).

thf(mnot_def,definition,
    ( mnot
    = ( ^ [A: mworld > $o,W: mworld] :
          ~ ( A @ W ) ) ) ).

thf(mand_def,definition,
    ( mand
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          & ( B @ W ) ) ) ) ).

thf(mor_def,definition,
    ( mor
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
          | ( B @ W ) ) ) ) ).

thf(mimplies_def,definition,
    ( mimplies
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
         => ( B @ W ) ) ) ) ).

thf(mequiv_def,definition,
    ( mequiv
    = ( ^ [A: mworld > $o,B: mworld > $o,W: mworld] :
          ( ( A @ W )
        <=> ( B @ W ) ) ) ) ).

thf(mbox_type,type,
    mbox: ( mworld > $o ) > mworld > $o ).

thf(mbox_def,definition,
    ( mbox
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ! [V: mworld] :
          ( ( mrel @ W @ V )
         => ( Phi @ V ) ) ) ) ).

thf(mdia_type,type,
    mdia: ( mworld > $o ) > mworld > $o ).

thf(mdia_def,definition,
    ( mdia
    = ( ^ [Phi: mworld > $o,W: mworld] :
        ? [V: mworld] :
          ( ( mrel @ W @ V )
          & ( Phi @ V ) ) ) ) ).

thf(mrel_reflexive,axiom,
    ! [W: mworld] : ( mrel @ W @ W ) ).

thf(mrel_euclidean,axiom,
    ! [W: mworld,V: mworld,U: mworld] :
      ( ( ( mrel @ W @ U )
        & ( mrel @ W @ V ) )
     => ( mrel @ U @ V ) ) ).

thf(mforall_di_type,type,
    mforall_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mforall_di_def,definition,
    ( mforall_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ! [X: $i] : ( A @ X @ W ) ) ) ).

thf(mexists_di_type,type,
    mexists_di: ( $i > mworld > $o ) > mworld > $o ).

thf(mexists_di_def,definition,
    ( mexists_di
    = ( ^ [A: $i > mworld > $o,W: mworld] :
        ? [X: $i] : ( A @ X @ W ) ) ) ).

thf(empty_set_decl,type,
    empty_set: $i ).

thf(qmltpeq_decl,type,
    qmltpeq: $i > $i > mworld > $o ).

thf(in_decl,type,
    in: $i > $i > mworld > $o ).

thf(disjoint_decl,type,
    disjoint: $i > $i > mworld > $o ).

thf(empty_decl,type,
    empty: $i > mworld > $o ).

thf(set_intersection2_decl,type,
    set_intersection2: $i > $i > $i ).

thf(unordered_pair_decl,type,
    unordered_pair: $i > $i > $i ).

thf(reflexivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] : ( mbox @ ( qmltpeq @ X @ X ) ) ) ) ) ).

thf(symmetry,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ X ) ) ) ) ) ) ) ) ) ).

thf(transitivity,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [X: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [Y: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [Z: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ X @ Y ) ) @ ( mbox @ ( qmltpeq @ Y @ Z ) ) ) @ ( mbox @ ( qmltpeq @ X @ Z ) ) ) ) ) ) ) ) ) ) ) ).

thf(set_intersection2_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( qmltpeq @ ( set_intersection2 @ A @ C ) @ ( set_intersection2 @ B @ C ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(set_intersection2_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( qmltpeq @ ( set_intersection2 @ C @ A ) @ ( set_intersection2 @ C @ B ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(unordered_pair_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( qmltpeq @ ( unordered_pair @ A @ C ) @ ( unordered_pair @ B @ C ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(unordered_pair_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( qmltpeq @ ( unordered_pair @ C @ A ) @ ( unordered_pair @ C @ B ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(disjoint_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( disjoint @ A @ C ) ) ) @ ( mbox @ ( disjoint @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(disjoint_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( disjoint @ C @ A ) ) ) @ ( mbox @ ( disjoint @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(empty_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( empty @ A ) ) ) @ ( mbox @ ( empty @ B ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_1,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ A @ C ) ) ) @ ( mbox @ ( in @ B @ C ) ) ) ) ) ) ) ) ) ) ) ).

thf(in_substitution_2,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( qmltpeq @ A @ B ) ) @ ( mbox @ ( in @ C @ A ) ) ) @ ( mbox @ ( in @ C @ B ) ) ) ) ) ) ) ) ) ) ) ).

thf(antisymmetry_r2_hidden,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mbox @ ( in @ A @ B ) ) @ ( mbox @ ( mnot @ ( mbox @ ( in @ B @ A ) ) ) ) ) ) ) ) ) ) ) ).

thf(commutativity_k2_tarski,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( qmltpeq @ ( unordered_pair @ A @ B ) @ ( unordered_pair @ B @ A ) ) ) ) ) ) ) ) ).

thf(commutativity_k3_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( qmltpeq @ ( set_intersection2 @ A @ B ) @ ( set_intersection2 @ B @ A ) ) ) ) ) ) ) ) ).

thf(d1_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mand
            @ ( mbox
              @ ( mimplies @ ( mbox @ ( qmltpeq @ A @ empty_set ) )
                @ ( mbox
                  @ ( mforall_di
                    @ ^ [B: $i] : ( mbox @ ( mnot @ ( mbox @ ( in @ B @ A ) ) ) ) ) ) ) )
            @ ( mbox
              @ ( mimplies
                @ ( mbox
                  @ ( mforall_di
                    @ ^ [B: $i] : ( mbox @ ( mnot @ ( mbox @ ( in @ B @ A ) ) ) ) ) )
                @ ( mbox @ ( qmltpeq @ A @ empty_set ) ) ) ) ) ) ) ) ).

thf(d2_tarski,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] :
                        ( mand
                        @ ( mbox
                          @ ( mimplies @ ( mbox @ ( qmltpeq @ C @ ( unordered_pair @ A @ B ) ) )
                            @ ( mbox
                              @ ( mforall_di
                                @ ^ [D: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( in @ D @ C ) ) @ ( mor @ ( mbox @ ( qmltpeq @ D @ A ) ) @ ( mbox @ ( qmltpeq @ D @ B ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mor @ ( mbox @ ( qmltpeq @ D @ A ) ) @ ( mbox @ ( qmltpeq @ D @ B ) ) ) @ ( mbox @ ( in @ D @ C ) ) ) ) ) ) ) ) )
                        @ ( mbox
                          @ ( mimplies
                            @ ( mbox
                              @ ( mforall_di
                                @ ^ [D: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( in @ D @ C ) ) @ ( mor @ ( mbox @ ( qmltpeq @ D @ A ) ) @ ( mbox @ ( qmltpeq @ D @ B ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mor @ ( mbox @ ( qmltpeq @ D @ A ) ) @ ( mbox @ ( qmltpeq @ D @ B ) ) ) @ ( mbox @ ( in @ D @ C ) ) ) ) ) ) )
                            @ ( mbox @ ( qmltpeq @ C @ ( unordered_pair @ A @ B ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(d3_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] :
                        ( mand
                        @ ( mbox
                          @ ( mimplies @ ( mbox @ ( qmltpeq @ C @ ( set_intersection2 @ A @ B ) ) )
                            @ ( mbox
                              @ ( mforall_di
                                @ ^ [D: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( in @ D @ C ) ) @ ( mand @ ( mbox @ ( in @ D @ A ) ) @ ( mbox @ ( in @ D @ B ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( in @ D @ A ) ) @ ( mbox @ ( in @ D @ B ) ) ) @ ( mbox @ ( in @ D @ C ) ) ) ) ) ) ) ) )
                        @ ( mbox
                          @ ( mimplies
                            @ ( mbox
                              @ ( mforall_di
                                @ ^ [D: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( in @ D @ C ) ) @ ( mand @ ( mbox @ ( in @ D @ A ) ) @ ( mbox @ ( in @ D @ B ) ) ) ) ) @ ( mbox @ ( mimplies @ ( mand @ ( mbox @ ( in @ D @ A ) ) @ ( mbox @ ( in @ D @ B ) ) ) @ ( mbox @ ( in @ D @ C ) ) ) ) ) ) )
                            @ ( mbox @ ( qmltpeq @ C @ ( set_intersection2 @ A @ B ) ) ) ) ) ) ) ) ) ) ) ) ) ).

thf(d7_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mand @ ( mbox @ ( mimplies @ ( mbox @ ( disjoint @ A @ B ) ) @ ( mbox @ ( qmltpeq @ ( set_intersection2 @ A @ B ) @ empty_set ) ) ) ) @ ( mbox @ ( mimplies @ ( mbox @ ( qmltpeq @ ( set_intersection2 @ A @ B ) @ empty_set ) ) @ ( mbox @ ( disjoint @ A @ B ) ) ) ) ) ) ) ) ) ) ).

thf(fc1_xboole_0,axiom,
    mlocal @ ( mbox @ ( empty @ empty_set ) ) ).

thf(idempotence_k3_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( qmltpeq @ ( set_intersection2 @ A @ A ) @ A ) ) ) ) ) ) ) ).

thf(rc1_xboole_0,axiom,
    ( mlocal
    @ ( mexists_di
      @ ^ [A: $i] : ( mbox @ ( empty @ A ) ) ) ) ).

thf(rc2_xboole_0,axiom,
    ( mlocal
    @ ( mexists_di
      @ ^ [A: $i] : ( mbox @ ( mnot @ ( mbox @ ( empty @ A ) ) ) ) ) ) ).

thf(symmetry_r1_xboole_0,axiom,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] : ( mbox @ ( mimplies @ ( mbox @ ( disjoint @ A @ B ) ) @ ( mbox @ ( disjoint @ B @ A ) ) ) ) ) ) ) ) ) ).

thf(t55_zfmisc_1,conjecture,
    ( mlocal
    @ ( mbox
      @ ( mforall_di
        @ ^ [A: $i] :
            ( mbox
            @ ( mforall_di
              @ ^ [B: $i] :
                  ( mbox
                  @ ( mforall_di
                    @ ^ [C: $i] : ( mbox @ ( mnot @ ( mand @ ( mbox @ ( disjoint @ ( unordered_pair @ A @ B ) @ C ) ) @ ( mbox @ ( in @ A @ C ) ) ) ) ) ) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
